spec:
  annotations:
    description: |
      Memory major pages are occurring at very high rate at {{ $labels.host }}, 500 major page faults per second for the last 15 minutes, is currently at {{ printf "%.2f" $value }}.
      Please check that there is enough memory available at this instance.
    summary: Memory major page faults are occurring at very high rate.
  execErrState: OK
  expressions:
    query:
      datasourceUID:
        svariable: OPENOBSERVE_PROMETHEUS_DATASOURCE_UID
      model:
        datasource:
          type: prometheus
          uid:
            svariable: OPENOBSERVE_PROMETHEUS_DATASOURCE_UID
        expr: rate(node_vmstat_pgmajfault[5m]) > 500
        instant: true
        range: false
        refId: query
      queryType: prometheus
      relativeTimeRange:
        from: 11m
        to: 1m
    prometheus_math:
      model:
        datasource:
          type: __expr__
          uid: __expr__
        expression: is_number($query) || is_nan($query) || is_inf($query)
        refId: prometheus_math
        type: math
      queryType: math
    threshold:
      model:
        conditions:
          - evaluator:
              params:
                - 0
              type: gt
        datasource:
          type: __expr__
          uid: __expr__
        expression: prometheus_math
        refId: threshold
        type: threshold
      queryType: threshold
      source: true
  for: 15m
  labels:
    alert_category: failure
    entity_type: node
    severity: warning
  missingSeriesEvalsToResolve: 1
  noDataState: OK
  notificationSettings:
    receiver: empty
  paused: false
  title: NodeMemoryMajorPagesFaults
  trigger:
    interval: 1m
