spec:
  annotations:
    description: Filesystem on {{ $labels.device }}, mounted on {{ $labels.mountpoint }}, at {{ $labels.host }} has only {{ printf "%.2f" $value }}% available inodes left and is filling up.
    summary: Filesystem is predicted to run out of inodes within the next 24 hours.
  execErrState: OK
  expressions:
    query:
      datasourceUID:
        svariable: OPENOBSERVE_PROMETHEUS_DATASOURCE_UID
      model:
        datasource:
          type: prometheus
          uid:
            svariable: OPENOBSERVE_PROMETHEUS_DATASOURCE_UID
        expr: |
          node_filesystem_files_free{fstype!="", mountpoint!=""} / node_filesystem_files{fstype!="", mountpoint!=""} * 100 < 40
          and
          predict_linear(node_filesystem_files_free{fstype!="", mountpoint!=""}[6h], 24 * 60 * 60) < 0
          and
          node_filesystem_readonly{fstype!="", mountpoint!=""} == 0
        instant: true
        range: false
        refId: query
      queryType: prometheus
      relativeTimeRange:
        from: 11m
        to: 1m
    prometheus_math:
      model:
        datasource:
          type: __expr__
          uid: __expr__
        expression: is_number($query) || is_nan($query) || is_inf($query)
        refId: prometheus_math
        type: math
      queryType: math
    threshold:
      model:
        conditions:
          - evaluator:
              params:
                - 0
              type: gt
        datasource:
          type: __expr__
          uid: __expr__
        expression: prometheus_math
        refId: threshold
        type: threshold
      queryType: threshold
      source: true
  for: 1h
  labels:
    alert_category: failure
    entity_type: filesystem
    severity: warning
  missingSeriesEvalsToResolve: 1
  noDataState: OK
  notificationSettings:
    receiver:
      svariable: DEFAULT_CONTACT_POINT
  paused: false
  title: NodeFilesystemFilesFillingUp
  trigger:
    interval: 1m
