spec:
  annotations:
    description: Node Exporter text file collector on {{ $labels.host }} failed to scrape.
    summary: Node Exporter text file collector failed to scrape.
  execErrState: OK
  expressions:
    query:
      datasourceUID:
        svariable: OPENOBSERVE_PROMETHEUS_DATASOURCE_UID
      model:
        datasource:
          type: prometheus
          uid:
            svariable: OPENOBSERVE_PROMETHEUS_DATASOURCE_UID
        expr: node_textfile_scrape_error == 1
        instant: true
        range: false
        refId: query
      queryType: prometheus
      relativeTimeRange:
        from: 11m
        to: 1m
    prometheus_math:
      model:
        datasource:
          type: __expr__
          uid: __expr__
        expression: is_number($query) || is_nan($query) || is_inf($query)
        refId: prometheus_math
        type: math
      queryType: math
    threshold:
      model:
        conditions:
          - evaluator:
              params:
                - 0
              type: gt
        datasource:
          type: __expr__
          uid: __expr__
        expression: prometheus_math
        refId: threshold
        type: threshold
      queryType: threshold
      source: true
  labels:
    alert_category: failure
    entity_type: node
    severity: warning
  missingSeriesEvalsToResolve: 1
  noDataState: OK
  notificationSettings:
    receiver: empty
  paused: false
  title: NodeTextFileCollectorScrapeError
  trigger:
    interval: 1m
