spec:
  annotations:
    description: |
      Memory is filling up at {{ $labels.host }}, has been above 90% for the last 15 minutes, is currently at {{ printf "%.2f" $value }}%.
    summary: Host is running out of memory.
  execErrState: OK
  expressions:
    query:
      datasourceUID:
        svariable: OPENOBSERVE_PROMETHEUS_DATASOURCE_UID
      model:
        datasource:
          type: prometheus
          uid:
            svariable: OPENOBSERVE_PROMETHEUS_DATASOURCE_UID
        expr: 100 - (node_memory_memavailable_bytes / node_memory_memtotal_bytes * 100) > 90
        instant: true
        range: false
        refId: query
      queryType: prometheus
      relativeTimeRange:
        from: 11m
        to: 1m
    prometheus_math:
      model:
        datasource:
          type: __expr__
          uid: __expr__
        expression: is_number($query) || is_nan($query) || is_inf($query)
        refId: prometheus_math
        type: math
      queryType: math
    threshold:
      model:
        conditions:
          - evaluator:
              params:
                - 0
              type: gt
        datasource:
          type: __expr__
          uid: __expr__
        expression: prometheus_math
        refId: threshold
        type: threshold
      queryType: threshold
      source: true
  for: 15m
  labels:
    alert_category: failure
    entity_type: node
    severity: warning
  missingSeriesEvalsToResolve: 1
  noDataState: OK
  notificationSettings:
    receiver: empty
  paused: false
  title: NodeMemoryHighUtilization
  trigger:
    interval: 1m
