spec:
  annotations:
    description: |
      CPU usage at {{ $labels.host }} has been above 90% for the last 15 minutes, is currently at {{ printf "%.2f" $value }}%.
      Note that 'iowait' CPU mode is excluded from total utilization.
    summary: High CPU usage.
  execErrState: OK
  expressions:
    query:
      datasourceUID:
        svariable: OPENOBSERVE_PROMETHEUS_DATASOURCE_UID
      model:
        datasource:
          type: prometheus
          uid:
            svariable: OPENOBSERVE_PROMETHEUS_DATASOURCE_UID
        expr: sum without (mode) (avg without (cpu) (rate(node_cpu_seconds_total{mode!~"idle|iowait"}[2m]))) * 100 > 90
        instant: true
        range: false
        refId: query
      queryType: prometheus
      relativeTimeRange:
        from: 11m
        to: 1m
    prometheus_math:
      model:
        datasource:
          type: __expr__
          uid: __expr__
        expression: is_number($query) || is_nan($query) || is_inf($query)
        refId: prometheus_math
        type: math
      queryType: math
    threshold:
      model:
        conditions:
          - evaluator:
              params:
                - 0
              type: gt
        datasource:
          type: __expr__
          uid: __expr__
        expression: prometheus_math
        refId: threshold
        type: threshold
      queryType: threshold
      source: true
  for: 15m
  labels:
    alert_category: failure
    entity_type: node
    severity: info
  missingSeriesEvalsToResolve: 2
  noDataState: OK
  notificationSettings:
    receiver: empty
  paused: false
  title: NodeCPUHighUsage
  trigger:
    interval: 1m
