spec:
  annotations:
    description: RAID array '{{ $labels.device }}' at {{ $labels.host }} is in degraded state due to one or more disks failures. Number of spare drives is insufficient to fix issue automatically.
    summary: RAID Array is degraded.
  execErrState: OK
  expressions:
    query:
      datasourceUID:
        svariable: OPENOBSERVE_PROMETHEUS_DATASOURCE_UID
      model:
        datasource:
          type: prometheus
          uid:
            svariable: OPENOBSERVE_PROMETHEUS_DATASOURCE_UID
        expr: node_md_disks_required{device!=""} - ignoring (state) (node_md_disks{state="active", device!=""}) > 0
        instant: true
        range: false
        refId: query
      queryType: prometheus
      relativeTimeRange:
        from: 11m
        to: 1m
    prometheus_math:
      model:
        datasource:
          type: __expr__
          uid: __expr__
        expression: is_number($query) || is_nan($query) || is_inf($query)
        refId: prometheus_math
        type: math
      queryType: math
    threshold:
      model:
        conditions:
          - evaluator:
              params:
                - 0
              type: gt
        datasource:
          type: __expr__
          uid: __expr__
        expression: prometheus_math
        refId: threshold
        type: threshold
      queryType: threshold
      source: true
  for: 15m
  labels:
    alert_category: failure
    entity_type: node
    severity: critical
  missingSeriesEvalsToResolve: 1
  noDataState: OK
  notificationSettings:
    receiver: empty
  paused: false
  title: NodeRAIDDegraded
  trigger:
    interval: 1m
