interfaces = []

exclude = [
    "**/*__pycache__",
    "**/*egg-info",
    "**/docs",
    "**/tests",
    "**/venv",
    "**/image",
]

source_roots = [
    "tool/homelab-backup/src",
    "tool/homelab-config/src",
    "tool/homelab-docker/src",
    "tool/homelab-extract/src",
    "tool/homelab-global/src",
    "tool/homelab-mail/src",
    "tool/homelab-network/src",
    "tool/homelab-pydantic/src",
    "tool/homelab-restic/src",
    "tool/homelab-s3/src",
    "tool/homelab-secret/src",
    "tool/homelab-sequence/src",
    "tool/homelab-vpn/src",
    "tool/config/homelab-traefik-config/src",
    "tool/config/homelab-hatchet-config/src",
    "service/homelab-backup-service/src",
    "service/homelab-balite-service/src",
    "service/homelab-barman-service/src",
    "service/homelab-extra-service/src",
    "service/homelab-hatchet-service/src",
    "service/homelab-kanidm-service/src",
    "service/homelab-litestream-service/src",
    "service/homelab-restic-service/src",
    "service/homelab-tailscale-service/src",
    "service/homelab-traefik-service/src",
    "service/homelab-vector-service/src",
]

external.exclude = ["paramiko"]
