services:
  restic:
    config:
      hatchet:
        scheduler:
          check-read-data:
            workflow: restic-check
            schedules:
              - "0 5 * * sat" # 5am every saturday
            input:
              profiles: [all]
              check:
                read-data: 2.5T
          forget-prune-check:
            workflow: restic-forget-prune-check
            schedules:
              - "0 7 * * sun" # 7am every sunday
            input: null
