services:
  restic:
    config:
      hatchet:
        scheduler:
          check-read-data:
            workflow: restic-check
            schedules:
              - "0 5 8-14 * sat" # 5am the second saturday of the month
              - "0 5 22-28 * sat" # 5am the fourth saturday of the month
            input:
              profiles: [all]
              check:
                read-data: 2T
          forget-prune-check:
            workflow: restic-forget-prune-check
            schedules:
              - "0 7 * * sun" # 7am every sunday
            input: null
