services:
  restic:
    config:
      hatchet:
        scheduler:
          check-read-data-main:
            workflow: restic-check
            schedules:
              - "0 5 * * sat" # 5am every saturday
            input:
              profiles: "repository-main"
              check:
                read-data: true
          check-read-data-iso:
            workflow: restic-check
            schedules:
              - "0 5 * * sat" # 5am every saturday
            input:
              profiles: "repository-iso"
              check:
                read-data: 2T
          forget-prune-check:
            workflow: restic-forget-prune-check
            schedules:
              - "0 7 * * sun" # 7am every sunday
            input: null
