services:
  traefik:
    container:
      observability:
        transforms:
          access-log:
            source:
              extract:
                kv:
                  geolite: |
                    geoip_asn, geoip_err = get_enrichment_table_record("geolite-asn", {"ip": .client_host })
                    if geoip_err != null {
                      geoip_asn = {}
                    }

                    geoip_city, geoip_err = get_enrichment_table_record("geolite-city", {"ip": .client_host })
                    if geoip_err != null {
                      geoip_city = {}
                    } else {
                      if geoip_city.city.names != null {
                        geoip_city.city.name = del(geoip_city.city.names).en
                      }
                      if geoip_city.continent.names != null {
                        geoip_city.continent.name = del(geoip_city.continent.names).en
                      }
                      if geoip_city.country.names != null {
                        geoip_city.country.name = del(geoip_city.country.names).en
                      }
                      if geoip_city.registered_country.names != null {
                        geoip_city.registered_country.name = del(geoip_city.registered_country.names).en
                      }
                      if geoip_city.subdivisions != null {
                        geoip_city.subdivisions = map_values(array!(geoip_city.subdivisions)) -> |value| {
                          if value.names != null {
                            value.name = del(value.names).en
                          }
                          value
                        }
                      }
                    }

                    .geoip = merge(geoip_asn, geoip_city)
