services:
  kanidm:
    config:
      state:
        systems:
          oauth2:
            kanidm:
              public: true
              display-name: Kanidm
              origin-landing:
                hostname: kanidm
                record: solar
                scheme: https
              prefer-short-username: true
  traefik:
    config:
      entrypoint:
        config:
          https:
            timeout:
              read: 12h
              write: 12h
              idle: 12h
      record:
        config:
          sun:
            entrypoint: https
          solar:
            entrypoint: https
      plugins:
        oidc:
          name: github.com/sevensolutions/traefik-oidc-auth
          version: "v0.18.0"
      traefik:
        dynamic:
          oidc:
            name: oidc
            plugin: oidc
            data:
              LogLevel: INFO
              Secret:
                secret: oidc
              Provider:
                Url:
                  extract:
                    hostname: kanidm
                    record: solar
                    scheme: https
                  transform:
                    string:
                      template: "{value}/oauth2/openid/kanidm"
                ClientId: kanidm
                UsePkce: true
              Scopes: ["openid", "profile", "email"]
              Headers:
                - Name: X-Remote-User
                  Value: "{{`{{ .claims.preferred_username }}`}}"
                - Name: X-Remote-Name
                  Value: "{{`{{ .claims.name }}`}}"
                - Name: X-Remote-Email
                  Value: "{{`{{ .claims.email }}`}}"
          redirect-admin:
            name: redirect-admin
            data:
              redirectRegex:
                regex: "^https://([^/]+)/?$"
                replacement: "https://${{1}}/admin/"
    secrets:
      oidc:
        length: 32
