docker:
  volumes:
    local:
      traefik-data:
        active: false
services:
  traefik:
    config:
      record:
        config:
          earth:
            entrypoint: "https"
    container:
      hosts:
        - hostname:
            hostname: openobserve-grpc
            record: sun
          host: sun
      wud:
