# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .account_settings import *
from .dns_record import *
from .dns_settings import *
from .dns_zone import *
from .get_account_settings import *
from .get_dns_record import *
from .get_dns_settings import *
from .get_dns_zone import *
from .get_group import *
from .get_identity_provider import *
from .get_nameserver_group import *
from .get_network import *
from .get_network_resource import *
from .get_network_router import *
from .get_peer import *
from .get_peers import *
from .get_policy import *
from .get_posture_check import *
from .get_reverse_proxy_clusters import *
from .get_reverse_proxy_domain import *
from .get_reverse_proxy_service import *
from .get_route import *
from .get_scim import *
from .get_setup_key import *
from .get_token import *
from .get_user import *
from .group import *
from .identity_provider import *
from .nameserver_group import *
from .network import *
from .network_resource import *
from .network_router import *
from .peer import *
from .policy import *
from .posture_check import *
from .provider import *
from .reverse_proxy_domain import *
from .reverse_proxy_service import *
from .route import *
from .scim import *
from .setup_key import *
from .token import *
from .user import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_netbird.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_netbird.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "netbird",
  "mod": "index/accountSettings",
  "fqn": "pulumi_netbird",
  "classes": {
   "netbird:index/accountSettings:AccountSettings": "AccountSettings"
  }
 },
 {
  "pkg": "netbird",
  "mod": "index/dnsRecord",
  "fqn": "pulumi_netbird",
  "classes": {
   "netbird:index/dnsRecord:DnsRecord": "DnsRecord"
  }
 },
 {
  "pkg": "netbird",
  "mod": "index/dnsSettings",
  "fqn": "pulumi_netbird",
  "classes": {
   "netbird:index/dnsSettings:DnsSettings": "DnsSettings"
  }
 },
 {
  "pkg": "netbird",
  "mod": "index/dnsZone",
  "fqn": "pulumi_netbird",
  "classes": {
   "netbird:index/dnsZone:DnsZone": "DnsZone"
  }
 },
 {
  "pkg": "netbird",
  "mod": "index/group",
  "fqn": "pulumi_netbird",
  "classes": {
   "netbird:index/group:Group": "Group"
  }
 },
 {
  "pkg": "netbird",
  "mod": "index/identityProvider",
  "fqn": "pulumi_netbird",
  "classes": {
   "netbird:index/identityProvider:IdentityProvider": "IdentityProvider"
  }
 },
 {
  "pkg": "netbird",
  "mod": "index/nameserverGroup",
  "fqn": "pulumi_netbird",
  "classes": {
   "netbird:index/nameserverGroup:NameserverGroup": "NameserverGroup"
  }
 },
 {
  "pkg": "netbird",
  "mod": "index/network",
  "fqn": "pulumi_netbird",
  "classes": {
   "netbird:index/network:Network": "Network"
  }
 },
 {
  "pkg": "netbird",
  "mod": "index/networkResource",
  "fqn": "pulumi_netbird",
  "classes": {
   "netbird:index/networkResource:NetworkResource": "NetworkResource"
  }
 },
 {
  "pkg": "netbird",
  "mod": "index/networkRouter",
  "fqn": "pulumi_netbird",
  "classes": {
   "netbird:index/networkRouter:NetworkRouter": "NetworkRouter"
  }
 },
 {
  "pkg": "netbird",
  "mod": "index/peer",
  "fqn": "pulumi_netbird",
  "classes": {
   "netbird:index/peer:Peer": "Peer"
  }
 },
 {
  "pkg": "netbird",
  "mod": "index/policy",
  "fqn": "pulumi_netbird",
  "classes": {
   "netbird:index/policy:Policy": "Policy"
  }
 },
 {
  "pkg": "netbird",
  "mod": "index/postureCheck",
  "fqn": "pulumi_netbird",
  "classes": {
   "netbird:index/postureCheck:PostureCheck": "PostureCheck"
  }
 },
 {
  "pkg": "netbird",
  "mod": "index/reverseProxyDomain",
  "fqn": "pulumi_netbird",
  "classes": {
   "netbird:index/reverseProxyDomain:ReverseProxyDomain": "ReverseProxyDomain"
  }
 },
 {
  "pkg": "netbird",
  "mod": "index/reverseProxyService",
  "fqn": "pulumi_netbird",
  "classes": {
   "netbird:index/reverseProxyService:ReverseProxyService": "ReverseProxyService"
  }
 },
 {
  "pkg": "netbird",
  "mod": "index/route",
  "fqn": "pulumi_netbird",
  "classes": {
   "netbird:index/route:Route": "Route"
  }
 },
 {
  "pkg": "netbird",
  "mod": "index/scim",
  "fqn": "pulumi_netbird",
  "classes": {
   "netbird:index/scim:Scim": "Scim"
  }
 },
 {
  "pkg": "netbird",
  "mod": "index/setupKey",
  "fqn": "pulumi_netbird",
  "classes": {
   "netbird:index/setupKey:SetupKey": "SetupKey"
  }
 },
 {
  "pkg": "netbird",
  "mod": "index/token",
  "fqn": "pulumi_netbird",
  "classes": {
   "netbird:index/token:Token": "Token"
  }
 },
 {
  "pkg": "netbird",
  "mod": "index/user",
  "fqn": "pulumi_netbird",
  "classes": {
   "netbird:index/user:User": "User"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "netbird",
  "token": "pulumi:providers:netbird",
  "fqn": "pulumi_netbird",
  "class": "Provider"
 }
]
"""
)
