# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'NameserverGroupNameserverArgs',
    'NameserverGroupNameserverArgsDict',
    'PolicyRuleArgs',
    'PolicyRuleArgsDict',
    'PolicyRuleDestinationResourceArgs',
    'PolicyRuleDestinationResourceArgsDict',
    'PolicyRulePortRangeArgs',
    'PolicyRulePortRangeArgsDict',
    'PolicyRuleSourceResourceArgs',
    'PolicyRuleSourceResourceArgsDict',
    'PostureCheckGeoLocationCheckArgs',
    'PostureCheckGeoLocationCheckArgsDict',
    'PostureCheckGeoLocationCheckLocationArgs',
    'PostureCheckGeoLocationCheckLocationArgsDict',
    'PostureCheckNetbirdVersionCheckArgs',
    'PostureCheckNetbirdVersionCheckArgsDict',
    'PostureCheckOsVersionCheckArgs',
    'PostureCheckOsVersionCheckArgsDict',
    'PostureCheckPeerNetworkRangeCheckArgs',
    'PostureCheckPeerNetworkRangeCheckArgsDict',
    'PostureCheckProcessCheckArgs',
    'PostureCheckProcessCheckArgsDict',
    'ReverseProxyServiceAuthArgs',
    'ReverseProxyServiceAuthArgsDict',
    'ReverseProxyServiceAuthBearerAuthArgs',
    'ReverseProxyServiceAuthBearerAuthArgsDict',
    'ReverseProxyServiceAuthLinkAuthArgs',
    'ReverseProxyServiceAuthLinkAuthArgsDict',
    'ReverseProxyServiceAuthPasswordAuthArgs',
    'ReverseProxyServiceAuthPasswordAuthArgsDict',
    'ReverseProxyServiceAuthPinAuthArgs',
    'ReverseProxyServiceAuthPinAuthArgsDict',
    'ReverseProxyServiceTargetArgs',
    'ReverseProxyServiceTargetArgsDict',
    'GetPolicyRuleArgs',
    'GetPolicyRuleArgsDict',
    'GetPolicyRuleDestinationResourceArgs',
    'GetPolicyRuleDestinationResourceArgsDict',
    'GetPolicyRulePortRangeArgs',
    'GetPolicyRulePortRangeArgsDict',
    'GetPolicyRuleSourceResourceArgs',
    'GetPolicyRuleSourceResourceArgsDict',
]

class NameserverGroupNameserverArgsDict(TypedDict):
    ip: pulumi.Input[_builtins.str]
    """
    Nameserver IP
    """
    ns_type: NotRequired[pulumi.Input[_builtins.str]]
    """
    Nameserver Type
    """
    port: NotRequired[pulumi.Input[_builtins.float]]
    """
    Nameserver Port
    """

@pulumi.input_type
class NameserverGroupNameserverArgs:
    def __init__(__self__, *,
                 ip: pulumi.Input[_builtins.str],
                 ns_type: Optional[pulumi.Input[_builtins.str]] = None,
                 port: Optional[pulumi.Input[_builtins.float]] = None):
        """
        :param pulumi.Input[_builtins.str] ip: Nameserver IP
        :param pulumi.Input[_builtins.str] ns_type: Nameserver Type
        :param pulumi.Input[_builtins.float] port: Nameserver Port
        """
        pulumi.set(__self__, "ip", ip)
        if ns_type is not None:
            pulumi.set(__self__, "ns_type", ns_type)
        if port is not None:
            pulumi.set(__self__, "port", port)

    @_builtins.property
    @pulumi.getter
    def ip(self) -> pulumi.Input[_builtins.str]:
        """
        Nameserver IP
        """
        return pulumi.get(self, "ip")

    @ip.setter
    def ip(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "ip", value)

    @_builtins.property
    @pulumi.getter(name="nsType")
    def ns_type(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Nameserver Type
        """
        return pulumi.get(self, "ns_type")

    @ns_type.setter
    def ns_type(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "ns_type", value)

    @_builtins.property
    @pulumi.getter
    def port(self) -> Optional[pulumi.Input[_builtins.float]]:
        """
        Nameserver Port
        """
        return pulumi.get(self, "port")

    @port.setter
    def port(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "port", value)


class PolicyRuleArgsDict(TypedDict):
    name: pulumi.Input[_builtins.str]
    """
    Policy Name
    """
    action: NotRequired[pulumi.Input[_builtins.str]]
    """
    Policy Rule Action (accept|drop)
    """
    authorized_groups: NotRequired[pulumi.Input[Mapping[str, pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]]]
    """
    Map of source group IDs to a list of local users authorized for SSH access. Keys must be group IDs present in <span pulumi-lang-nodejs="`sources`" pulumi-lang-dotnet="`Sources`" pulumi-lang-go="`sources`" pulumi-lang-python="`sources`" pulumi-lang-yaml="`sources`" pulumi-lang-java="`sources`">`sources`</span>. If not set, all local users are permitted. Only applicable when protocol is `netbird-ssh`.
    """
    bidirectional: NotRequired[pulumi.Input[_builtins.bool]]
    """
    Policy Rule Bidirectional
    """
    description: NotRequired[pulumi.Input[_builtins.str]]
    """
    Policy description
    """
    destination_resource: NotRequired[pulumi.Input['PolicyRuleDestinationResourceArgsDict']]
    """
    Policy Rule Destination Resource (mutually exclusive with destinations)
    """
    destinations: NotRequired[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]
    """
    Policy Rule Destination Groups (mutually exclusive with destination_resource)
    """
    enabled: NotRequired[pulumi.Input[_builtins.bool]]
    """
    Policy Rule Enabled
    """
    id: NotRequired[pulumi.Input[_builtins.str]]
    """
    Policy ID
    """
    port_ranges: NotRequired[pulumi.Input[Sequence[pulumi.Input['PolicyRulePortRangeArgsDict']]]]
    """
    Policy Rule Port Ranges (mutually exclusive with ports)
    """
    ports: NotRequired[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]
    """
    Policy Rule Ports (mutually exclusive with port_ranges)
    """
    protocol: NotRequired[pulumi.Input[_builtins.str]]
    """
    Policy Rule Protocol (tcp|udp|icmp|all|netbird-ssh)
    """
    source_resource: NotRequired[pulumi.Input['PolicyRuleSourceResourceArgsDict']]
    """
    Policy Rule Source Resource (mutually exclusive with sources)
    """
    sources: NotRequired[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]
    """
    Policy Rule Source Groups (mutually exclusive with source_resource)
    """

@pulumi.input_type
class PolicyRuleArgs:
    def __init__(__self__, *,
                 name: pulumi.Input[_builtins.str],
                 action: Optional[pulumi.Input[_builtins.str]] = None,
                 authorized_groups: Optional[pulumi.Input[Mapping[str, pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]]] = None,
                 bidirectional: Optional[pulumi.Input[_builtins.bool]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 destination_resource: Optional[pulumi.Input['PolicyRuleDestinationResourceArgs']] = None,
                 destinations: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 id: Optional[pulumi.Input[_builtins.str]] = None,
                 port_ranges: Optional[pulumi.Input[Sequence[pulumi.Input['PolicyRulePortRangeArgs']]]] = None,
                 ports: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 protocol: Optional[pulumi.Input[_builtins.str]] = None,
                 source_resource: Optional[pulumi.Input['PolicyRuleSourceResourceArgs']] = None,
                 sources: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None):
        """
        :param pulumi.Input[_builtins.str] name: Policy Name
        :param pulumi.Input[_builtins.str] action: Policy Rule Action (accept|drop)
        :param pulumi.Input[Mapping[str, pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]] authorized_groups: Map of source group IDs to a list of local users authorized for SSH access. Keys must be group IDs present in <span pulumi-lang-nodejs="`sources`" pulumi-lang-dotnet="`Sources`" pulumi-lang-go="`sources`" pulumi-lang-python="`sources`" pulumi-lang-yaml="`sources`" pulumi-lang-java="`sources`">`sources`</span>. If not set, all local users are permitted. Only applicable when protocol is `netbird-ssh`.
        :param pulumi.Input[_builtins.bool] bidirectional: Policy Rule Bidirectional
        :param pulumi.Input[_builtins.str] description: Policy description
        :param pulumi.Input['PolicyRuleDestinationResourceArgs'] destination_resource: Policy Rule Destination Resource (mutually exclusive with destinations)
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] destinations: Policy Rule Destination Groups (mutually exclusive with destination_resource)
        :param pulumi.Input[_builtins.bool] enabled: Policy Rule Enabled
        :param pulumi.Input[_builtins.str] id: Policy ID
        :param pulumi.Input[Sequence[pulumi.Input['PolicyRulePortRangeArgs']]] port_ranges: Policy Rule Port Ranges (mutually exclusive with ports)
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] ports: Policy Rule Ports (mutually exclusive with port_ranges)
        :param pulumi.Input[_builtins.str] protocol: Policy Rule Protocol (tcp|udp|icmp|all|netbird-ssh)
        :param pulumi.Input['PolicyRuleSourceResourceArgs'] source_resource: Policy Rule Source Resource (mutually exclusive with sources)
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] sources: Policy Rule Source Groups (mutually exclusive with source_resource)
        """
        pulumi.set(__self__, "name", name)
        if action is not None:
            pulumi.set(__self__, "action", action)
        if authorized_groups is not None:
            pulumi.set(__self__, "authorized_groups", authorized_groups)
        if bidirectional is not None:
            pulumi.set(__self__, "bidirectional", bidirectional)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if destination_resource is not None:
            pulumi.set(__self__, "destination_resource", destination_resource)
        if destinations is not None:
            pulumi.set(__self__, "destinations", destinations)
        if enabled is not None:
            pulumi.set(__self__, "enabled", enabled)
        if id is not None:
            pulumi.set(__self__, "id", id)
        if port_ranges is not None:
            pulumi.set(__self__, "port_ranges", port_ranges)
        if ports is not None:
            pulumi.set(__self__, "ports", ports)
        if protocol is not None:
            pulumi.set(__self__, "protocol", protocol)
        if source_resource is not None:
            pulumi.set(__self__, "source_resource", source_resource)
        if sources is not None:
            pulumi.set(__self__, "sources", sources)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[_builtins.str]:
        """
        Policy Name
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def action(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Policy Rule Action (accept|drop)
        """
        return pulumi.get(self, "action")

    @action.setter
    def action(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "action", value)

    @_builtins.property
    @pulumi.getter(name="authorizedGroups")
    def authorized_groups(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]]]:
        """
        Map of source group IDs to a list of local users authorized for SSH access. Keys must be group IDs present in <span pulumi-lang-nodejs="`sources`" pulumi-lang-dotnet="`Sources`" pulumi-lang-go="`sources`" pulumi-lang-python="`sources`" pulumi-lang-yaml="`sources`" pulumi-lang-java="`sources`">`sources`</span>. If not set, all local users are permitted. Only applicable when protocol is `netbird-ssh`.
        """
        return pulumi.get(self, "authorized_groups")

    @authorized_groups.setter
    def authorized_groups(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]]]):
        pulumi.set(self, "authorized_groups", value)

    @_builtins.property
    @pulumi.getter
    def bidirectional(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Policy Rule Bidirectional
        """
        return pulumi.get(self, "bidirectional")

    @bidirectional.setter
    def bidirectional(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "bidirectional", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Policy description
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="destinationResource")
    def destination_resource(self) -> Optional[pulumi.Input['PolicyRuleDestinationResourceArgs']]:
        """
        Policy Rule Destination Resource (mutually exclusive with destinations)
        """
        return pulumi.get(self, "destination_resource")

    @destination_resource.setter
    def destination_resource(self, value: Optional[pulumi.Input['PolicyRuleDestinationResourceArgs']]):
        pulumi.set(self, "destination_resource", value)

    @_builtins.property
    @pulumi.getter
    def destinations(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Policy Rule Destination Groups (mutually exclusive with destination_resource)
        """
        return pulumi.get(self, "destinations")

    @destinations.setter
    def destinations(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "destinations", value)

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Policy Rule Enabled
        """
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "enabled", value)

    @_builtins.property
    @pulumi.getter
    def id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Policy ID
        """
        return pulumi.get(self, "id")

    @id.setter
    def id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "id", value)

    @_builtins.property
    @pulumi.getter(name="portRanges")
    def port_ranges(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['PolicyRulePortRangeArgs']]]]:
        """
        Policy Rule Port Ranges (mutually exclusive with ports)
        """
        return pulumi.get(self, "port_ranges")

    @port_ranges.setter
    def port_ranges(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['PolicyRulePortRangeArgs']]]]):
        pulumi.set(self, "port_ranges", value)

    @_builtins.property
    @pulumi.getter
    def ports(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Policy Rule Ports (mutually exclusive with port_ranges)
        """
        return pulumi.get(self, "ports")

    @ports.setter
    def ports(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "ports", value)

    @_builtins.property
    @pulumi.getter
    def protocol(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Policy Rule Protocol (tcp|udp|icmp|all|netbird-ssh)
        """
        return pulumi.get(self, "protocol")

    @protocol.setter
    def protocol(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "protocol", value)

    @_builtins.property
    @pulumi.getter(name="sourceResource")
    def source_resource(self) -> Optional[pulumi.Input['PolicyRuleSourceResourceArgs']]:
        """
        Policy Rule Source Resource (mutually exclusive with sources)
        """
        return pulumi.get(self, "source_resource")

    @source_resource.setter
    def source_resource(self, value: Optional[pulumi.Input['PolicyRuleSourceResourceArgs']]):
        pulumi.set(self, "source_resource", value)

    @_builtins.property
    @pulumi.getter
    def sources(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Policy Rule Source Groups (mutually exclusive with source_resource)
        """
        return pulumi.get(self, "sources")

    @sources.setter
    def sources(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "sources", value)


class PolicyRuleDestinationResourceArgsDict(TypedDict):
    id: pulumi.Input[_builtins.str]
    type: pulumi.Input[_builtins.str]

@pulumi.input_type
class PolicyRuleDestinationResourceArgs:
    def __init__(__self__, *,
                 id: pulumi.Input[_builtins.str],
                 type: pulumi.Input[_builtins.str]):
        pulumi.set(__self__, "id", id)
        pulumi.set(__self__, "type", type)

    @_builtins.property
    @pulumi.getter
    def id(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "id")

    @id.setter
    def id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "id", value)

    @_builtins.property
    @pulumi.getter
    def type(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "type", value)


class PolicyRulePortRangeArgsDict(TypedDict):
    end: pulumi.Input[_builtins.float]
    start: pulumi.Input[_builtins.float]

@pulumi.input_type
class PolicyRulePortRangeArgs:
    def __init__(__self__, *,
                 end: pulumi.Input[_builtins.float],
                 start: pulumi.Input[_builtins.float]):
        pulumi.set(__self__, "end", end)
        pulumi.set(__self__, "start", start)

    @_builtins.property
    @pulumi.getter
    def end(self) -> pulumi.Input[_builtins.float]:
        return pulumi.get(self, "end")

    @end.setter
    def end(self, value: pulumi.Input[_builtins.float]):
        pulumi.set(self, "end", value)

    @_builtins.property
    @pulumi.getter
    def start(self) -> pulumi.Input[_builtins.float]:
        return pulumi.get(self, "start")

    @start.setter
    def start(self, value: pulumi.Input[_builtins.float]):
        pulumi.set(self, "start", value)


class PolicyRuleSourceResourceArgsDict(TypedDict):
    id: pulumi.Input[_builtins.str]
    type: pulumi.Input[_builtins.str]

@pulumi.input_type
class PolicyRuleSourceResourceArgs:
    def __init__(__self__, *,
                 id: pulumi.Input[_builtins.str],
                 type: pulumi.Input[_builtins.str]):
        pulumi.set(__self__, "id", id)
        pulumi.set(__self__, "type", type)

    @_builtins.property
    @pulumi.getter
    def id(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "id")

    @id.setter
    def id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "id", value)

    @_builtins.property
    @pulumi.getter
    def type(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "type", value)


class PostureCheckGeoLocationCheckArgsDict(TypedDict):
    action: NotRequired[pulumi.Input[_builtins.str]]
    locations: NotRequired[pulumi.Input[Sequence[pulumi.Input['PostureCheckGeoLocationCheckLocationArgsDict']]]]

@pulumi.input_type
class PostureCheckGeoLocationCheckArgs:
    def __init__(__self__, *,
                 action: Optional[pulumi.Input[_builtins.str]] = None,
                 locations: Optional[pulumi.Input[Sequence[pulumi.Input['PostureCheckGeoLocationCheckLocationArgs']]]] = None):
        if action is not None:
            pulumi.set(__self__, "action", action)
        if locations is not None:
            pulumi.set(__self__, "locations", locations)

    @_builtins.property
    @pulumi.getter
    def action(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "action")

    @action.setter
    def action(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "action", value)

    @_builtins.property
    @pulumi.getter
    def locations(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['PostureCheckGeoLocationCheckLocationArgs']]]]:
        return pulumi.get(self, "locations")

    @locations.setter
    def locations(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['PostureCheckGeoLocationCheckLocationArgs']]]]):
        pulumi.set(self, "locations", value)


class PostureCheckGeoLocationCheckLocationArgsDict(TypedDict):
    country_code: pulumi.Input[_builtins.str]
    city_name: NotRequired[pulumi.Input[_builtins.str]]

@pulumi.input_type
class PostureCheckGeoLocationCheckLocationArgs:
    def __init__(__self__, *,
                 country_code: pulumi.Input[_builtins.str],
                 city_name: Optional[pulumi.Input[_builtins.str]] = None):
        pulumi.set(__self__, "country_code", country_code)
        if city_name is not None:
            pulumi.set(__self__, "city_name", city_name)

    @_builtins.property
    @pulumi.getter(name="countryCode")
    def country_code(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "country_code")

    @country_code.setter
    def country_code(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "country_code", value)

    @_builtins.property
    @pulumi.getter(name="cityName")
    def city_name(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "city_name")

    @city_name.setter
    def city_name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "city_name", value)


class PostureCheckNetbirdVersionCheckArgsDict(TypedDict):
    min_version: NotRequired[pulumi.Input[_builtins.str]]

@pulumi.input_type
class PostureCheckNetbirdVersionCheckArgs:
    def __init__(__self__, *,
                 min_version: Optional[pulumi.Input[_builtins.str]] = None):
        if min_version is not None:
            pulumi.set(__self__, "min_version", min_version)

    @_builtins.property
    @pulumi.getter(name="minVersion")
    def min_version(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "min_version")

    @min_version.setter
    def min_version(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "min_version", value)


class PostureCheckOsVersionCheckArgsDict(TypedDict):
    android_min_version: NotRequired[pulumi.Input[_builtins.str]]
    darwin_min_version: NotRequired[pulumi.Input[_builtins.str]]
    ios_min_version: NotRequired[pulumi.Input[_builtins.str]]
    linux_min_kernel_version: NotRequired[pulumi.Input[_builtins.str]]
    windows_min_kernel_version: NotRequired[pulumi.Input[_builtins.str]]

@pulumi.input_type
class PostureCheckOsVersionCheckArgs:
    def __init__(__self__, *,
                 android_min_version: Optional[pulumi.Input[_builtins.str]] = None,
                 darwin_min_version: Optional[pulumi.Input[_builtins.str]] = None,
                 ios_min_version: Optional[pulumi.Input[_builtins.str]] = None,
                 linux_min_kernel_version: Optional[pulumi.Input[_builtins.str]] = None,
                 windows_min_kernel_version: Optional[pulumi.Input[_builtins.str]] = None):
        if android_min_version is not None:
            pulumi.set(__self__, "android_min_version", android_min_version)
        if darwin_min_version is not None:
            pulumi.set(__self__, "darwin_min_version", darwin_min_version)
        if ios_min_version is not None:
            pulumi.set(__self__, "ios_min_version", ios_min_version)
        if linux_min_kernel_version is not None:
            pulumi.set(__self__, "linux_min_kernel_version", linux_min_kernel_version)
        if windows_min_kernel_version is not None:
            pulumi.set(__self__, "windows_min_kernel_version", windows_min_kernel_version)

    @_builtins.property
    @pulumi.getter(name="androidMinVersion")
    def android_min_version(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "android_min_version")

    @android_min_version.setter
    def android_min_version(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "android_min_version", value)

    @_builtins.property
    @pulumi.getter(name="darwinMinVersion")
    def darwin_min_version(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "darwin_min_version")

    @darwin_min_version.setter
    def darwin_min_version(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "darwin_min_version", value)

    @_builtins.property
    @pulumi.getter(name="iosMinVersion")
    def ios_min_version(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "ios_min_version")

    @ios_min_version.setter
    def ios_min_version(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "ios_min_version", value)

    @_builtins.property
    @pulumi.getter(name="linuxMinKernelVersion")
    def linux_min_kernel_version(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "linux_min_kernel_version")

    @linux_min_kernel_version.setter
    def linux_min_kernel_version(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "linux_min_kernel_version", value)

    @_builtins.property
    @pulumi.getter(name="windowsMinKernelVersion")
    def windows_min_kernel_version(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "windows_min_kernel_version")

    @windows_min_kernel_version.setter
    def windows_min_kernel_version(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "windows_min_kernel_version", value)


class PostureCheckPeerNetworkRangeCheckArgsDict(TypedDict):
    action: NotRequired[pulumi.Input[_builtins.str]]
    ranges: NotRequired[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]

@pulumi.input_type
class PostureCheckPeerNetworkRangeCheckArgs:
    def __init__(__self__, *,
                 action: Optional[pulumi.Input[_builtins.str]] = None,
                 ranges: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None):
        if action is not None:
            pulumi.set(__self__, "action", action)
        if ranges is not None:
            pulumi.set(__self__, "ranges", ranges)

    @_builtins.property
    @pulumi.getter
    def action(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "action")

    @action.setter
    def action(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "action", value)

    @_builtins.property
    @pulumi.getter
    def ranges(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        return pulumi.get(self, "ranges")

    @ranges.setter
    def ranges(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "ranges", value)


class PostureCheckProcessCheckArgsDict(TypedDict):
    linux_path: NotRequired[pulumi.Input[_builtins.str]]
    mac_path: NotRequired[pulumi.Input[_builtins.str]]
    windows_path: NotRequired[pulumi.Input[_builtins.str]]

@pulumi.input_type
class PostureCheckProcessCheckArgs:
    def __init__(__self__, *,
                 linux_path: Optional[pulumi.Input[_builtins.str]] = None,
                 mac_path: Optional[pulumi.Input[_builtins.str]] = None,
                 windows_path: Optional[pulumi.Input[_builtins.str]] = None):
        if linux_path is not None:
            pulumi.set(__self__, "linux_path", linux_path)
        if mac_path is not None:
            pulumi.set(__self__, "mac_path", mac_path)
        if windows_path is not None:
            pulumi.set(__self__, "windows_path", windows_path)

    @_builtins.property
    @pulumi.getter(name="linuxPath")
    def linux_path(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "linux_path")

    @linux_path.setter
    def linux_path(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "linux_path", value)

    @_builtins.property
    @pulumi.getter(name="macPath")
    def mac_path(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "mac_path")

    @mac_path.setter
    def mac_path(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "mac_path", value)

    @_builtins.property
    @pulumi.getter(name="windowsPath")
    def windows_path(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "windows_path")

    @windows_path.setter
    def windows_path(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "windows_path", value)


class ReverseProxyServiceAuthArgsDict(TypedDict):
    bearer_auth: NotRequired[pulumi.Input['ReverseProxyServiceAuthBearerAuthArgsDict']]
    """
    Bearer token authentication
    """
    link_auth: NotRequired[pulumi.Input['ReverseProxyServiceAuthLinkAuthArgsDict']]
    """
    Link authentication
    """
    password_auth: NotRequired[pulumi.Input['ReverseProxyServiceAuthPasswordAuthArgsDict']]
    """
    Password authentication
    """
    pin_auth: NotRequired[pulumi.Input['ReverseProxyServiceAuthPinAuthArgsDict']]
    """
    PIN authentication
    """

@pulumi.input_type
class ReverseProxyServiceAuthArgs:
    def __init__(__self__, *,
                 bearer_auth: Optional[pulumi.Input['ReverseProxyServiceAuthBearerAuthArgs']] = None,
                 link_auth: Optional[pulumi.Input['ReverseProxyServiceAuthLinkAuthArgs']] = None,
                 password_auth: Optional[pulumi.Input['ReverseProxyServiceAuthPasswordAuthArgs']] = None,
                 pin_auth: Optional[pulumi.Input['ReverseProxyServiceAuthPinAuthArgs']] = None):
        """
        :param pulumi.Input['ReverseProxyServiceAuthBearerAuthArgs'] bearer_auth: Bearer token authentication
        :param pulumi.Input['ReverseProxyServiceAuthLinkAuthArgs'] link_auth: Link authentication
        :param pulumi.Input['ReverseProxyServiceAuthPasswordAuthArgs'] password_auth: Password authentication
        :param pulumi.Input['ReverseProxyServiceAuthPinAuthArgs'] pin_auth: PIN authentication
        """
        if bearer_auth is not None:
            pulumi.set(__self__, "bearer_auth", bearer_auth)
        if link_auth is not None:
            pulumi.set(__self__, "link_auth", link_auth)
        if password_auth is not None:
            pulumi.set(__self__, "password_auth", password_auth)
        if pin_auth is not None:
            pulumi.set(__self__, "pin_auth", pin_auth)

    @_builtins.property
    @pulumi.getter(name="bearerAuth")
    def bearer_auth(self) -> Optional[pulumi.Input['ReverseProxyServiceAuthBearerAuthArgs']]:
        """
        Bearer token authentication
        """
        return pulumi.get(self, "bearer_auth")

    @bearer_auth.setter
    def bearer_auth(self, value: Optional[pulumi.Input['ReverseProxyServiceAuthBearerAuthArgs']]):
        pulumi.set(self, "bearer_auth", value)

    @_builtins.property
    @pulumi.getter(name="linkAuth")
    def link_auth(self) -> Optional[pulumi.Input['ReverseProxyServiceAuthLinkAuthArgs']]:
        """
        Link authentication
        """
        return pulumi.get(self, "link_auth")

    @link_auth.setter
    def link_auth(self, value: Optional[pulumi.Input['ReverseProxyServiceAuthLinkAuthArgs']]):
        pulumi.set(self, "link_auth", value)

    @_builtins.property
    @pulumi.getter(name="passwordAuth")
    def password_auth(self) -> Optional[pulumi.Input['ReverseProxyServiceAuthPasswordAuthArgs']]:
        """
        Password authentication
        """
        return pulumi.get(self, "password_auth")

    @password_auth.setter
    def password_auth(self, value: Optional[pulumi.Input['ReverseProxyServiceAuthPasswordAuthArgs']]):
        pulumi.set(self, "password_auth", value)

    @_builtins.property
    @pulumi.getter(name="pinAuth")
    def pin_auth(self) -> Optional[pulumi.Input['ReverseProxyServiceAuthPinAuthArgs']]:
        """
        PIN authentication
        """
        return pulumi.get(self, "pin_auth")

    @pin_auth.setter
    def pin_auth(self, value: Optional[pulumi.Input['ReverseProxyServiceAuthPinAuthArgs']]):
        pulumi.set(self, "pin_auth", value)


class ReverseProxyServiceAuthBearerAuthArgsDict(TypedDict):
    enabled: pulumi.Input[_builtins.bool]
    distribution_groups: NotRequired[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]
    """
    List of group IDs that can use bearer auth
    """

@pulumi.input_type
class ReverseProxyServiceAuthBearerAuthArgs:
    def __init__(__self__, *,
                 enabled: pulumi.Input[_builtins.bool],
                 distribution_groups: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None):
        """
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] distribution_groups: List of group IDs that can use bearer auth
        """
        pulumi.set(__self__, "enabled", enabled)
        if distribution_groups is not None:
            pulumi.set(__self__, "distribution_groups", distribution_groups)

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> pulumi.Input[_builtins.bool]:
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: pulumi.Input[_builtins.bool]):
        pulumi.set(self, "enabled", value)

    @_builtins.property
    @pulumi.getter(name="distributionGroups")
    def distribution_groups(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        List of group IDs that can use bearer auth
        """
        return pulumi.get(self, "distribution_groups")

    @distribution_groups.setter
    def distribution_groups(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "distribution_groups", value)


class ReverseProxyServiceAuthLinkAuthArgsDict(TypedDict):
    enabled: pulumi.Input[_builtins.bool]

@pulumi.input_type
class ReverseProxyServiceAuthLinkAuthArgs:
    def __init__(__self__, *,
                 enabled: pulumi.Input[_builtins.bool]):
        pulumi.set(__self__, "enabled", enabled)

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> pulumi.Input[_builtins.bool]:
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: pulumi.Input[_builtins.bool]):
        pulumi.set(self, "enabled", value)


class ReverseProxyServiceAuthPasswordAuthArgsDict(TypedDict):
    enabled: pulumi.Input[_builtins.bool]
    password: NotRequired[pulumi.Input[_builtins.str]]

@pulumi.input_type
class ReverseProxyServiceAuthPasswordAuthArgs:
    def __init__(__self__, *,
                 enabled: pulumi.Input[_builtins.bool],
                 password: Optional[pulumi.Input[_builtins.str]] = None):
        pulumi.set(__self__, "enabled", enabled)
        if password is not None:
            pulumi.set(__self__, "password", password)

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> pulumi.Input[_builtins.bool]:
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: pulumi.Input[_builtins.bool]):
        pulumi.set(self, "enabled", value)

    @_builtins.property
    @pulumi.getter
    def password(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "password")

    @password.setter
    def password(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "password", value)


class ReverseProxyServiceAuthPinAuthArgsDict(TypedDict):
    enabled: pulumi.Input[_builtins.bool]
    pin: NotRequired[pulumi.Input[_builtins.str]]

@pulumi.input_type
class ReverseProxyServiceAuthPinAuthArgs:
    def __init__(__self__, *,
                 enabled: pulumi.Input[_builtins.bool],
                 pin: Optional[pulumi.Input[_builtins.str]] = None):
        pulumi.set(__self__, "enabled", enabled)
        if pin is not None:
            pulumi.set(__self__, "pin", pin)

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> pulumi.Input[_builtins.bool]:
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: pulumi.Input[_builtins.bool]):
        pulumi.set(self, "enabled", value)

    @_builtins.property
    @pulumi.getter
    def pin(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "pin")

    @pin.setter
    def pin(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "pin", value)


class ReverseProxyServiceTargetArgsDict(TypedDict):
    port: pulumi.Input[_builtins.float]
    """
    Backend port for this target (0 for scheme default)
    """
    protocol: pulumi.Input[_builtins.str]
    """
    Protocol to use when connecting to the backend (http, https)
    """
    target_id: pulumi.Input[_builtins.str]
    """
    Target ID (resource or peer ID)
    """
    target_type: pulumi.Input[_builtins.str]
    """
    Target type (peer, host, domain, subnet)
    """
    enabled: NotRequired[pulumi.Input[_builtins.bool]]
    """
    Whether this target is enabled
    """
    host: NotRequired[pulumi.Input[_builtins.str]]
    """
    Backend IP or domain for this target. If omitted, the API resolves it from the target peer.
    """
    path: NotRequired[pulumi.Input[_builtins.str]]
    """
    URL path prefix for this target. Defaults to "/" if omitted.
    """

@pulumi.input_type
class ReverseProxyServiceTargetArgs:
    def __init__(__self__, *,
                 port: pulumi.Input[_builtins.float],
                 protocol: pulumi.Input[_builtins.str],
                 target_id: pulumi.Input[_builtins.str],
                 target_type: pulumi.Input[_builtins.str],
                 enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 host: Optional[pulumi.Input[_builtins.str]] = None,
                 path: Optional[pulumi.Input[_builtins.str]] = None):
        """
        :param pulumi.Input[_builtins.float] port: Backend port for this target (0 for scheme default)
        :param pulumi.Input[_builtins.str] protocol: Protocol to use when connecting to the backend (http, https)
        :param pulumi.Input[_builtins.str] target_id: Target ID (resource or peer ID)
        :param pulumi.Input[_builtins.str] target_type: Target type (peer, host, domain, subnet)
        :param pulumi.Input[_builtins.bool] enabled: Whether this target is enabled
        :param pulumi.Input[_builtins.str] host: Backend IP or domain for this target. If omitted, the API resolves it from the target peer.
        :param pulumi.Input[_builtins.str] path: URL path prefix for this target. Defaults to "/" if omitted.
        """
        pulumi.set(__self__, "port", port)
        pulumi.set(__self__, "protocol", protocol)
        pulumi.set(__self__, "target_id", target_id)
        pulumi.set(__self__, "target_type", target_type)
        if enabled is not None:
            pulumi.set(__self__, "enabled", enabled)
        if host is not None:
            pulumi.set(__self__, "host", host)
        if path is not None:
            pulumi.set(__self__, "path", path)

    @_builtins.property
    @pulumi.getter
    def port(self) -> pulumi.Input[_builtins.float]:
        """
        Backend port for this target (0 for scheme default)
        """
        return pulumi.get(self, "port")

    @port.setter
    def port(self, value: pulumi.Input[_builtins.float]):
        pulumi.set(self, "port", value)

    @_builtins.property
    @pulumi.getter
    def protocol(self) -> pulumi.Input[_builtins.str]:
        """
        Protocol to use when connecting to the backend (http, https)
        """
        return pulumi.get(self, "protocol")

    @protocol.setter
    def protocol(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "protocol", value)

    @_builtins.property
    @pulumi.getter(name="targetId")
    def target_id(self) -> pulumi.Input[_builtins.str]:
        """
        Target ID (resource or peer ID)
        """
        return pulumi.get(self, "target_id")

    @target_id.setter
    def target_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "target_id", value)

    @_builtins.property
    @pulumi.getter(name="targetType")
    def target_type(self) -> pulumi.Input[_builtins.str]:
        """
        Target type (peer, host, domain, subnet)
        """
        return pulumi.get(self, "target_type")

    @target_type.setter
    def target_type(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "target_type", value)

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Whether this target is enabled
        """
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "enabled", value)

    @_builtins.property
    @pulumi.getter
    def host(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Backend IP or domain for this target. If omitted, the API resolves it from the target peer.
        """
        return pulumi.get(self, "host")

    @host.setter
    def host(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "host", value)

    @_builtins.property
    @pulumi.getter
    def path(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        URL path prefix for this target. Defaults to "/" if omitted.
        """
        return pulumi.get(self, "path")

    @path.setter
    def path(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "path", value)


class GetPolicyRuleArgsDict(TypedDict):
    action: _builtins.str
    """
    Policy Rule Action (accept|drop)
    """
    authorized_groups: Mapping[str, Sequence[_builtins.str]]
    """
    Map of source group IDs to a list of local users authorized for SSH access. Keys must be group IDs present in <span pulumi-lang-nodejs="`sources`" pulumi-lang-dotnet="`Sources`" pulumi-lang-go="`sources`" pulumi-lang-python="`sources`" pulumi-lang-yaml="`sources`" pulumi-lang-java="`sources`">`sources`</span>. If not set, all local users are permitted. Only applicable when protocol is `netbird-ssh`.
    """
    bidirectional: _builtins.bool
    """
    Policy Rule Bidirectional
    """
    description: _builtins.str
    """
    Policy description
    """
    destination_resource: 'GetPolicyRuleDestinationResourceArgsDict'
    """
    Policy Rule Destination Resource (mutually exclusive with destinations)
    """
    destinations: Sequence[_builtins.str]
    """
    Policy Rule Destination Groups (mutually exclusive with destination_resource)
    """
    enabled: _builtins.bool
    """
    Policy Rule Enabled
    """
    id: _builtins.str
    """
    Policy ID
    """
    name: _builtins.str
    """
    Policy Name
    """
    port_ranges: Sequence['GetPolicyRulePortRangeArgsDict']
    """
    Policy Rule Port Ranges (mutually exclusive with ports)
    """
    ports: Sequence[_builtins.str]
    """
    Policy Rule Ports (mutually exclusive with port_ranges)
    """
    protocol: _builtins.str
    """
    Policy Rule Protocol (tcp|udp|icmp|all|netbird-ssh)
    """
    source_resource: 'GetPolicyRuleSourceResourceArgsDict'
    """
    Policy Rule Source Resource (mutually exclusive with sources)
    """
    sources: Sequence[_builtins.str]
    """
    Policy Rule Source Groups (mutually exclusive with source_resource)
    """

@pulumi.input_type
class GetPolicyRuleArgs:
    def __init__(__self__, *,
                 action: _builtins.str,
                 authorized_groups: Mapping[str, Sequence[_builtins.str]],
                 bidirectional: _builtins.bool,
                 description: _builtins.str,
                 destination_resource: 'GetPolicyRuleDestinationResourceArgs',
                 destinations: Sequence[_builtins.str],
                 enabled: _builtins.bool,
                 id: _builtins.str,
                 name: _builtins.str,
                 port_ranges: Sequence['GetPolicyRulePortRangeArgs'],
                 ports: Sequence[_builtins.str],
                 protocol: _builtins.str,
                 source_resource: 'GetPolicyRuleSourceResourceArgs',
                 sources: Sequence[_builtins.str]):
        """
        :param _builtins.str action: Policy Rule Action (accept|drop)
        :param Mapping[str, Sequence[_builtins.str]] authorized_groups: Map of source group IDs to a list of local users authorized for SSH access. Keys must be group IDs present in <span pulumi-lang-nodejs="`sources`" pulumi-lang-dotnet="`Sources`" pulumi-lang-go="`sources`" pulumi-lang-python="`sources`" pulumi-lang-yaml="`sources`" pulumi-lang-java="`sources`">`sources`</span>. If not set, all local users are permitted. Only applicable when protocol is `netbird-ssh`.
        :param _builtins.bool bidirectional: Policy Rule Bidirectional
        :param _builtins.str description: Policy description
        :param 'GetPolicyRuleDestinationResourceArgs' destination_resource: Policy Rule Destination Resource (mutually exclusive with destinations)
        :param Sequence[_builtins.str] destinations: Policy Rule Destination Groups (mutually exclusive with destination_resource)
        :param _builtins.bool enabled: Policy Rule Enabled
        :param _builtins.str id: Policy ID
        :param _builtins.str name: Policy Name
        :param Sequence['GetPolicyRulePortRangeArgs'] port_ranges: Policy Rule Port Ranges (mutually exclusive with ports)
        :param Sequence[_builtins.str] ports: Policy Rule Ports (mutually exclusive with port_ranges)
        :param _builtins.str protocol: Policy Rule Protocol (tcp|udp|icmp|all|netbird-ssh)
        :param 'GetPolicyRuleSourceResourceArgs' source_resource: Policy Rule Source Resource (mutually exclusive with sources)
        :param Sequence[_builtins.str] sources: Policy Rule Source Groups (mutually exclusive with source_resource)
        """
        pulumi.set(__self__, "action", action)
        pulumi.set(__self__, "authorized_groups", authorized_groups)
        pulumi.set(__self__, "bidirectional", bidirectional)
        pulumi.set(__self__, "description", description)
        pulumi.set(__self__, "destination_resource", destination_resource)
        pulumi.set(__self__, "destinations", destinations)
        pulumi.set(__self__, "enabled", enabled)
        pulumi.set(__self__, "id", id)
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "port_ranges", port_ranges)
        pulumi.set(__self__, "ports", ports)
        pulumi.set(__self__, "protocol", protocol)
        pulumi.set(__self__, "source_resource", source_resource)
        pulumi.set(__self__, "sources", sources)

    @_builtins.property
    @pulumi.getter
    def action(self) -> _builtins.str:
        """
        Policy Rule Action (accept|drop)
        """
        return pulumi.get(self, "action")

    @action.setter
    def action(self, value: _builtins.str):
        pulumi.set(self, "action", value)

    @_builtins.property
    @pulumi.getter(name="authorizedGroups")
    def authorized_groups(self) -> Mapping[str, Sequence[_builtins.str]]:
        """
        Map of source group IDs to a list of local users authorized for SSH access. Keys must be group IDs present in <span pulumi-lang-nodejs="`sources`" pulumi-lang-dotnet="`Sources`" pulumi-lang-go="`sources`" pulumi-lang-python="`sources`" pulumi-lang-yaml="`sources`" pulumi-lang-java="`sources`">`sources`</span>. If not set, all local users are permitted. Only applicable when protocol is `netbird-ssh`.
        """
        return pulumi.get(self, "authorized_groups")

    @authorized_groups.setter
    def authorized_groups(self, value: Mapping[str, Sequence[_builtins.str]]):
        pulumi.set(self, "authorized_groups", value)

    @_builtins.property
    @pulumi.getter
    def bidirectional(self) -> _builtins.bool:
        """
        Policy Rule Bidirectional
        """
        return pulumi.get(self, "bidirectional")

    @bidirectional.setter
    def bidirectional(self, value: _builtins.bool):
        pulumi.set(self, "bidirectional", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> _builtins.str:
        """
        Policy description
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: _builtins.str):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="destinationResource")
    def destination_resource(self) -> 'GetPolicyRuleDestinationResourceArgs':
        """
        Policy Rule Destination Resource (mutually exclusive with destinations)
        """
        return pulumi.get(self, "destination_resource")

    @destination_resource.setter
    def destination_resource(self, value: 'GetPolicyRuleDestinationResourceArgs'):
        pulumi.set(self, "destination_resource", value)

    @_builtins.property
    @pulumi.getter
    def destinations(self) -> Sequence[_builtins.str]:
        """
        Policy Rule Destination Groups (mutually exclusive with destination_resource)
        """
        return pulumi.get(self, "destinations")

    @destinations.setter
    def destinations(self, value: Sequence[_builtins.str]):
        pulumi.set(self, "destinations", value)

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> _builtins.bool:
        """
        Policy Rule Enabled
        """
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: _builtins.bool):
        pulumi.set(self, "enabled", value)

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        Policy ID
        """
        return pulumi.get(self, "id")

    @id.setter
    def id(self, value: _builtins.str):
        pulumi.set(self, "id", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        Policy Name
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: _builtins.str):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="portRanges")
    def port_ranges(self) -> Sequence['GetPolicyRulePortRangeArgs']:
        """
        Policy Rule Port Ranges (mutually exclusive with ports)
        """
        return pulumi.get(self, "port_ranges")

    @port_ranges.setter
    def port_ranges(self, value: Sequence['GetPolicyRulePortRangeArgs']):
        pulumi.set(self, "port_ranges", value)

    @_builtins.property
    @pulumi.getter
    def ports(self) -> Sequence[_builtins.str]:
        """
        Policy Rule Ports (mutually exclusive with port_ranges)
        """
        return pulumi.get(self, "ports")

    @ports.setter
    def ports(self, value: Sequence[_builtins.str]):
        pulumi.set(self, "ports", value)

    @_builtins.property
    @pulumi.getter
    def protocol(self) -> _builtins.str:
        """
        Policy Rule Protocol (tcp|udp|icmp|all|netbird-ssh)
        """
        return pulumi.get(self, "protocol")

    @protocol.setter
    def protocol(self, value: _builtins.str):
        pulumi.set(self, "protocol", value)

    @_builtins.property
    @pulumi.getter(name="sourceResource")
    def source_resource(self) -> 'GetPolicyRuleSourceResourceArgs':
        """
        Policy Rule Source Resource (mutually exclusive with sources)
        """
        return pulumi.get(self, "source_resource")

    @source_resource.setter
    def source_resource(self, value: 'GetPolicyRuleSourceResourceArgs'):
        pulumi.set(self, "source_resource", value)

    @_builtins.property
    @pulumi.getter
    def sources(self) -> Sequence[_builtins.str]:
        """
        Policy Rule Source Groups (mutually exclusive with source_resource)
        """
        return pulumi.get(self, "sources")

    @sources.setter
    def sources(self, value: Sequence[_builtins.str]):
        pulumi.set(self, "sources", value)


class GetPolicyRuleDestinationResourceArgsDict(TypedDict):
    id: _builtins.str
    type: _builtins.str

@pulumi.input_type
class GetPolicyRuleDestinationResourceArgs:
    def __init__(__self__, *,
                 id: _builtins.str,
                 type: _builtins.str):
        pulumi.set(__self__, "id", id)
        pulumi.set(__self__, "type", type)

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")

    @id.setter
    def id(self, value: _builtins.str):
        pulumi.set(self, "id", value)

    @_builtins.property
    @pulumi.getter
    def type(self) -> _builtins.str:
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: _builtins.str):
        pulumi.set(self, "type", value)


class GetPolicyRulePortRangeArgsDict(TypedDict):
    end: _builtins.float
    start: _builtins.float

@pulumi.input_type
class GetPolicyRulePortRangeArgs:
    def __init__(__self__, *,
                 end: _builtins.float,
                 start: _builtins.float):
        pulumi.set(__self__, "end", end)
        pulumi.set(__self__, "start", start)

    @_builtins.property
    @pulumi.getter
    def end(self) -> _builtins.float:
        return pulumi.get(self, "end")

    @end.setter
    def end(self, value: _builtins.float):
        pulumi.set(self, "end", value)

    @_builtins.property
    @pulumi.getter
    def start(self) -> _builtins.float:
        return pulumi.get(self, "start")

    @start.setter
    def start(self, value: _builtins.float):
        pulumi.set(self, "start", value)


class GetPolicyRuleSourceResourceArgsDict(TypedDict):
    id: _builtins.str
    type: _builtins.str

@pulumi.input_type
class GetPolicyRuleSourceResourceArgs:
    def __init__(__self__, *,
                 id: _builtins.str,
                 type: _builtins.str):
        pulumi.set(__self__, "id", id)
        pulumi.set(__self__, "type", type)

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")

    @id.setter
    def id(self, value: _builtins.str):
        pulumi.set(self, "id", value)

    @_builtins.property
    @pulumi.getter
    def type(self) -> _builtins.str:
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: _builtins.str):
        pulumi.set(self, "type", value)


