# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetSetupKeyResult',
    'AwaitableGetSetupKeyResult',
    'get_setup_key',
    'get_setup_key_output',
]

@pulumi.output_type
class GetSetupKeyResult:
    """
    A collection of values returned by getSetupKey.
    """
    def __init__(__self__, allow_extra_dns_labels=None, auto_groups=None, ephemeral=None, expires=None, id=None, last_used=None, name=None, revoked=None, state=None, type=None, updated_at=None, usage_limit=None, used_times=None, valid=None):
        if allow_extra_dns_labels and not isinstance(allow_extra_dns_labels, bool):
            raise TypeError("Expected argument 'allow_extra_dns_labels' to be a bool")
        pulumi.set(__self__, "allow_extra_dns_labels", allow_extra_dns_labels)
        if auto_groups and not isinstance(auto_groups, list):
            raise TypeError("Expected argument 'auto_groups' to be a list")
        pulumi.set(__self__, "auto_groups", auto_groups)
        if ephemeral and not isinstance(ephemeral, bool):
            raise TypeError("Expected argument 'ephemeral' to be a bool")
        pulumi.set(__self__, "ephemeral", ephemeral)
        if expires and not isinstance(expires, str):
            raise TypeError("Expected argument 'expires' to be a str")
        pulumi.set(__self__, "expires", expires)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if last_used and not isinstance(last_used, str):
            raise TypeError("Expected argument 'last_used' to be a str")
        pulumi.set(__self__, "last_used", last_used)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if revoked and not isinstance(revoked, bool):
            raise TypeError("Expected argument 'revoked' to be a bool")
        pulumi.set(__self__, "revoked", revoked)
        if state and not isinstance(state, str):
            raise TypeError("Expected argument 'state' to be a str")
        pulumi.set(__self__, "state", state)
        if type and not isinstance(type, str):
            raise TypeError("Expected argument 'type' to be a str")
        pulumi.set(__self__, "type", type)
        if updated_at and not isinstance(updated_at, str):
            raise TypeError("Expected argument 'updated_at' to be a str")
        pulumi.set(__self__, "updated_at", updated_at)
        if usage_limit and not isinstance(usage_limit, float):
            raise TypeError("Expected argument 'usage_limit' to be a float")
        pulumi.set(__self__, "usage_limit", usage_limit)
        if used_times and not isinstance(used_times, float):
            raise TypeError("Expected argument 'used_times' to be a float")
        pulumi.set(__self__, "used_times", used_times)
        if valid and not isinstance(valid, bool):
            raise TypeError("Expected argument 'valid' to be a bool")
        pulumi.set(__self__, "valid", valid)

    @_builtins.property
    @pulumi.getter(name="allowExtraDnsLabels")
    def allow_extra_dns_labels(self) -> _builtins.bool:
        return pulumi.get(self, "allow_extra_dns_labels")

    @_builtins.property
    @pulumi.getter(name="autoGroups")
    def auto_groups(self) -> Sequence[_builtins.str]:
        return pulumi.get(self, "auto_groups")

    @_builtins.property
    @pulumi.getter
    def ephemeral(self) -> _builtins.bool:
        return pulumi.get(self, "ephemeral")

    @_builtins.property
    @pulumi.getter
    def expires(self) -> _builtins.str:
        return pulumi.get(self, "expires")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="lastUsed")
    def last_used(self) -> _builtins.str:
        return pulumi.get(self, "last_used")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def revoked(self) -> _builtins.bool:
        return pulumi.get(self, "revoked")

    @_builtins.property
    @pulumi.getter
    def state(self) -> _builtins.str:
        return pulumi.get(self, "state")

    @_builtins.property
    @pulumi.getter
    def type(self) -> _builtins.str:
        return pulumi.get(self, "type")

    @_builtins.property
    @pulumi.getter(name="updatedAt")
    def updated_at(self) -> _builtins.str:
        return pulumi.get(self, "updated_at")

    @_builtins.property
    @pulumi.getter(name="usageLimit")
    def usage_limit(self) -> _builtins.float:
        return pulumi.get(self, "usage_limit")

    @_builtins.property
    @pulumi.getter(name="usedTimes")
    def used_times(self) -> _builtins.float:
        return pulumi.get(self, "used_times")

    @_builtins.property
    @pulumi.getter
    def valid(self) -> _builtins.bool:
        return pulumi.get(self, "valid")


class AwaitableGetSetupKeyResult(GetSetupKeyResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetSetupKeyResult(
            allow_extra_dns_labels=self.allow_extra_dns_labels,
            auto_groups=self.auto_groups,
            ephemeral=self.ephemeral,
            expires=self.expires,
            id=self.id,
            last_used=self.last_used,
            name=self.name,
            revoked=self.revoked,
            state=self.state,
            type=self.type,
            updated_at=self.updated_at,
            usage_limit=self.usage_limit,
            used_times=self.used_times,
            valid=self.valid)


def get_setup_key(id: Optional[_builtins.str] = None,
                  name: Optional[_builtins.str] = None,
                  opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetSetupKeyResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['id'] = id
    __args__['name'] = name
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('netbird:index/getSetupKey:getSetupKey', __args__, opts=opts, typ=GetSetupKeyResult, package_ref=_utilities.get_package()).value

    return AwaitableGetSetupKeyResult(
        allow_extra_dns_labels=pulumi.get(__ret__, 'allow_extra_dns_labels'),
        auto_groups=pulumi.get(__ret__, 'auto_groups'),
        ephemeral=pulumi.get(__ret__, 'ephemeral'),
        expires=pulumi.get(__ret__, 'expires'),
        id=pulumi.get(__ret__, 'id'),
        last_used=pulumi.get(__ret__, 'last_used'),
        name=pulumi.get(__ret__, 'name'),
        revoked=pulumi.get(__ret__, 'revoked'),
        state=pulumi.get(__ret__, 'state'),
        type=pulumi.get(__ret__, 'type'),
        updated_at=pulumi.get(__ret__, 'updated_at'),
        usage_limit=pulumi.get(__ret__, 'usage_limit'),
        used_times=pulumi.get(__ret__, 'used_times'),
        valid=pulumi.get(__ret__, 'valid'))
def get_setup_key_output(id: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                         name: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                         opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetSetupKeyResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['id'] = id
    __args__['name'] = name
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('netbird:index/getSetupKey:getSetupKey', __args__, opts=opts, typ=GetSetupKeyResult, package_ref=_utilities.get_package())
    return __ret__.apply(lambda __response__: GetSetupKeyResult(
        allow_extra_dns_labels=pulumi.get(__response__, 'allow_extra_dns_labels'),
        auto_groups=pulumi.get(__response__, 'auto_groups'),
        ephemeral=pulumi.get(__response__, 'ephemeral'),
        expires=pulumi.get(__response__, 'expires'),
        id=pulumi.get(__response__, 'id'),
        last_used=pulumi.get(__response__, 'last_used'),
        name=pulumi.get(__response__, 'name'),
        revoked=pulumi.get(__response__, 'revoked'),
        state=pulumi.get(__response__, 'state'),
        type=pulumi.get(__response__, 'type'),
        updated_at=pulumi.get(__response__, 'updated_at'),
        usage_limit=pulumi.get(__response__, 'usage_limit'),
        used_times=pulumi.get(__response__, 'used_times'),
        valid=pulumi.get(__response__, 'valid')))
