# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetDnsSettingsResult',
    'AwaitableGetDnsSettingsResult',
    'get_dns_settings',
    'get_dns_settings_output',
]

@pulumi.output_type
class GetDnsSettingsResult:
    """
    A collection of values returned by getDnsSettings.
    """
    def __init__(__self__, disabled_management_groups=None, id=None):
        if disabled_management_groups and not isinstance(disabled_management_groups, list):
            raise TypeError("Expected argument 'disabled_management_groups' to be a list")
        pulumi.set(__self__, "disabled_management_groups", disabled_management_groups)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)

    @_builtins.property
    @pulumi.getter(name="disabledManagementGroups")
    def disabled_management_groups(self) -> Sequence[_builtins.str]:
        return pulumi.get(self, "disabled_management_groups")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")


class AwaitableGetDnsSettingsResult(GetDnsSettingsResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetDnsSettingsResult(
            disabled_management_groups=self.disabled_management_groups,
            id=self.id)


def get_dns_settings(opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetDnsSettingsResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('netbird:index/getDnsSettings:getDnsSettings', __args__, opts=opts, typ=GetDnsSettingsResult, package_ref=_utilities.get_package()).value

    return AwaitableGetDnsSettingsResult(
        disabled_management_groups=pulumi.get(__ret__, 'disabled_management_groups'),
        id=pulumi.get(__ret__, 'id'))
def get_dns_settings_output(opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetDnsSettingsResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('netbird:index/getDnsSettings:getDnsSettings', __args__, opts=opts, typ=GetDnsSettingsResult, package_ref=_utilities.get_package())
    return __ret__.apply(lambda __response__: GetDnsSettingsResult(
        disabled_management_groups=pulumi.get(__response__, 'disabled_management_groups'),
        id=pulumi.get(__response__, 'id')))
