# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetReverseProxyServiceResult',
    'AwaitableGetReverseProxyServiceResult',
    'get_reverse_proxy_service',
    'get_reverse_proxy_service_output',
]

@pulumi.output_type
class GetReverseProxyServiceResult:
    """
    A collection of values returned by getReverseProxyService.
    """
    def __init__(__self__, auth=None, domain=None, enabled=None, id=None, name=None, pass_host_header=None, proxy_cluster=None, rewrite_redirects=None, targets=None):
        if auth and not isinstance(auth, dict):
            raise TypeError("Expected argument 'auth' to be a dict")
        pulumi.set(__self__, "auth", auth)
        if domain and not isinstance(domain, str):
            raise TypeError("Expected argument 'domain' to be a str")
        pulumi.set(__self__, "domain", domain)
        if enabled and not isinstance(enabled, bool):
            raise TypeError("Expected argument 'enabled' to be a bool")
        pulumi.set(__self__, "enabled", enabled)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if pass_host_header and not isinstance(pass_host_header, bool):
            raise TypeError("Expected argument 'pass_host_header' to be a bool")
        pulumi.set(__self__, "pass_host_header", pass_host_header)
        if proxy_cluster and not isinstance(proxy_cluster, str):
            raise TypeError("Expected argument 'proxy_cluster' to be a str")
        pulumi.set(__self__, "proxy_cluster", proxy_cluster)
        if rewrite_redirects and not isinstance(rewrite_redirects, bool):
            raise TypeError("Expected argument 'rewrite_redirects' to be a bool")
        pulumi.set(__self__, "rewrite_redirects", rewrite_redirects)
        if targets and not isinstance(targets, list):
            raise TypeError("Expected argument 'targets' to be a list")
        pulumi.set(__self__, "targets", targets)

    @_builtins.property
    @pulumi.getter
    def auth(self) -> 'outputs.GetReverseProxyServiceAuthResult':
        return pulumi.get(self, "auth")

    @_builtins.property
    @pulumi.getter
    def domain(self) -> _builtins.str:
        return pulumi.get(self, "domain")

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> _builtins.bool:
        return pulumi.get(self, "enabled")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="passHostHeader")
    def pass_host_header(self) -> _builtins.bool:
        return pulumi.get(self, "pass_host_header")

    @_builtins.property
    @pulumi.getter(name="proxyCluster")
    def proxy_cluster(self) -> _builtins.str:
        return pulumi.get(self, "proxy_cluster")

    @_builtins.property
    @pulumi.getter(name="rewriteRedirects")
    def rewrite_redirects(self) -> _builtins.bool:
        return pulumi.get(self, "rewrite_redirects")

    @_builtins.property
    @pulumi.getter
    def targets(self) -> Sequence['outputs.GetReverseProxyServiceTargetResult']:
        return pulumi.get(self, "targets")


class AwaitableGetReverseProxyServiceResult(GetReverseProxyServiceResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetReverseProxyServiceResult(
            auth=self.auth,
            domain=self.domain,
            enabled=self.enabled,
            id=self.id,
            name=self.name,
            pass_host_header=self.pass_host_header,
            proxy_cluster=self.proxy_cluster,
            rewrite_redirects=self.rewrite_redirects,
            targets=self.targets)


def get_reverse_proxy_service(domain: Optional[_builtins.str] = None,
                              id: Optional[_builtins.str] = None,
                              name: Optional[_builtins.str] = None,
                              opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetReverseProxyServiceResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['domain'] = domain
    __args__['id'] = id
    __args__['name'] = name
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('netbird:index/getReverseProxyService:getReverseProxyService', __args__, opts=opts, typ=GetReverseProxyServiceResult, package_ref=_utilities.get_package()).value

    return AwaitableGetReverseProxyServiceResult(
        auth=pulumi.get(__ret__, 'auth'),
        domain=pulumi.get(__ret__, 'domain'),
        enabled=pulumi.get(__ret__, 'enabled'),
        id=pulumi.get(__ret__, 'id'),
        name=pulumi.get(__ret__, 'name'),
        pass_host_header=pulumi.get(__ret__, 'pass_host_header'),
        proxy_cluster=pulumi.get(__ret__, 'proxy_cluster'),
        rewrite_redirects=pulumi.get(__ret__, 'rewrite_redirects'),
        targets=pulumi.get(__ret__, 'targets'))
def get_reverse_proxy_service_output(domain: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                     id: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                     name: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                     opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetReverseProxyServiceResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['domain'] = domain
    __args__['id'] = id
    __args__['name'] = name
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('netbird:index/getReverseProxyService:getReverseProxyService', __args__, opts=opts, typ=GetReverseProxyServiceResult, package_ref=_utilities.get_package())
    return __ret__.apply(lambda __response__: GetReverseProxyServiceResult(
        auth=pulumi.get(__response__, 'auth'),
        domain=pulumi.get(__response__, 'domain'),
        enabled=pulumi.get(__response__, 'enabled'),
        id=pulumi.get(__response__, 'id'),
        name=pulumi.get(__response__, 'name'),
        pass_host_header=pulumi.get(__response__, 'pass_host_header'),
        proxy_cluster=pulumi.get(__response__, 'proxy_cluster'),
        rewrite_redirects=pulumi.get(__response__, 'rewrite_redirects'),
        targets=pulumi.get(__response__, 'targets')))
