# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetPeersResult',
    'AwaitableGetPeersResult',
    'get_peers',
    'get_peers_output',
]

@pulumi.output_type
class GetPeersResult:
    """
    A collection of values returned by getPeers.
    """
    def __init__(__self__, approval_required=None, city_name=None, connected=None, connection_ip=None, country_code=None, dns_label=None, extra_dns_labels=None, geoname_id=None, groups=None, hostname=None, id=None, ids=None, inactivity_expiration_enabled=None, ip=None, kernel_version=None, last_login=None, last_seen=None, login_expiration_enabled=None, login_expired=None, name=None, os=None, serial_number=None, ssh_enabled=None, ui_version=None, user_id=None, version=None):
        if approval_required and not isinstance(approval_required, bool):
            raise TypeError("Expected argument 'approval_required' to be a bool")
        pulumi.set(__self__, "approval_required", approval_required)
        if city_name and not isinstance(city_name, str):
            raise TypeError("Expected argument 'city_name' to be a str")
        pulumi.set(__self__, "city_name", city_name)
        if connected and not isinstance(connected, bool):
            raise TypeError("Expected argument 'connected' to be a bool")
        pulumi.set(__self__, "connected", connected)
        if connection_ip and not isinstance(connection_ip, str):
            raise TypeError("Expected argument 'connection_ip' to be a str")
        pulumi.set(__self__, "connection_ip", connection_ip)
        if country_code and not isinstance(country_code, str):
            raise TypeError("Expected argument 'country_code' to be a str")
        pulumi.set(__self__, "country_code", country_code)
        if dns_label and not isinstance(dns_label, str):
            raise TypeError("Expected argument 'dns_label' to be a str")
        pulumi.set(__self__, "dns_label", dns_label)
        if extra_dns_labels and not isinstance(extra_dns_labels, list):
            raise TypeError("Expected argument 'extra_dns_labels' to be a list")
        pulumi.set(__self__, "extra_dns_labels", extra_dns_labels)
        if geoname_id and not isinstance(geoname_id, float):
            raise TypeError("Expected argument 'geoname_id' to be a float")
        pulumi.set(__self__, "geoname_id", geoname_id)
        if groups and not isinstance(groups, list):
            raise TypeError("Expected argument 'groups' to be a list")
        pulumi.set(__self__, "groups", groups)
        if hostname and not isinstance(hostname, str):
            raise TypeError("Expected argument 'hostname' to be a str")
        pulumi.set(__self__, "hostname", hostname)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if ids and not isinstance(ids, list):
            raise TypeError("Expected argument 'ids' to be a list")
        pulumi.set(__self__, "ids", ids)
        if inactivity_expiration_enabled and not isinstance(inactivity_expiration_enabled, bool):
            raise TypeError("Expected argument 'inactivity_expiration_enabled' to be a bool")
        pulumi.set(__self__, "inactivity_expiration_enabled", inactivity_expiration_enabled)
        if ip and not isinstance(ip, str):
            raise TypeError("Expected argument 'ip' to be a str")
        pulumi.set(__self__, "ip", ip)
        if kernel_version and not isinstance(kernel_version, str):
            raise TypeError("Expected argument 'kernel_version' to be a str")
        pulumi.set(__self__, "kernel_version", kernel_version)
        if last_login and not isinstance(last_login, str):
            raise TypeError("Expected argument 'last_login' to be a str")
        pulumi.set(__self__, "last_login", last_login)
        if last_seen and not isinstance(last_seen, str):
            raise TypeError("Expected argument 'last_seen' to be a str")
        pulumi.set(__self__, "last_seen", last_seen)
        if login_expiration_enabled and not isinstance(login_expiration_enabled, bool):
            raise TypeError("Expected argument 'login_expiration_enabled' to be a bool")
        pulumi.set(__self__, "login_expiration_enabled", login_expiration_enabled)
        if login_expired and not isinstance(login_expired, bool):
            raise TypeError("Expected argument 'login_expired' to be a bool")
        pulumi.set(__self__, "login_expired", login_expired)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if os and not isinstance(os, str):
            raise TypeError("Expected argument 'os' to be a str")
        pulumi.set(__self__, "os", os)
        if serial_number and not isinstance(serial_number, str):
            raise TypeError("Expected argument 'serial_number' to be a str")
        pulumi.set(__self__, "serial_number", serial_number)
        if ssh_enabled and not isinstance(ssh_enabled, bool):
            raise TypeError("Expected argument 'ssh_enabled' to be a bool")
        pulumi.set(__self__, "ssh_enabled", ssh_enabled)
        if ui_version and not isinstance(ui_version, str):
            raise TypeError("Expected argument 'ui_version' to be a str")
        pulumi.set(__self__, "ui_version", ui_version)
        if user_id and not isinstance(user_id, str):
            raise TypeError("Expected argument 'user_id' to be a str")
        pulumi.set(__self__, "user_id", user_id)
        if version and not isinstance(version, str):
            raise TypeError("Expected argument 'version' to be a str")
        pulumi.set(__self__, "version", version)

    @_builtins.property
    @pulumi.getter(name="approvalRequired")
    def approval_required(self) -> _builtins.bool:
        return pulumi.get(self, "approval_required")

    @_builtins.property
    @pulumi.getter(name="cityName")
    def city_name(self) -> _builtins.str:
        return pulumi.get(self, "city_name")

    @_builtins.property
    @pulumi.getter
    def connected(self) -> _builtins.bool:
        return pulumi.get(self, "connected")

    @_builtins.property
    @pulumi.getter(name="connectionIp")
    def connection_ip(self) -> _builtins.str:
        return pulumi.get(self, "connection_ip")

    @_builtins.property
    @pulumi.getter(name="countryCode")
    def country_code(self) -> _builtins.str:
        return pulumi.get(self, "country_code")

    @_builtins.property
    @pulumi.getter(name="dnsLabel")
    def dns_label(self) -> _builtins.str:
        return pulumi.get(self, "dns_label")

    @_builtins.property
    @pulumi.getter(name="extraDnsLabels")
    def extra_dns_labels(self) -> Sequence[_builtins.str]:
        return pulumi.get(self, "extra_dns_labels")

    @_builtins.property
    @pulumi.getter(name="geonameId")
    def geoname_id(self) -> _builtins.float:
        return pulumi.get(self, "geoname_id")

    @_builtins.property
    @pulumi.getter
    def groups(self) -> Sequence[_builtins.str]:
        return pulumi.get(self, "groups")

    @_builtins.property
    @pulumi.getter
    def hostname(self) -> _builtins.str:
        return pulumi.get(self, "hostname")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def ids(self) -> Sequence[_builtins.str]:
        return pulumi.get(self, "ids")

    @_builtins.property
    @pulumi.getter(name="inactivityExpirationEnabled")
    def inactivity_expiration_enabled(self) -> _builtins.bool:
        return pulumi.get(self, "inactivity_expiration_enabled")

    @_builtins.property
    @pulumi.getter
    def ip(self) -> _builtins.str:
        return pulumi.get(self, "ip")

    @_builtins.property
    @pulumi.getter(name="kernelVersion")
    def kernel_version(self) -> _builtins.str:
        return pulumi.get(self, "kernel_version")

    @_builtins.property
    @pulumi.getter(name="lastLogin")
    def last_login(self) -> _builtins.str:
        return pulumi.get(self, "last_login")

    @_builtins.property
    @pulumi.getter(name="lastSeen")
    def last_seen(self) -> _builtins.str:
        return pulumi.get(self, "last_seen")

    @_builtins.property
    @pulumi.getter(name="loginExpirationEnabled")
    def login_expiration_enabled(self) -> _builtins.bool:
        return pulumi.get(self, "login_expiration_enabled")

    @_builtins.property
    @pulumi.getter(name="loginExpired")
    def login_expired(self) -> _builtins.bool:
        return pulumi.get(self, "login_expired")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def os(self) -> _builtins.str:
        return pulumi.get(self, "os")

    @_builtins.property
    @pulumi.getter(name="serialNumber")
    def serial_number(self) -> _builtins.str:
        return pulumi.get(self, "serial_number")

    @_builtins.property
    @pulumi.getter(name="sshEnabled")
    def ssh_enabled(self) -> _builtins.bool:
        return pulumi.get(self, "ssh_enabled")

    @_builtins.property
    @pulumi.getter(name="uiVersion")
    def ui_version(self) -> _builtins.str:
        return pulumi.get(self, "ui_version")

    @_builtins.property
    @pulumi.getter(name="userId")
    def user_id(self) -> _builtins.str:
        return pulumi.get(self, "user_id")

    @_builtins.property
    @pulumi.getter
    def version(self) -> _builtins.str:
        return pulumi.get(self, "version")


class AwaitableGetPeersResult(GetPeersResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetPeersResult(
            approval_required=self.approval_required,
            city_name=self.city_name,
            connected=self.connected,
            connection_ip=self.connection_ip,
            country_code=self.country_code,
            dns_label=self.dns_label,
            extra_dns_labels=self.extra_dns_labels,
            geoname_id=self.geoname_id,
            groups=self.groups,
            hostname=self.hostname,
            id=self.id,
            ids=self.ids,
            inactivity_expiration_enabled=self.inactivity_expiration_enabled,
            ip=self.ip,
            kernel_version=self.kernel_version,
            last_login=self.last_login,
            last_seen=self.last_seen,
            login_expiration_enabled=self.login_expiration_enabled,
            login_expired=self.login_expired,
            name=self.name,
            os=self.os,
            serial_number=self.serial_number,
            ssh_enabled=self.ssh_enabled,
            ui_version=self.ui_version,
            user_id=self.user_id,
            version=self.version)


def get_peers(approval_required: Optional[_builtins.bool] = None,
              city_name: Optional[_builtins.str] = None,
              connected: Optional[_builtins.bool] = None,
              connection_ip: Optional[_builtins.str] = None,
              country_code: Optional[_builtins.str] = None,
              dns_label: Optional[_builtins.str] = None,
              extra_dns_labels: Optional[Sequence[_builtins.str]] = None,
              geoname_id: Optional[_builtins.float] = None,
              groups: Optional[Sequence[_builtins.str]] = None,
              hostname: Optional[_builtins.str] = None,
              inactivity_expiration_enabled: Optional[_builtins.bool] = None,
              ip: Optional[_builtins.str] = None,
              login_expiration_enabled: Optional[_builtins.bool] = None,
              login_expired: Optional[_builtins.bool] = None,
              name: Optional[_builtins.str] = None,
              os: Optional[_builtins.str] = None,
              ssh_enabled: Optional[_builtins.bool] = None,
              user_id: Optional[_builtins.str] = None,
              opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetPeersResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['approvalRequired'] = approval_required
    __args__['cityName'] = city_name
    __args__['connected'] = connected
    __args__['connectionIp'] = connection_ip
    __args__['countryCode'] = country_code
    __args__['dnsLabel'] = dns_label
    __args__['extraDnsLabels'] = extra_dns_labels
    __args__['geonameId'] = geoname_id
    __args__['groups'] = groups
    __args__['hostname'] = hostname
    __args__['inactivityExpirationEnabled'] = inactivity_expiration_enabled
    __args__['ip'] = ip
    __args__['loginExpirationEnabled'] = login_expiration_enabled
    __args__['loginExpired'] = login_expired
    __args__['name'] = name
    __args__['os'] = os
    __args__['sshEnabled'] = ssh_enabled
    __args__['userId'] = user_id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('netbird:index/getPeers:getPeers', __args__, opts=opts, typ=GetPeersResult, package_ref=_utilities.get_package()).value

    return AwaitableGetPeersResult(
        approval_required=pulumi.get(__ret__, 'approval_required'),
        city_name=pulumi.get(__ret__, 'city_name'),
        connected=pulumi.get(__ret__, 'connected'),
        connection_ip=pulumi.get(__ret__, 'connection_ip'),
        country_code=pulumi.get(__ret__, 'country_code'),
        dns_label=pulumi.get(__ret__, 'dns_label'),
        extra_dns_labels=pulumi.get(__ret__, 'extra_dns_labels'),
        geoname_id=pulumi.get(__ret__, 'geoname_id'),
        groups=pulumi.get(__ret__, 'groups'),
        hostname=pulumi.get(__ret__, 'hostname'),
        id=pulumi.get(__ret__, 'id'),
        ids=pulumi.get(__ret__, 'ids'),
        inactivity_expiration_enabled=pulumi.get(__ret__, 'inactivity_expiration_enabled'),
        ip=pulumi.get(__ret__, 'ip'),
        kernel_version=pulumi.get(__ret__, 'kernel_version'),
        last_login=pulumi.get(__ret__, 'last_login'),
        last_seen=pulumi.get(__ret__, 'last_seen'),
        login_expiration_enabled=pulumi.get(__ret__, 'login_expiration_enabled'),
        login_expired=pulumi.get(__ret__, 'login_expired'),
        name=pulumi.get(__ret__, 'name'),
        os=pulumi.get(__ret__, 'os'),
        serial_number=pulumi.get(__ret__, 'serial_number'),
        ssh_enabled=pulumi.get(__ret__, 'ssh_enabled'),
        ui_version=pulumi.get(__ret__, 'ui_version'),
        user_id=pulumi.get(__ret__, 'user_id'),
        version=pulumi.get(__ret__, 'version'))
def get_peers_output(approval_required: Optional[pulumi.Input[Optional[_builtins.bool]]] = None,
                     city_name: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                     connected: Optional[pulumi.Input[Optional[_builtins.bool]]] = None,
                     connection_ip: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                     country_code: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                     dns_label: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                     extra_dns_labels: Optional[pulumi.Input[Optional[Sequence[_builtins.str]]]] = None,
                     geoname_id: Optional[pulumi.Input[Optional[_builtins.float]]] = None,
                     groups: Optional[pulumi.Input[Optional[Sequence[_builtins.str]]]] = None,
                     hostname: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                     inactivity_expiration_enabled: Optional[pulumi.Input[Optional[_builtins.bool]]] = None,
                     ip: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                     login_expiration_enabled: Optional[pulumi.Input[Optional[_builtins.bool]]] = None,
                     login_expired: Optional[pulumi.Input[Optional[_builtins.bool]]] = None,
                     name: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                     os: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                     ssh_enabled: Optional[pulumi.Input[Optional[_builtins.bool]]] = None,
                     user_id: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                     opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetPeersResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['approvalRequired'] = approval_required
    __args__['cityName'] = city_name
    __args__['connected'] = connected
    __args__['connectionIp'] = connection_ip
    __args__['countryCode'] = country_code
    __args__['dnsLabel'] = dns_label
    __args__['extraDnsLabels'] = extra_dns_labels
    __args__['geonameId'] = geoname_id
    __args__['groups'] = groups
    __args__['hostname'] = hostname
    __args__['inactivityExpirationEnabled'] = inactivity_expiration_enabled
    __args__['ip'] = ip
    __args__['loginExpirationEnabled'] = login_expiration_enabled
    __args__['loginExpired'] = login_expired
    __args__['name'] = name
    __args__['os'] = os
    __args__['sshEnabled'] = ssh_enabled
    __args__['userId'] = user_id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('netbird:index/getPeers:getPeers', __args__, opts=opts, typ=GetPeersResult, package_ref=_utilities.get_package())
    return __ret__.apply(lambda __response__: GetPeersResult(
        approval_required=pulumi.get(__response__, 'approval_required'),
        city_name=pulumi.get(__response__, 'city_name'),
        connected=pulumi.get(__response__, 'connected'),
        connection_ip=pulumi.get(__response__, 'connection_ip'),
        country_code=pulumi.get(__response__, 'country_code'),
        dns_label=pulumi.get(__response__, 'dns_label'),
        extra_dns_labels=pulumi.get(__response__, 'extra_dns_labels'),
        geoname_id=pulumi.get(__response__, 'geoname_id'),
        groups=pulumi.get(__response__, 'groups'),
        hostname=pulumi.get(__response__, 'hostname'),
        id=pulumi.get(__response__, 'id'),
        ids=pulumi.get(__response__, 'ids'),
        inactivity_expiration_enabled=pulumi.get(__response__, 'inactivity_expiration_enabled'),
        ip=pulumi.get(__response__, 'ip'),
        kernel_version=pulumi.get(__response__, 'kernel_version'),
        last_login=pulumi.get(__response__, 'last_login'),
        last_seen=pulumi.get(__response__, 'last_seen'),
        login_expiration_enabled=pulumi.get(__response__, 'login_expiration_enabled'),
        login_expired=pulumi.get(__response__, 'login_expired'),
        name=pulumi.get(__response__, 'name'),
        os=pulumi.get(__response__, 'os'),
        serial_number=pulumi.get(__response__, 'serial_number'),
        ssh_enabled=pulumi.get(__response__, 'ssh_enabled'),
        ui_version=pulumi.get(__response__, 'ui_version'),
        user_id=pulumi.get(__response__, 'user_id'),
        version=pulumi.get(__response__, 'version')))
