# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetDnsZoneResult',
    'AwaitableGetDnsZoneResult',
    'get_dns_zone',
    'get_dns_zone_output',
]

@pulumi.output_type
class GetDnsZoneResult:
    """
    A collection of values returned by getDnsZone.
    """
    def __init__(__self__, distribution_groups=None, domain=None, enable_search_domain=None, enabled=None, id=None, name=None):
        if distribution_groups and not isinstance(distribution_groups, list):
            raise TypeError("Expected argument 'distribution_groups' to be a list")
        pulumi.set(__self__, "distribution_groups", distribution_groups)
        if domain and not isinstance(domain, str):
            raise TypeError("Expected argument 'domain' to be a str")
        pulumi.set(__self__, "domain", domain)
        if enable_search_domain and not isinstance(enable_search_domain, bool):
            raise TypeError("Expected argument 'enable_search_domain' to be a bool")
        pulumi.set(__self__, "enable_search_domain", enable_search_domain)
        if enabled and not isinstance(enabled, bool):
            raise TypeError("Expected argument 'enabled' to be a bool")
        pulumi.set(__self__, "enabled", enabled)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)

    @_builtins.property
    @pulumi.getter(name="distributionGroups")
    def distribution_groups(self) -> Sequence[_builtins.str]:
        return pulumi.get(self, "distribution_groups")

    @_builtins.property
    @pulumi.getter
    def domain(self) -> _builtins.str:
        return pulumi.get(self, "domain")

    @_builtins.property
    @pulumi.getter(name="enableSearchDomain")
    def enable_search_domain(self) -> _builtins.bool:
        return pulumi.get(self, "enable_search_domain")

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> _builtins.bool:
        return pulumi.get(self, "enabled")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        return pulumi.get(self, "name")


class AwaitableGetDnsZoneResult(GetDnsZoneResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetDnsZoneResult(
            distribution_groups=self.distribution_groups,
            domain=self.domain,
            enable_search_domain=self.enable_search_domain,
            enabled=self.enabled,
            id=self.id,
            name=self.name)


def get_dns_zone(domain: Optional[_builtins.str] = None,
                 id: Optional[_builtins.str] = None,
                 name: Optional[_builtins.str] = None,
                 opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetDnsZoneResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['domain'] = domain
    __args__['id'] = id
    __args__['name'] = name
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('netbird:index/getDnsZone:getDnsZone', __args__, opts=opts, typ=GetDnsZoneResult, package_ref=_utilities.get_package()).value

    return AwaitableGetDnsZoneResult(
        distribution_groups=pulumi.get(__ret__, 'distribution_groups'),
        domain=pulumi.get(__ret__, 'domain'),
        enable_search_domain=pulumi.get(__ret__, 'enable_search_domain'),
        enabled=pulumi.get(__ret__, 'enabled'),
        id=pulumi.get(__ret__, 'id'),
        name=pulumi.get(__ret__, 'name'))
def get_dns_zone_output(domain: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                        id: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                        name: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                        opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetDnsZoneResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['domain'] = domain
    __args__['id'] = id
    __args__['name'] = name
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('netbird:index/getDnsZone:getDnsZone', __args__, opts=opts, typ=GetDnsZoneResult, package_ref=_utilities.get_package())
    return __ret__.apply(lambda __response__: GetDnsZoneResult(
        distribution_groups=pulumi.get(__response__, 'distribution_groups'),
        domain=pulumi.get(__response__, 'domain'),
        enable_search_domain=pulumi.get(__response__, 'enable_search_domain'),
        enabled=pulumi.get(__response__, 'enabled'),
        id=pulumi.get(__response__, 'id'),
        name=pulumi.get(__response__, 'name')))
