# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetPostureCheckResult',
    'AwaitableGetPostureCheckResult',
    'get_posture_check',
    'get_posture_check_output',
]

@pulumi.output_type
class GetPostureCheckResult:
    """
    A collection of values returned by getPostureCheck.
    """
    def __init__(__self__, description=None, geo_location_check=None, id=None, name=None, netbird_version_check=None, os_version_check=None, peer_network_range_check=None, process_checks=None):
        if description and not isinstance(description, str):
            raise TypeError("Expected argument 'description' to be a str")
        pulumi.set(__self__, "description", description)
        if geo_location_check and not isinstance(geo_location_check, dict):
            raise TypeError("Expected argument 'geo_location_check' to be a dict")
        pulumi.set(__self__, "geo_location_check", geo_location_check)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if netbird_version_check and not isinstance(netbird_version_check, dict):
            raise TypeError("Expected argument 'netbird_version_check' to be a dict")
        pulumi.set(__self__, "netbird_version_check", netbird_version_check)
        if os_version_check and not isinstance(os_version_check, dict):
            raise TypeError("Expected argument 'os_version_check' to be a dict")
        pulumi.set(__self__, "os_version_check", os_version_check)
        if peer_network_range_check and not isinstance(peer_network_range_check, dict):
            raise TypeError("Expected argument 'peer_network_range_check' to be a dict")
        pulumi.set(__self__, "peer_network_range_check", peer_network_range_check)
        if process_checks and not isinstance(process_checks, list):
            raise TypeError("Expected argument 'process_checks' to be a list")
        pulumi.set(__self__, "process_checks", process_checks)

    @_builtins.property
    @pulumi.getter
    def description(self) -> _builtins.str:
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter(name="geoLocationCheck")
    def geo_location_check(self) -> 'outputs.GetPostureCheckGeoLocationCheckResult':
        return pulumi.get(self, "geo_location_check")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="netbirdVersionCheck")
    def netbird_version_check(self) -> 'outputs.GetPostureCheckNetbirdVersionCheckResult':
        return pulumi.get(self, "netbird_version_check")

    @_builtins.property
    @pulumi.getter(name="osVersionCheck")
    def os_version_check(self) -> 'outputs.GetPostureCheckOsVersionCheckResult':
        return pulumi.get(self, "os_version_check")

    @_builtins.property
    @pulumi.getter(name="peerNetworkRangeCheck")
    def peer_network_range_check(self) -> 'outputs.GetPostureCheckPeerNetworkRangeCheckResult':
        return pulumi.get(self, "peer_network_range_check")

    @_builtins.property
    @pulumi.getter(name="processChecks")
    def process_checks(self) -> Sequence['outputs.GetPostureCheckProcessCheckResult']:
        return pulumi.get(self, "process_checks")


class AwaitableGetPostureCheckResult(GetPostureCheckResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetPostureCheckResult(
            description=self.description,
            geo_location_check=self.geo_location_check,
            id=self.id,
            name=self.name,
            netbird_version_check=self.netbird_version_check,
            os_version_check=self.os_version_check,
            peer_network_range_check=self.peer_network_range_check,
            process_checks=self.process_checks)


def get_posture_check(id: Optional[_builtins.str] = None,
                      name: Optional[_builtins.str] = None,
                      opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetPostureCheckResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['id'] = id
    __args__['name'] = name
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('netbird:index/getPostureCheck:getPostureCheck', __args__, opts=opts, typ=GetPostureCheckResult, package_ref=_utilities.get_package()).value

    return AwaitableGetPostureCheckResult(
        description=pulumi.get(__ret__, 'description'),
        geo_location_check=pulumi.get(__ret__, 'geo_location_check'),
        id=pulumi.get(__ret__, 'id'),
        name=pulumi.get(__ret__, 'name'),
        netbird_version_check=pulumi.get(__ret__, 'netbird_version_check'),
        os_version_check=pulumi.get(__ret__, 'os_version_check'),
        peer_network_range_check=pulumi.get(__ret__, 'peer_network_range_check'),
        process_checks=pulumi.get(__ret__, 'process_checks'))
def get_posture_check_output(id: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                             name: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                             opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetPostureCheckResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['id'] = id
    __args__['name'] = name
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('netbird:index/getPostureCheck:getPostureCheck', __args__, opts=opts, typ=GetPostureCheckResult, package_ref=_utilities.get_package())
    return __ret__.apply(lambda __response__: GetPostureCheckResult(
        description=pulumi.get(__response__, 'description'),
        geo_location_check=pulumi.get(__response__, 'geo_location_check'),
        id=pulumi.get(__response__, 'id'),
        name=pulumi.get(__response__, 'name'),
        netbird_version_check=pulumi.get(__response__, 'netbird_version_check'),
        os_version_check=pulumi.get(__response__, 'os_version_check'),
        peer_network_range_check=pulumi.get(__response__, 'peer_network_range_check'),
        process_checks=pulumi.get(__response__, 'process_checks')))
