# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetNameserverGroupResult',
    'AwaitableGetNameserverGroupResult',
    'get_nameserver_group',
    'get_nameserver_group_output',
]

@pulumi.output_type
class GetNameserverGroupResult:
    """
    A collection of values returned by getNameserverGroup.
    """
    def __init__(__self__, description=None, domains=None, enabled=None, groups=None, id=None, name=None, nameservers=None, primary=None, search_domains_enabled=None):
        if description and not isinstance(description, str):
            raise TypeError("Expected argument 'description' to be a str")
        pulumi.set(__self__, "description", description)
        if domains and not isinstance(domains, list):
            raise TypeError("Expected argument 'domains' to be a list")
        pulumi.set(__self__, "domains", domains)
        if enabled and not isinstance(enabled, bool):
            raise TypeError("Expected argument 'enabled' to be a bool")
        pulumi.set(__self__, "enabled", enabled)
        if groups and not isinstance(groups, list):
            raise TypeError("Expected argument 'groups' to be a list")
        pulumi.set(__self__, "groups", groups)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if nameservers and not isinstance(nameservers, list):
            raise TypeError("Expected argument 'nameservers' to be a list")
        pulumi.set(__self__, "nameservers", nameservers)
        if primary and not isinstance(primary, bool):
            raise TypeError("Expected argument 'primary' to be a bool")
        pulumi.set(__self__, "primary", primary)
        if search_domains_enabled and not isinstance(search_domains_enabled, bool):
            raise TypeError("Expected argument 'search_domains_enabled' to be a bool")
        pulumi.set(__self__, "search_domains_enabled", search_domains_enabled)

    @_builtins.property
    @pulumi.getter
    def description(self) -> _builtins.str:
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter
    def domains(self) -> Sequence[_builtins.str]:
        return pulumi.get(self, "domains")

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> _builtins.bool:
        return pulumi.get(self, "enabled")

    @_builtins.property
    @pulumi.getter
    def groups(self) -> Sequence[_builtins.str]:
        return pulumi.get(self, "groups")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def nameservers(self) -> Sequence['outputs.GetNameserverGroupNameserverResult']:
        return pulumi.get(self, "nameservers")

    @_builtins.property
    @pulumi.getter
    def primary(self) -> _builtins.bool:
        return pulumi.get(self, "primary")

    @_builtins.property
    @pulumi.getter(name="searchDomainsEnabled")
    def search_domains_enabled(self) -> _builtins.bool:
        return pulumi.get(self, "search_domains_enabled")


class AwaitableGetNameserverGroupResult(GetNameserverGroupResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetNameserverGroupResult(
            description=self.description,
            domains=self.domains,
            enabled=self.enabled,
            groups=self.groups,
            id=self.id,
            name=self.name,
            nameservers=self.nameservers,
            primary=self.primary,
            search_domains_enabled=self.search_domains_enabled)


def get_nameserver_group(id: Optional[_builtins.str] = None,
                         name: Optional[_builtins.str] = None,
                         opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetNameserverGroupResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['id'] = id
    __args__['name'] = name
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('netbird:index/getNameserverGroup:getNameserverGroup', __args__, opts=opts, typ=GetNameserverGroupResult, package_ref=_utilities.get_package()).value

    return AwaitableGetNameserverGroupResult(
        description=pulumi.get(__ret__, 'description'),
        domains=pulumi.get(__ret__, 'domains'),
        enabled=pulumi.get(__ret__, 'enabled'),
        groups=pulumi.get(__ret__, 'groups'),
        id=pulumi.get(__ret__, 'id'),
        name=pulumi.get(__ret__, 'name'),
        nameservers=pulumi.get(__ret__, 'nameservers'),
        primary=pulumi.get(__ret__, 'primary'),
        search_domains_enabled=pulumi.get(__ret__, 'search_domains_enabled'))
def get_nameserver_group_output(id: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                name: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetNameserverGroupResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['id'] = id
    __args__['name'] = name
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('netbird:index/getNameserverGroup:getNameserverGroup', __args__, opts=opts, typ=GetNameserverGroupResult, package_ref=_utilities.get_package())
    return __ret__.apply(lambda __response__: GetNameserverGroupResult(
        description=pulumi.get(__response__, 'description'),
        domains=pulumi.get(__response__, 'domains'),
        enabled=pulumi.get(__response__, 'enabled'),
        groups=pulumi.get(__response__, 'groups'),
        id=pulumi.get(__response__, 'id'),
        name=pulumi.get(__response__, 'name'),
        nameservers=pulumi.get(__response__, 'nameservers'),
        primary=pulumi.get(__response__, 'primary'),
        search_domains_enabled=pulumi.get(__response__, 'search_domains_enabled')))
