# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['NameserverGroupArgs', 'NameserverGroup']

@pulumi.input_type
class NameserverGroupArgs:
    def __init__(__self__, *,
                 groups: pulumi.Input[Sequence[pulumi.Input[_builtins.str]]],
                 nameservers: pulumi.Input[Sequence[pulumi.Input['NameserverGroupNameserverArgs']]],
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 domains: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 primary: Optional[pulumi.Input[_builtins.bool]] = None,
                 search_domains_enabled: Optional[pulumi.Input[_builtins.bool]] = None):
        """
        The set of arguments for constructing a NameserverGroup resource.

        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] groups: Distribution group IDs that defines group of peers that will use this nameserver group
        :param pulumi.Input[Sequence[pulumi.Input['NameserverGroupNameserverArgs']]] nameservers: Nameserver list
        :param pulumi.Input[_builtins.str] description: Description of the nameserver group
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] domains: Match domain list. It should be empty only if primary is true.
        :param pulumi.Input[_builtins.bool] enabled: Nameserver group status
        :param pulumi.Input[_builtins.str] name: Name of nameserver group
        :param pulumi.Input[_builtins.bool] primary: Defines if a nameserver group is primary that resolves all domains. It should be true only if domains list is empty.
        :param pulumi.Input[_builtins.bool] search_domains_enabled: Search domain status for match domains. It should be true only if domains list is not empty.
        """
        pulumi.set(__self__, "groups", groups)
        pulumi.set(__self__, "nameservers", nameservers)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if domains is not None:
            pulumi.set(__self__, "domains", domains)
        if enabled is not None:
            pulumi.set(__self__, "enabled", enabled)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if primary is not None:
            pulumi.set(__self__, "primary", primary)
        if search_domains_enabled is not None:
            pulumi.set(__self__, "search_domains_enabled", search_domains_enabled)

    @_builtins.property
    @pulumi.getter
    def groups(self) -> pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]:
        """
        Distribution group IDs that defines group of peers that will use this nameserver group
        """
        return pulumi.get(self, "groups")

    @groups.setter
    def groups(self, value: pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]):
        pulumi.set(self, "groups", value)

    @_builtins.property
    @pulumi.getter
    def nameservers(self) -> pulumi.Input[Sequence[pulumi.Input['NameserverGroupNameserverArgs']]]:
        """
        Nameserver list
        """
        return pulumi.get(self, "nameservers")

    @nameservers.setter
    def nameservers(self, value: pulumi.Input[Sequence[pulumi.Input['NameserverGroupNameserverArgs']]]):
        pulumi.set(self, "nameservers", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Description of the nameserver group
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def domains(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Match domain list. It should be empty only if primary is true.
        """
        return pulumi.get(self, "domains")

    @domains.setter
    def domains(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "domains", value)

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Nameserver group status
        """
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "enabled", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Name of nameserver group
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def primary(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Defines if a nameserver group is primary that resolves all domains. It should be true only if domains list is empty.
        """
        return pulumi.get(self, "primary")

    @primary.setter
    def primary(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "primary", value)

    @_builtins.property
    @pulumi.getter(name="searchDomainsEnabled")
    def search_domains_enabled(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Search domain status for match domains. It should be true only if domains list is not empty.
        """
        return pulumi.get(self, "search_domains_enabled")

    @search_domains_enabled.setter
    def search_domains_enabled(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "search_domains_enabled", value)


@pulumi.input_type
class _NameserverGroupState:
    def __init__(__self__, *,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 domains: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 groups: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 nameservers: Optional[pulumi.Input[Sequence[pulumi.Input['NameserverGroupNameserverArgs']]]] = None,
                 primary: Optional[pulumi.Input[_builtins.bool]] = None,
                 search_domains_enabled: Optional[pulumi.Input[_builtins.bool]] = None):
        """
        Input properties used for looking up and filtering NameserverGroup resources.

        :param pulumi.Input[_builtins.str] description: Description of the nameserver group
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] domains: Match domain list. It should be empty only if primary is true.
        :param pulumi.Input[_builtins.bool] enabled: Nameserver group status
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] groups: Distribution group IDs that defines group of peers that will use this nameserver group
        :param pulumi.Input[_builtins.str] name: Name of nameserver group
        :param pulumi.Input[Sequence[pulumi.Input['NameserverGroupNameserverArgs']]] nameservers: Nameserver list
        :param pulumi.Input[_builtins.bool] primary: Defines if a nameserver group is primary that resolves all domains. It should be true only if domains list is empty.
        :param pulumi.Input[_builtins.bool] search_domains_enabled: Search domain status for match domains. It should be true only if domains list is not empty.
        """
        if description is not None:
            pulumi.set(__self__, "description", description)
        if domains is not None:
            pulumi.set(__self__, "domains", domains)
        if enabled is not None:
            pulumi.set(__self__, "enabled", enabled)
        if groups is not None:
            pulumi.set(__self__, "groups", groups)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if nameservers is not None:
            pulumi.set(__self__, "nameservers", nameservers)
        if primary is not None:
            pulumi.set(__self__, "primary", primary)
        if search_domains_enabled is not None:
            pulumi.set(__self__, "search_domains_enabled", search_domains_enabled)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Description of the nameserver group
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def domains(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Match domain list. It should be empty only if primary is true.
        """
        return pulumi.get(self, "domains")

    @domains.setter
    def domains(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "domains", value)

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Nameserver group status
        """
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "enabled", value)

    @_builtins.property
    @pulumi.getter
    def groups(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Distribution group IDs that defines group of peers that will use this nameserver group
        """
        return pulumi.get(self, "groups")

    @groups.setter
    def groups(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "groups", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Name of nameserver group
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def nameservers(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['NameserverGroupNameserverArgs']]]]:
        """
        Nameserver list
        """
        return pulumi.get(self, "nameservers")

    @nameservers.setter
    def nameservers(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['NameserverGroupNameserverArgs']]]]):
        pulumi.set(self, "nameservers", value)

    @_builtins.property
    @pulumi.getter
    def primary(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Defines if a nameserver group is primary that resolves all domains. It should be true only if domains list is empty.
        """
        return pulumi.get(self, "primary")

    @primary.setter
    def primary(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "primary", value)

    @_builtins.property
    @pulumi.getter(name="searchDomainsEnabled")
    def search_domains_enabled(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Search domain status for match domains. It should be true only if domains list is not empty.
        """
        return pulumi.get(self, "search_domains_enabled")

    @search_domains_enabled.setter
    def search_domains_enabled(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "search_domains_enabled", value)


@pulumi.type_token("netbird:index/nameserverGroup:NameserverGroup")
class NameserverGroup(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 domains: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 groups: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 nameservers: Optional[pulumi.Input[Sequence[pulumi.Input[Union['NameserverGroupNameserverArgs', 'NameserverGroupNameserverArgsDict']]]]] = None,
                 primary: Optional[pulumi.Input[_builtins.bool]] = None,
                 search_domains_enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 __props__=None):
        """
        Create a NameserverGroup resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] description: Description of the nameserver group
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] domains: Match domain list. It should be empty only if primary is true.
        :param pulumi.Input[_builtins.bool] enabled: Nameserver group status
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] groups: Distribution group IDs that defines group of peers that will use this nameserver group
        :param pulumi.Input[_builtins.str] name: Name of nameserver group
        :param pulumi.Input[Sequence[pulumi.Input[Union['NameserverGroupNameserverArgs', 'NameserverGroupNameserverArgsDict']]]] nameservers: Nameserver list
        :param pulumi.Input[_builtins.bool] primary: Defines if a nameserver group is primary that resolves all domains. It should be true only if domains list is empty.
        :param pulumi.Input[_builtins.bool] search_domains_enabled: Search domain status for match domains. It should be true only if domains list is not empty.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: NameserverGroupArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a NameserverGroup resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param NameserverGroupArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(NameserverGroupArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 domains: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 groups: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 nameservers: Optional[pulumi.Input[Sequence[pulumi.Input[Union['NameserverGroupNameserverArgs', 'NameserverGroupNameserverArgsDict']]]]] = None,
                 primary: Optional[pulumi.Input[_builtins.bool]] = None,
                 search_domains_enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = NameserverGroupArgs.__new__(NameserverGroupArgs)

            __props__.__dict__["description"] = description
            __props__.__dict__["domains"] = domains
            __props__.__dict__["enabled"] = enabled
            if groups is None and not opts.urn:
                raise TypeError("Missing required property 'groups'")
            __props__.__dict__["groups"] = groups
            __props__.__dict__["name"] = name
            if nameservers is None and not opts.urn:
                raise TypeError("Missing required property 'nameservers'")
            __props__.__dict__["nameservers"] = nameservers
            __props__.__dict__["primary"] = primary
            __props__.__dict__["search_domains_enabled"] = search_domains_enabled
        super(NameserverGroup, __self__).__init__(
            'netbird:index/nameserverGroup:NameserverGroup',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            description: Optional[pulumi.Input[_builtins.str]] = None,
            domains: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            enabled: Optional[pulumi.Input[_builtins.bool]] = None,
            groups: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            name: Optional[pulumi.Input[_builtins.str]] = None,
            nameservers: Optional[pulumi.Input[Sequence[pulumi.Input[Union['NameserverGroupNameserverArgs', 'NameserverGroupNameserverArgsDict']]]]] = None,
            primary: Optional[pulumi.Input[_builtins.bool]] = None,
            search_domains_enabled: Optional[pulumi.Input[_builtins.bool]] = None) -> 'NameserverGroup':
        """
        Get an existing NameserverGroup resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] description: Description of the nameserver group
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] domains: Match domain list. It should be empty only if primary is true.
        :param pulumi.Input[_builtins.bool] enabled: Nameserver group status
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] groups: Distribution group IDs that defines group of peers that will use this nameserver group
        :param pulumi.Input[_builtins.str] name: Name of nameserver group
        :param pulumi.Input[Sequence[pulumi.Input[Union['NameserverGroupNameserverArgs', 'NameserverGroupNameserverArgsDict']]]] nameservers: Nameserver list
        :param pulumi.Input[_builtins.bool] primary: Defines if a nameserver group is primary that resolves all domains. It should be true only if domains list is empty.
        :param pulumi.Input[_builtins.bool] search_domains_enabled: Search domain status for match domains. It should be true only if domains list is not empty.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _NameserverGroupState.__new__(_NameserverGroupState)

        __props__.__dict__["description"] = description
        __props__.__dict__["domains"] = domains
        __props__.__dict__["enabled"] = enabled
        __props__.__dict__["groups"] = groups
        __props__.__dict__["name"] = name
        __props__.__dict__["nameservers"] = nameservers
        __props__.__dict__["primary"] = primary
        __props__.__dict__["search_domains_enabled"] = search_domains_enabled
        return NameserverGroup(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[_builtins.str]:
        """
        Description of the nameserver group
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter
    def domains(self) -> pulumi.Output[Sequence[_builtins.str]]:
        """
        Match domain list. It should be empty only if primary is true.
        """
        return pulumi.get(self, "domains")

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> pulumi.Output[_builtins.bool]:
        """
        Nameserver group status
        """
        return pulumi.get(self, "enabled")

    @_builtins.property
    @pulumi.getter
    def groups(self) -> pulumi.Output[Sequence[_builtins.str]]:
        """
        Distribution group IDs that defines group of peers that will use this nameserver group
        """
        return pulumi.get(self, "groups")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Name of nameserver group
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def nameservers(self) -> pulumi.Output[Sequence['outputs.NameserverGroupNameserver']]:
        """
        Nameserver list
        """
        return pulumi.get(self, "nameservers")

    @_builtins.property
    @pulumi.getter
    def primary(self) -> pulumi.Output[_builtins.bool]:
        """
        Defines if a nameserver group is primary that resolves all domains. It should be true only if domains list is empty.
        """
        return pulumi.get(self, "primary")

    @_builtins.property
    @pulumi.getter(name="searchDomainsEnabled")
    def search_domains_enabled(self) -> pulumi.Output[_builtins.bool]:
        """
        Search domain status for match domains. It should be true only if domains list is not empty.
        """
        return pulumi.get(self, "search_domains_enabled")

