# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'NameserverGroupNameserver',
    'PolicyRule',
    'PolicyRuleDestinationResource',
    'PolicyRulePortRange',
    'PolicyRuleSourceResource',
    'PostureCheckGeoLocationCheck',
    'PostureCheckGeoLocationCheckLocation',
    'PostureCheckNetbirdVersionCheck',
    'PostureCheckOsVersionCheck',
    'PostureCheckPeerNetworkRangeCheck',
    'PostureCheckProcessCheck',
    'ReverseProxyServiceAuth',
    'ReverseProxyServiceAuthBearerAuth',
    'ReverseProxyServiceAuthLinkAuth',
    'ReverseProxyServiceAuthPasswordAuth',
    'ReverseProxyServiceAuthPinAuth',
    'ReverseProxyServiceTarget',
    'GetNameserverGroupNameserverResult',
    'GetPolicyRuleResult',
    'GetPolicyRuleDestinationResourceResult',
    'GetPolicyRulePortRangeResult',
    'GetPolicyRuleSourceResourceResult',
    'GetPostureCheckGeoLocationCheckResult',
    'GetPostureCheckGeoLocationCheckLocationResult',
    'GetPostureCheckNetbirdVersionCheckResult',
    'GetPostureCheckOsVersionCheckResult',
    'GetPostureCheckPeerNetworkRangeCheckResult',
    'GetPostureCheckProcessCheckResult',
    'GetReverseProxyClustersClusterResult',
    'GetReverseProxyServiceAuthResult',
    'GetReverseProxyServiceAuthBearerAuthResult',
    'GetReverseProxyServiceAuthLinkAuthResult',
    'GetReverseProxyServiceAuthPasswordAuthResult',
    'GetReverseProxyServiceAuthPinAuthResult',
    'GetReverseProxyServiceTargetResult',
]

@pulumi.output_type
class NameserverGroupNameserver(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "nsType":
            suggest = "ns_type"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in NameserverGroupNameserver. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        NameserverGroupNameserver.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        NameserverGroupNameserver.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 ip: _builtins.str,
                 ns_type: Optional[_builtins.str] = None,
                 port: Optional[_builtins.float] = None):
        """
        :param _builtins.str ip: Nameserver IP
        :param _builtins.str ns_type: Nameserver Type
        :param _builtins.float port: Nameserver Port
        """
        pulumi.set(__self__, "ip", ip)
        if ns_type is not None:
            pulumi.set(__self__, "ns_type", ns_type)
        if port is not None:
            pulumi.set(__self__, "port", port)

    @_builtins.property
    @pulumi.getter
    def ip(self) -> _builtins.str:
        """
        Nameserver IP
        """
        return pulumi.get(self, "ip")

    @_builtins.property
    @pulumi.getter(name="nsType")
    def ns_type(self) -> Optional[_builtins.str]:
        """
        Nameserver Type
        """
        return pulumi.get(self, "ns_type")

    @_builtins.property
    @pulumi.getter
    def port(self) -> Optional[_builtins.float]:
        """
        Nameserver Port
        """
        return pulumi.get(self, "port")


@pulumi.output_type
class PolicyRule(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "authorizedGroups":
            suggest = "authorized_groups"
        elif key == "destinationResource":
            suggest = "destination_resource"
        elif key == "portRanges":
            suggest = "port_ranges"
        elif key == "sourceResource":
            suggest = "source_resource"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in PolicyRule. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        PolicyRule.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        PolicyRule.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 name: _builtins.str,
                 action: Optional[_builtins.str] = None,
                 authorized_groups: Optional[Mapping[str, Sequence[_builtins.str]]] = None,
                 bidirectional: Optional[_builtins.bool] = None,
                 description: Optional[_builtins.str] = None,
                 destination_resource: Optional['outputs.PolicyRuleDestinationResource'] = None,
                 destinations: Optional[Sequence[_builtins.str]] = None,
                 enabled: Optional[_builtins.bool] = None,
                 id: Optional[_builtins.str] = None,
                 port_ranges: Optional[Sequence['outputs.PolicyRulePortRange']] = None,
                 ports: Optional[Sequence[_builtins.str]] = None,
                 protocol: Optional[_builtins.str] = None,
                 source_resource: Optional['outputs.PolicyRuleSourceResource'] = None,
                 sources: Optional[Sequence[_builtins.str]] = None):
        """
        :param _builtins.str name: Policy Name
        :param _builtins.str action: Policy Rule Action (accept|drop)
        :param Mapping[str, Sequence[_builtins.str]] authorized_groups: Map of source group IDs to a list of local users authorized for SSH access. Keys must be group IDs present in <span pulumi-lang-nodejs="`sources`" pulumi-lang-dotnet="`Sources`" pulumi-lang-go="`sources`" pulumi-lang-python="`sources`" pulumi-lang-yaml="`sources`" pulumi-lang-java="`sources`">`sources`</span>. If not set, all local users are permitted. Only applicable when protocol is `netbird-ssh`.
        :param _builtins.bool bidirectional: Policy Rule Bidirectional
        :param _builtins.str description: Policy description
        :param 'PolicyRuleDestinationResourceArgs' destination_resource: Policy Rule Destination Resource (mutually exclusive with destinations)
        :param Sequence[_builtins.str] destinations: Policy Rule Destination Groups (mutually exclusive with destination_resource)
        :param _builtins.bool enabled: Policy Rule Enabled
        :param _builtins.str id: Policy ID
        :param Sequence['PolicyRulePortRangeArgs'] port_ranges: Policy Rule Port Ranges (mutually exclusive with ports)
        :param Sequence[_builtins.str] ports: Policy Rule Ports (mutually exclusive with port_ranges)
        :param _builtins.str protocol: Policy Rule Protocol (tcp|udp|icmp|all|netbird-ssh)
        :param 'PolicyRuleSourceResourceArgs' source_resource: Policy Rule Source Resource (mutually exclusive with sources)
        :param Sequence[_builtins.str] sources: Policy Rule Source Groups (mutually exclusive with source_resource)
        """
        pulumi.set(__self__, "name", name)
        if action is not None:
            pulumi.set(__self__, "action", action)
        if authorized_groups is not None:
            pulumi.set(__self__, "authorized_groups", authorized_groups)
        if bidirectional is not None:
            pulumi.set(__self__, "bidirectional", bidirectional)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if destination_resource is not None:
            pulumi.set(__self__, "destination_resource", destination_resource)
        if destinations is not None:
            pulumi.set(__self__, "destinations", destinations)
        if enabled is not None:
            pulumi.set(__self__, "enabled", enabled)
        if id is not None:
            pulumi.set(__self__, "id", id)
        if port_ranges is not None:
            pulumi.set(__self__, "port_ranges", port_ranges)
        if ports is not None:
            pulumi.set(__self__, "ports", ports)
        if protocol is not None:
            pulumi.set(__self__, "protocol", protocol)
        if source_resource is not None:
            pulumi.set(__self__, "source_resource", source_resource)
        if sources is not None:
            pulumi.set(__self__, "sources", sources)

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        Policy Name
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def action(self) -> Optional[_builtins.str]:
        """
        Policy Rule Action (accept|drop)
        """
        return pulumi.get(self, "action")

    @_builtins.property
    @pulumi.getter(name="authorizedGroups")
    def authorized_groups(self) -> Optional[Mapping[str, Sequence[_builtins.str]]]:
        """
        Map of source group IDs to a list of local users authorized for SSH access. Keys must be group IDs present in <span pulumi-lang-nodejs="`sources`" pulumi-lang-dotnet="`Sources`" pulumi-lang-go="`sources`" pulumi-lang-python="`sources`" pulumi-lang-yaml="`sources`" pulumi-lang-java="`sources`">`sources`</span>. If not set, all local users are permitted. Only applicable when protocol is `netbird-ssh`.
        """
        return pulumi.get(self, "authorized_groups")

    @_builtins.property
    @pulumi.getter
    def bidirectional(self) -> Optional[_builtins.bool]:
        """
        Policy Rule Bidirectional
        """
        return pulumi.get(self, "bidirectional")

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[_builtins.str]:
        """
        Policy description
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter(name="destinationResource")
    def destination_resource(self) -> Optional['outputs.PolicyRuleDestinationResource']:
        """
        Policy Rule Destination Resource (mutually exclusive with destinations)
        """
        return pulumi.get(self, "destination_resource")

    @_builtins.property
    @pulumi.getter
    def destinations(self) -> Optional[Sequence[_builtins.str]]:
        """
        Policy Rule Destination Groups (mutually exclusive with destination_resource)
        """
        return pulumi.get(self, "destinations")

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> Optional[_builtins.bool]:
        """
        Policy Rule Enabled
        """
        return pulumi.get(self, "enabled")

    @_builtins.property
    @pulumi.getter
    def id(self) -> Optional[_builtins.str]:
        """
        Policy ID
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="portRanges")
    def port_ranges(self) -> Optional[Sequence['outputs.PolicyRulePortRange']]:
        """
        Policy Rule Port Ranges (mutually exclusive with ports)
        """
        return pulumi.get(self, "port_ranges")

    @_builtins.property
    @pulumi.getter
    def ports(self) -> Optional[Sequence[_builtins.str]]:
        """
        Policy Rule Ports (mutually exclusive with port_ranges)
        """
        return pulumi.get(self, "ports")

    @_builtins.property
    @pulumi.getter
    def protocol(self) -> Optional[_builtins.str]:
        """
        Policy Rule Protocol (tcp|udp|icmp|all|netbird-ssh)
        """
        return pulumi.get(self, "protocol")

    @_builtins.property
    @pulumi.getter(name="sourceResource")
    def source_resource(self) -> Optional['outputs.PolicyRuleSourceResource']:
        """
        Policy Rule Source Resource (mutually exclusive with sources)
        """
        return pulumi.get(self, "source_resource")

    @_builtins.property
    @pulumi.getter
    def sources(self) -> Optional[Sequence[_builtins.str]]:
        """
        Policy Rule Source Groups (mutually exclusive with source_resource)
        """
        return pulumi.get(self, "sources")


@pulumi.output_type
class PolicyRuleDestinationResource(dict):
    def __init__(__self__, *,
                 id: _builtins.str,
                 type: _builtins.str):
        pulumi.set(__self__, "id", id)
        pulumi.set(__self__, "type", type)

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def type(self) -> _builtins.str:
        return pulumi.get(self, "type")


@pulumi.output_type
class PolicyRulePortRange(dict):
    def __init__(__self__, *,
                 end: _builtins.float,
                 start: _builtins.float):
        pulumi.set(__self__, "end", end)
        pulumi.set(__self__, "start", start)

    @_builtins.property
    @pulumi.getter
    def end(self) -> _builtins.float:
        return pulumi.get(self, "end")

    @_builtins.property
    @pulumi.getter
    def start(self) -> _builtins.float:
        return pulumi.get(self, "start")


@pulumi.output_type
class PolicyRuleSourceResource(dict):
    def __init__(__self__, *,
                 id: _builtins.str,
                 type: _builtins.str):
        pulumi.set(__self__, "id", id)
        pulumi.set(__self__, "type", type)

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def type(self) -> _builtins.str:
        return pulumi.get(self, "type")


@pulumi.output_type
class PostureCheckGeoLocationCheck(dict):
    def __init__(__self__, *,
                 action: Optional[_builtins.str] = None,
                 locations: Optional[Sequence['outputs.PostureCheckGeoLocationCheckLocation']] = None):
        if action is not None:
            pulumi.set(__self__, "action", action)
        if locations is not None:
            pulumi.set(__self__, "locations", locations)

    @_builtins.property
    @pulumi.getter
    def action(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "action")

    @_builtins.property
    @pulumi.getter
    def locations(self) -> Optional[Sequence['outputs.PostureCheckGeoLocationCheckLocation']]:
        return pulumi.get(self, "locations")


@pulumi.output_type
class PostureCheckGeoLocationCheckLocation(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "countryCode":
            suggest = "country_code"
        elif key == "cityName":
            suggest = "city_name"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in PostureCheckGeoLocationCheckLocation. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        PostureCheckGeoLocationCheckLocation.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        PostureCheckGeoLocationCheckLocation.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 country_code: _builtins.str,
                 city_name: Optional[_builtins.str] = None):
        pulumi.set(__self__, "country_code", country_code)
        if city_name is not None:
            pulumi.set(__self__, "city_name", city_name)

    @_builtins.property
    @pulumi.getter(name="countryCode")
    def country_code(self) -> _builtins.str:
        return pulumi.get(self, "country_code")

    @_builtins.property
    @pulumi.getter(name="cityName")
    def city_name(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "city_name")


@pulumi.output_type
class PostureCheckNetbirdVersionCheck(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "minVersion":
            suggest = "min_version"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in PostureCheckNetbirdVersionCheck. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        PostureCheckNetbirdVersionCheck.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        PostureCheckNetbirdVersionCheck.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 min_version: Optional[_builtins.str] = None):
        if min_version is not None:
            pulumi.set(__self__, "min_version", min_version)

    @_builtins.property
    @pulumi.getter(name="minVersion")
    def min_version(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "min_version")


@pulumi.output_type
class PostureCheckOsVersionCheck(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "androidMinVersion":
            suggest = "android_min_version"
        elif key == "darwinMinVersion":
            suggest = "darwin_min_version"
        elif key == "iosMinVersion":
            suggest = "ios_min_version"
        elif key == "linuxMinKernelVersion":
            suggest = "linux_min_kernel_version"
        elif key == "windowsMinKernelVersion":
            suggest = "windows_min_kernel_version"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in PostureCheckOsVersionCheck. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        PostureCheckOsVersionCheck.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        PostureCheckOsVersionCheck.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 android_min_version: Optional[_builtins.str] = None,
                 darwin_min_version: Optional[_builtins.str] = None,
                 ios_min_version: Optional[_builtins.str] = None,
                 linux_min_kernel_version: Optional[_builtins.str] = None,
                 windows_min_kernel_version: Optional[_builtins.str] = None):
        if android_min_version is not None:
            pulumi.set(__self__, "android_min_version", android_min_version)
        if darwin_min_version is not None:
            pulumi.set(__self__, "darwin_min_version", darwin_min_version)
        if ios_min_version is not None:
            pulumi.set(__self__, "ios_min_version", ios_min_version)
        if linux_min_kernel_version is not None:
            pulumi.set(__self__, "linux_min_kernel_version", linux_min_kernel_version)
        if windows_min_kernel_version is not None:
            pulumi.set(__self__, "windows_min_kernel_version", windows_min_kernel_version)

    @_builtins.property
    @pulumi.getter(name="androidMinVersion")
    def android_min_version(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "android_min_version")

    @_builtins.property
    @pulumi.getter(name="darwinMinVersion")
    def darwin_min_version(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "darwin_min_version")

    @_builtins.property
    @pulumi.getter(name="iosMinVersion")
    def ios_min_version(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "ios_min_version")

    @_builtins.property
    @pulumi.getter(name="linuxMinKernelVersion")
    def linux_min_kernel_version(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "linux_min_kernel_version")

    @_builtins.property
    @pulumi.getter(name="windowsMinKernelVersion")
    def windows_min_kernel_version(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "windows_min_kernel_version")


@pulumi.output_type
class PostureCheckPeerNetworkRangeCheck(dict):
    def __init__(__self__, *,
                 action: Optional[_builtins.str] = None,
                 ranges: Optional[Sequence[_builtins.str]] = None):
        if action is not None:
            pulumi.set(__self__, "action", action)
        if ranges is not None:
            pulumi.set(__self__, "ranges", ranges)

    @_builtins.property
    @pulumi.getter
    def action(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "action")

    @_builtins.property
    @pulumi.getter
    def ranges(self) -> Optional[Sequence[_builtins.str]]:
        return pulumi.get(self, "ranges")


@pulumi.output_type
class PostureCheckProcessCheck(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "linuxPath":
            suggest = "linux_path"
        elif key == "macPath":
            suggest = "mac_path"
        elif key == "windowsPath":
            suggest = "windows_path"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in PostureCheckProcessCheck. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        PostureCheckProcessCheck.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        PostureCheckProcessCheck.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 linux_path: Optional[_builtins.str] = None,
                 mac_path: Optional[_builtins.str] = None,
                 windows_path: Optional[_builtins.str] = None):
        if linux_path is not None:
            pulumi.set(__self__, "linux_path", linux_path)
        if mac_path is not None:
            pulumi.set(__self__, "mac_path", mac_path)
        if windows_path is not None:
            pulumi.set(__self__, "windows_path", windows_path)

    @_builtins.property
    @pulumi.getter(name="linuxPath")
    def linux_path(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "linux_path")

    @_builtins.property
    @pulumi.getter(name="macPath")
    def mac_path(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "mac_path")

    @_builtins.property
    @pulumi.getter(name="windowsPath")
    def windows_path(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "windows_path")


@pulumi.output_type
class ReverseProxyServiceAuth(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "bearerAuth":
            suggest = "bearer_auth"
        elif key == "linkAuth":
            suggest = "link_auth"
        elif key == "passwordAuth":
            suggest = "password_auth"
        elif key == "pinAuth":
            suggest = "pin_auth"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in ReverseProxyServiceAuth. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        ReverseProxyServiceAuth.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        ReverseProxyServiceAuth.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 bearer_auth: Optional['outputs.ReverseProxyServiceAuthBearerAuth'] = None,
                 link_auth: Optional['outputs.ReverseProxyServiceAuthLinkAuth'] = None,
                 password_auth: Optional['outputs.ReverseProxyServiceAuthPasswordAuth'] = None,
                 pin_auth: Optional['outputs.ReverseProxyServiceAuthPinAuth'] = None):
        """
        :param 'ReverseProxyServiceAuthBearerAuthArgs' bearer_auth: Bearer token authentication
        :param 'ReverseProxyServiceAuthLinkAuthArgs' link_auth: Link authentication
        :param 'ReverseProxyServiceAuthPasswordAuthArgs' password_auth: Password authentication
        :param 'ReverseProxyServiceAuthPinAuthArgs' pin_auth: PIN authentication
        """
        if bearer_auth is not None:
            pulumi.set(__self__, "bearer_auth", bearer_auth)
        if link_auth is not None:
            pulumi.set(__self__, "link_auth", link_auth)
        if password_auth is not None:
            pulumi.set(__self__, "password_auth", password_auth)
        if pin_auth is not None:
            pulumi.set(__self__, "pin_auth", pin_auth)

    @_builtins.property
    @pulumi.getter(name="bearerAuth")
    def bearer_auth(self) -> Optional['outputs.ReverseProxyServiceAuthBearerAuth']:
        """
        Bearer token authentication
        """
        return pulumi.get(self, "bearer_auth")

    @_builtins.property
    @pulumi.getter(name="linkAuth")
    def link_auth(self) -> Optional['outputs.ReverseProxyServiceAuthLinkAuth']:
        """
        Link authentication
        """
        return pulumi.get(self, "link_auth")

    @_builtins.property
    @pulumi.getter(name="passwordAuth")
    def password_auth(self) -> Optional['outputs.ReverseProxyServiceAuthPasswordAuth']:
        """
        Password authentication
        """
        return pulumi.get(self, "password_auth")

    @_builtins.property
    @pulumi.getter(name="pinAuth")
    def pin_auth(self) -> Optional['outputs.ReverseProxyServiceAuthPinAuth']:
        """
        PIN authentication
        """
        return pulumi.get(self, "pin_auth")


@pulumi.output_type
class ReverseProxyServiceAuthBearerAuth(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "distributionGroups":
            suggest = "distribution_groups"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in ReverseProxyServiceAuthBearerAuth. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        ReverseProxyServiceAuthBearerAuth.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        ReverseProxyServiceAuthBearerAuth.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 enabled: _builtins.bool,
                 distribution_groups: Optional[Sequence[_builtins.str]] = None):
        """
        :param Sequence[_builtins.str] distribution_groups: List of group IDs that can use bearer auth
        """
        pulumi.set(__self__, "enabled", enabled)
        if distribution_groups is not None:
            pulumi.set(__self__, "distribution_groups", distribution_groups)

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> _builtins.bool:
        return pulumi.get(self, "enabled")

    @_builtins.property
    @pulumi.getter(name="distributionGroups")
    def distribution_groups(self) -> Optional[Sequence[_builtins.str]]:
        """
        List of group IDs that can use bearer auth
        """
        return pulumi.get(self, "distribution_groups")


@pulumi.output_type
class ReverseProxyServiceAuthLinkAuth(dict):
    def __init__(__self__, *,
                 enabled: _builtins.bool):
        pulumi.set(__self__, "enabled", enabled)

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> _builtins.bool:
        return pulumi.get(self, "enabled")


@pulumi.output_type
class ReverseProxyServiceAuthPasswordAuth(dict):
    def __init__(__self__, *,
                 enabled: _builtins.bool,
                 password: Optional[_builtins.str] = None):
        pulumi.set(__self__, "enabled", enabled)
        if password is not None:
            pulumi.set(__self__, "password", password)

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> _builtins.bool:
        return pulumi.get(self, "enabled")

    @_builtins.property
    @pulumi.getter
    def password(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "password")


@pulumi.output_type
class ReverseProxyServiceAuthPinAuth(dict):
    def __init__(__self__, *,
                 enabled: _builtins.bool,
                 pin: Optional[_builtins.str] = None):
        pulumi.set(__self__, "enabled", enabled)
        if pin is not None:
            pulumi.set(__self__, "pin", pin)

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> _builtins.bool:
        return pulumi.get(self, "enabled")

    @_builtins.property
    @pulumi.getter
    def pin(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "pin")


@pulumi.output_type
class ReverseProxyServiceTarget(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "targetId":
            suggest = "target_id"
        elif key == "targetType":
            suggest = "target_type"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in ReverseProxyServiceTarget. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        ReverseProxyServiceTarget.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        ReverseProxyServiceTarget.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 port: _builtins.float,
                 protocol: _builtins.str,
                 target_id: _builtins.str,
                 target_type: _builtins.str,
                 enabled: Optional[_builtins.bool] = None,
                 host: Optional[_builtins.str] = None,
                 path: Optional[_builtins.str] = None):
        """
        :param _builtins.float port: Backend port for this target (0 for scheme default)
        :param _builtins.str protocol: Protocol to use when connecting to the backend (http, https)
        :param _builtins.str target_id: Target ID (resource or peer ID)
        :param _builtins.str target_type: Target type (peer, host, domain, subnet)
        :param _builtins.bool enabled: Whether this target is enabled
        :param _builtins.str host: Backend IP or domain for this target. If omitted, the API resolves it from the target peer.
        :param _builtins.str path: URL path prefix for this target. Defaults to "/" if omitted.
        """
        pulumi.set(__self__, "port", port)
        pulumi.set(__self__, "protocol", protocol)
        pulumi.set(__self__, "target_id", target_id)
        pulumi.set(__self__, "target_type", target_type)
        if enabled is not None:
            pulumi.set(__self__, "enabled", enabled)
        if host is not None:
            pulumi.set(__self__, "host", host)
        if path is not None:
            pulumi.set(__self__, "path", path)

    @_builtins.property
    @pulumi.getter
    def port(self) -> _builtins.float:
        """
        Backend port for this target (0 for scheme default)
        """
        return pulumi.get(self, "port")

    @_builtins.property
    @pulumi.getter
    def protocol(self) -> _builtins.str:
        """
        Protocol to use when connecting to the backend (http, https)
        """
        return pulumi.get(self, "protocol")

    @_builtins.property
    @pulumi.getter(name="targetId")
    def target_id(self) -> _builtins.str:
        """
        Target ID (resource or peer ID)
        """
        return pulumi.get(self, "target_id")

    @_builtins.property
    @pulumi.getter(name="targetType")
    def target_type(self) -> _builtins.str:
        """
        Target type (peer, host, domain, subnet)
        """
        return pulumi.get(self, "target_type")

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> Optional[_builtins.bool]:
        """
        Whether this target is enabled
        """
        return pulumi.get(self, "enabled")

    @_builtins.property
    @pulumi.getter
    def host(self) -> Optional[_builtins.str]:
        """
        Backend IP or domain for this target. If omitted, the API resolves it from the target peer.
        """
        return pulumi.get(self, "host")

    @_builtins.property
    @pulumi.getter
    def path(self) -> Optional[_builtins.str]:
        """
        URL path prefix for this target. Defaults to "/" if omitted.
        """
        return pulumi.get(self, "path")


@pulumi.output_type
class GetNameserverGroupNameserverResult(dict):
    def __init__(__self__, *,
                 ip: _builtins.str,
                 ns_type: _builtins.str,
                 port: _builtins.float):
        """
        :param _builtins.str ip: Nameserver IP
        :param _builtins.str ns_type: Nameserver Type
        :param _builtins.float port: Nameserver Port
        """
        pulumi.set(__self__, "ip", ip)
        pulumi.set(__self__, "ns_type", ns_type)
        pulumi.set(__self__, "port", port)

    @_builtins.property
    @pulumi.getter
    def ip(self) -> _builtins.str:
        """
        Nameserver IP
        """
        return pulumi.get(self, "ip")

    @_builtins.property
    @pulumi.getter(name="nsType")
    def ns_type(self) -> _builtins.str:
        """
        Nameserver Type
        """
        return pulumi.get(self, "ns_type")

    @_builtins.property
    @pulumi.getter
    def port(self) -> _builtins.float:
        """
        Nameserver Port
        """
        return pulumi.get(self, "port")


@pulumi.output_type
class GetPolicyRuleResult(dict):
    def __init__(__self__, *,
                 action: _builtins.str,
                 authorized_groups: Mapping[str, Sequence[_builtins.str]],
                 bidirectional: _builtins.bool,
                 description: _builtins.str,
                 destination_resource: 'outputs.GetPolicyRuleDestinationResourceResult',
                 destinations: Sequence[_builtins.str],
                 enabled: _builtins.bool,
                 id: _builtins.str,
                 name: _builtins.str,
                 port_ranges: Sequence['outputs.GetPolicyRulePortRangeResult'],
                 ports: Sequence[_builtins.str],
                 protocol: _builtins.str,
                 source_resource: 'outputs.GetPolicyRuleSourceResourceResult',
                 sources: Sequence[_builtins.str]):
        """
        :param _builtins.str action: Policy Rule Action (accept|drop)
        :param Mapping[str, Sequence[_builtins.str]] authorized_groups: Map of source group IDs to a list of local users authorized for SSH access. Keys must be group IDs present in <span pulumi-lang-nodejs="`sources`" pulumi-lang-dotnet="`Sources`" pulumi-lang-go="`sources`" pulumi-lang-python="`sources`" pulumi-lang-yaml="`sources`" pulumi-lang-java="`sources`">`sources`</span>. If not set, all local users are permitted. Only applicable when protocol is `netbird-ssh`.
        :param _builtins.bool bidirectional: Policy Rule Bidirectional
        :param _builtins.str description: Policy description
        :param 'GetPolicyRuleDestinationResourceArgs' destination_resource: Policy Rule Destination Resource (mutually exclusive with destinations)
        :param Sequence[_builtins.str] destinations: Policy Rule Destination Groups (mutually exclusive with destination_resource)
        :param _builtins.bool enabled: Policy Rule Enabled
        :param _builtins.str id: Policy ID
        :param _builtins.str name: Policy Name
        :param Sequence['GetPolicyRulePortRangeArgs'] port_ranges: Policy Rule Port Ranges (mutually exclusive with ports)
        :param Sequence[_builtins.str] ports: Policy Rule Ports (mutually exclusive with port_ranges)
        :param _builtins.str protocol: Policy Rule Protocol (tcp|udp|icmp|all|netbird-ssh)
        :param 'GetPolicyRuleSourceResourceArgs' source_resource: Policy Rule Source Resource (mutually exclusive with sources)
        :param Sequence[_builtins.str] sources: Policy Rule Source Groups (mutually exclusive with source_resource)
        """
        pulumi.set(__self__, "action", action)
        pulumi.set(__self__, "authorized_groups", authorized_groups)
        pulumi.set(__self__, "bidirectional", bidirectional)
        pulumi.set(__self__, "description", description)
        pulumi.set(__self__, "destination_resource", destination_resource)
        pulumi.set(__self__, "destinations", destinations)
        pulumi.set(__self__, "enabled", enabled)
        pulumi.set(__self__, "id", id)
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "port_ranges", port_ranges)
        pulumi.set(__self__, "ports", ports)
        pulumi.set(__self__, "protocol", protocol)
        pulumi.set(__self__, "source_resource", source_resource)
        pulumi.set(__self__, "sources", sources)

    @_builtins.property
    @pulumi.getter
    def action(self) -> _builtins.str:
        """
        Policy Rule Action (accept|drop)
        """
        return pulumi.get(self, "action")

    @_builtins.property
    @pulumi.getter(name="authorizedGroups")
    def authorized_groups(self) -> Mapping[str, Sequence[_builtins.str]]:
        """
        Map of source group IDs to a list of local users authorized for SSH access. Keys must be group IDs present in <span pulumi-lang-nodejs="`sources`" pulumi-lang-dotnet="`Sources`" pulumi-lang-go="`sources`" pulumi-lang-python="`sources`" pulumi-lang-yaml="`sources`" pulumi-lang-java="`sources`">`sources`</span>. If not set, all local users are permitted. Only applicable when protocol is `netbird-ssh`.
        """
        return pulumi.get(self, "authorized_groups")

    @_builtins.property
    @pulumi.getter
    def bidirectional(self) -> _builtins.bool:
        """
        Policy Rule Bidirectional
        """
        return pulumi.get(self, "bidirectional")

    @_builtins.property
    @pulumi.getter
    def description(self) -> _builtins.str:
        """
        Policy description
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter(name="destinationResource")
    def destination_resource(self) -> 'outputs.GetPolicyRuleDestinationResourceResult':
        """
        Policy Rule Destination Resource (mutually exclusive with destinations)
        """
        return pulumi.get(self, "destination_resource")

    @_builtins.property
    @pulumi.getter
    def destinations(self) -> Sequence[_builtins.str]:
        """
        Policy Rule Destination Groups (mutually exclusive with destination_resource)
        """
        return pulumi.get(self, "destinations")

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> _builtins.bool:
        """
        Policy Rule Enabled
        """
        return pulumi.get(self, "enabled")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        Policy ID
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        Policy Name
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="portRanges")
    def port_ranges(self) -> Sequence['outputs.GetPolicyRulePortRangeResult']:
        """
        Policy Rule Port Ranges (mutually exclusive with ports)
        """
        return pulumi.get(self, "port_ranges")

    @_builtins.property
    @pulumi.getter
    def ports(self) -> Sequence[_builtins.str]:
        """
        Policy Rule Ports (mutually exclusive with port_ranges)
        """
        return pulumi.get(self, "ports")

    @_builtins.property
    @pulumi.getter
    def protocol(self) -> _builtins.str:
        """
        Policy Rule Protocol (tcp|udp|icmp|all|netbird-ssh)
        """
        return pulumi.get(self, "protocol")

    @_builtins.property
    @pulumi.getter(name="sourceResource")
    def source_resource(self) -> 'outputs.GetPolicyRuleSourceResourceResult':
        """
        Policy Rule Source Resource (mutually exclusive with sources)
        """
        return pulumi.get(self, "source_resource")

    @_builtins.property
    @pulumi.getter
    def sources(self) -> Sequence[_builtins.str]:
        """
        Policy Rule Source Groups (mutually exclusive with source_resource)
        """
        return pulumi.get(self, "sources")


@pulumi.output_type
class GetPolicyRuleDestinationResourceResult(dict):
    def __init__(__self__, *,
                 id: _builtins.str,
                 type: _builtins.str):
        pulumi.set(__self__, "id", id)
        pulumi.set(__self__, "type", type)

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def type(self) -> _builtins.str:
        return pulumi.get(self, "type")


@pulumi.output_type
class GetPolicyRulePortRangeResult(dict):
    def __init__(__self__, *,
                 end: _builtins.float,
                 start: _builtins.float):
        pulumi.set(__self__, "end", end)
        pulumi.set(__self__, "start", start)

    @_builtins.property
    @pulumi.getter
    def end(self) -> _builtins.float:
        return pulumi.get(self, "end")

    @_builtins.property
    @pulumi.getter
    def start(self) -> _builtins.float:
        return pulumi.get(self, "start")


@pulumi.output_type
class GetPolicyRuleSourceResourceResult(dict):
    def __init__(__self__, *,
                 id: _builtins.str,
                 type: _builtins.str):
        pulumi.set(__self__, "id", id)
        pulumi.set(__self__, "type", type)

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def type(self) -> _builtins.str:
        return pulumi.get(self, "type")


@pulumi.output_type
class GetPostureCheckGeoLocationCheckResult(dict):
    def __init__(__self__, *,
                 action: _builtins.str,
                 locations: Sequence['outputs.GetPostureCheckGeoLocationCheckLocationResult']):
        pulumi.set(__self__, "action", action)
        pulumi.set(__self__, "locations", locations)

    @_builtins.property
    @pulumi.getter
    def action(self) -> _builtins.str:
        return pulumi.get(self, "action")

    @_builtins.property
    @pulumi.getter
    def locations(self) -> Sequence['outputs.GetPostureCheckGeoLocationCheckLocationResult']:
        return pulumi.get(self, "locations")


@pulumi.output_type
class GetPostureCheckGeoLocationCheckLocationResult(dict):
    def __init__(__self__, *,
                 city_name: _builtins.str,
                 country_code: _builtins.str):
        pulumi.set(__self__, "city_name", city_name)
        pulumi.set(__self__, "country_code", country_code)

    @_builtins.property
    @pulumi.getter(name="cityName")
    def city_name(self) -> _builtins.str:
        return pulumi.get(self, "city_name")

    @_builtins.property
    @pulumi.getter(name="countryCode")
    def country_code(self) -> _builtins.str:
        return pulumi.get(self, "country_code")


@pulumi.output_type
class GetPostureCheckNetbirdVersionCheckResult(dict):
    def __init__(__self__, *,
                 min_version: _builtins.str):
        pulumi.set(__self__, "min_version", min_version)

    @_builtins.property
    @pulumi.getter(name="minVersion")
    def min_version(self) -> _builtins.str:
        return pulumi.get(self, "min_version")


@pulumi.output_type
class GetPostureCheckOsVersionCheckResult(dict):
    def __init__(__self__, *,
                 android_min_version: _builtins.str,
                 darwin_min_version: _builtins.str,
                 ios_min_version: _builtins.str,
                 linux_min_kernel_version: _builtins.str,
                 windows_min_kernel_version: _builtins.str):
        pulumi.set(__self__, "android_min_version", android_min_version)
        pulumi.set(__self__, "darwin_min_version", darwin_min_version)
        pulumi.set(__self__, "ios_min_version", ios_min_version)
        pulumi.set(__self__, "linux_min_kernel_version", linux_min_kernel_version)
        pulumi.set(__self__, "windows_min_kernel_version", windows_min_kernel_version)

    @_builtins.property
    @pulumi.getter(name="androidMinVersion")
    def android_min_version(self) -> _builtins.str:
        return pulumi.get(self, "android_min_version")

    @_builtins.property
    @pulumi.getter(name="darwinMinVersion")
    def darwin_min_version(self) -> _builtins.str:
        return pulumi.get(self, "darwin_min_version")

    @_builtins.property
    @pulumi.getter(name="iosMinVersion")
    def ios_min_version(self) -> _builtins.str:
        return pulumi.get(self, "ios_min_version")

    @_builtins.property
    @pulumi.getter(name="linuxMinKernelVersion")
    def linux_min_kernel_version(self) -> _builtins.str:
        return pulumi.get(self, "linux_min_kernel_version")

    @_builtins.property
    @pulumi.getter(name="windowsMinKernelVersion")
    def windows_min_kernel_version(self) -> _builtins.str:
        return pulumi.get(self, "windows_min_kernel_version")


@pulumi.output_type
class GetPostureCheckPeerNetworkRangeCheckResult(dict):
    def __init__(__self__, *,
                 action: _builtins.str,
                 ranges: Sequence[_builtins.str]):
        pulumi.set(__self__, "action", action)
        pulumi.set(__self__, "ranges", ranges)

    @_builtins.property
    @pulumi.getter
    def action(self) -> _builtins.str:
        return pulumi.get(self, "action")

    @_builtins.property
    @pulumi.getter
    def ranges(self) -> Sequence[_builtins.str]:
        return pulumi.get(self, "ranges")


@pulumi.output_type
class GetPostureCheckProcessCheckResult(dict):
    def __init__(__self__, *,
                 linux_path: _builtins.str,
                 mac_path: _builtins.str,
                 windows_path: _builtins.str):
        pulumi.set(__self__, "linux_path", linux_path)
        pulumi.set(__self__, "mac_path", mac_path)
        pulumi.set(__self__, "windows_path", windows_path)

    @_builtins.property
    @pulumi.getter(name="linuxPath")
    def linux_path(self) -> _builtins.str:
        return pulumi.get(self, "linux_path")

    @_builtins.property
    @pulumi.getter(name="macPath")
    def mac_path(self) -> _builtins.str:
        return pulumi.get(self, "mac_path")

    @_builtins.property
    @pulumi.getter(name="windowsPath")
    def windows_path(self) -> _builtins.str:
        return pulumi.get(self, "windows_path")


@pulumi.output_type
class GetReverseProxyClustersClusterResult(dict):
    def __init__(__self__, *,
                 address: _builtins.str,
                 connected_proxies: _builtins.float):
        """
        :param _builtins.str address: Cluster address used for CNAME targets
        :param _builtins.float connected_proxies: Number of proxy nodes connected in this cluster
        """
        pulumi.set(__self__, "address", address)
        pulumi.set(__self__, "connected_proxies", connected_proxies)

    @_builtins.property
    @pulumi.getter
    def address(self) -> _builtins.str:
        """
        Cluster address used for CNAME targets
        """
        return pulumi.get(self, "address")

    @_builtins.property
    @pulumi.getter(name="connectedProxies")
    def connected_proxies(self) -> _builtins.float:
        """
        Number of proxy nodes connected in this cluster
        """
        return pulumi.get(self, "connected_proxies")


@pulumi.output_type
class GetReverseProxyServiceAuthResult(dict):
    def __init__(__self__, *,
                 bearer_auth: 'outputs.GetReverseProxyServiceAuthBearerAuthResult',
                 link_auth: 'outputs.GetReverseProxyServiceAuthLinkAuthResult',
                 password_auth: 'outputs.GetReverseProxyServiceAuthPasswordAuthResult',
                 pin_auth: 'outputs.GetReverseProxyServiceAuthPinAuthResult'):
        """
        :param 'GetReverseProxyServiceAuthBearerAuthArgs' bearer_auth: Bearer token authentication
        :param 'GetReverseProxyServiceAuthLinkAuthArgs' link_auth: Link authentication
        :param 'GetReverseProxyServiceAuthPasswordAuthArgs' password_auth: Password authentication
        :param 'GetReverseProxyServiceAuthPinAuthArgs' pin_auth: PIN authentication
        """
        pulumi.set(__self__, "bearer_auth", bearer_auth)
        pulumi.set(__self__, "link_auth", link_auth)
        pulumi.set(__self__, "password_auth", password_auth)
        pulumi.set(__self__, "pin_auth", pin_auth)

    @_builtins.property
    @pulumi.getter(name="bearerAuth")
    def bearer_auth(self) -> 'outputs.GetReverseProxyServiceAuthBearerAuthResult':
        """
        Bearer token authentication
        """
        return pulumi.get(self, "bearer_auth")

    @_builtins.property
    @pulumi.getter(name="linkAuth")
    def link_auth(self) -> 'outputs.GetReverseProxyServiceAuthLinkAuthResult':
        """
        Link authentication
        """
        return pulumi.get(self, "link_auth")

    @_builtins.property
    @pulumi.getter(name="passwordAuth")
    def password_auth(self) -> 'outputs.GetReverseProxyServiceAuthPasswordAuthResult':
        """
        Password authentication
        """
        return pulumi.get(self, "password_auth")

    @_builtins.property
    @pulumi.getter(name="pinAuth")
    def pin_auth(self) -> 'outputs.GetReverseProxyServiceAuthPinAuthResult':
        """
        PIN authentication
        """
        return pulumi.get(self, "pin_auth")


@pulumi.output_type
class GetReverseProxyServiceAuthBearerAuthResult(dict):
    def __init__(__self__, *,
                 distribution_groups: Sequence[_builtins.str],
                 enabled: _builtins.bool):
        """
        :param Sequence[_builtins.str] distribution_groups: List of group IDs that can use bearer auth
        """
        pulumi.set(__self__, "distribution_groups", distribution_groups)
        pulumi.set(__self__, "enabled", enabled)

    @_builtins.property
    @pulumi.getter(name="distributionGroups")
    def distribution_groups(self) -> Sequence[_builtins.str]:
        """
        List of group IDs that can use bearer auth
        """
        return pulumi.get(self, "distribution_groups")

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> _builtins.bool:
        return pulumi.get(self, "enabled")


@pulumi.output_type
class GetReverseProxyServiceAuthLinkAuthResult(dict):
    def __init__(__self__, *,
                 enabled: _builtins.bool):
        pulumi.set(__self__, "enabled", enabled)

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> _builtins.bool:
        return pulumi.get(self, "enabled")


@pulumi.output_type
class GetReverseProxyServiceAuthPasswordAuthResult(dict):
    def __init__(__self__, *,
                 enabled: _builtins.bool,
                 password: _builtins.str):
        pulumi.set(__self__, "enabled", enabled)
        pulumi.set(__self__, "password", password)

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> _builtins.bool:
        return pulumi.get(self, "enabled")

    @_builtins.property
    @pulumi.getter
    def password(self) -> _builtins.str:
        return pulumi.get(self, "password")


@pulumi.output_type
class GetReverseProxyServiceAuthPinAuthResult(dict):
    def __init__(__self__, *,
                 enabled: _builtins.bool,
                 pin: _builtins.str):
        pulumi.set(__self__, "enabled", enabled)
        pulumi.set(__self__, "pin", pin)

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> _builtins.bool:
        return pulumi.get(self, "enabled")

    @_builtins.property
    @pulumi.getter
    def pin(self) -> _builtins.str:
        return pulumi.get(self, "pin")


@pulumi.output_type
class GetReverseProxyServiceTargetResult(dict):
    def __init__(__self__, *,
                 enabled: _builtins.bool,
                 host: _builtins.str,
                 path: _builtins.str,
                 port: _builtins.float,
                 protocol: _builtins.str,
                 target_id: _builtins.str,
                 target_type: _builtins.str):
        """
        :param _builtins.bool enabled: Whether this target is enabled
        :param _builtins.str host: Backend IP or domain for this target
        :param _builtins.str path: URL path prefix for this target
        :param _builtins.float port: Backend port for this target
        :param _builtins.str protocol: Protocol to use when connecting to the backend (http, https)
        :param _builtins.str target_id: Target ID (resource or peer ID)
        :param _builtins.str target_type: Target type (peer, host, domain, subnet)
        """
        pulumi.set(__self__, "enabled", enabled)
        pulumi.set(__self__, "host", host)
        pulumi.set(__self__, "path", path)
        pulumi.set(__self__, "port", port)
        pulumi.set(__self__, "protocol", protocol)
        pulumi.set(__self__, "target_id", target_id)
        pulumi.set(__self__, "target_type", target_type)

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> _builtins.bool:
        """
        Whether this target is enabled
        """
        return pulumi.get(self, "enabled")

    @_builtins.property
    @pulumi.getter
    def host(self) -> _builtins.str:
        """
        Backend IP or domain for this target
        """
        return pulumi.get(self, "host")

    @_builtins.property
    @pulumi.getter
    def path(self) -> _builtins.str:
        """
        URL path prefix for this target
        """
        return pulumi.get(self, "path")

    @_builtins.property
    @pulumi.getter
    def port(self) -> _builtins.float:
        """
        Backend port for this target
        """
        return pulumi.get(self, "port")

    @_builtins.property
    @pulumi.getter
    def protocol(self) -> _builtins.str:
        """
        Protocol to use when connecting to the backend (http, https)
        """
        return pulumi.get(self, "protocol")

    @_builtins.property
    @pulumi.getter(name="targetId")
    def target_id(self) -> _builtins.str:
        """
        Target ID (resource or peer ID)
        """
        return pulumi.get(self, "target_id")

    @_builtins.property
    @pulumi.getter(name="targetType")
    def target_type(self) -> _builtins.str:
        """
        Target type (peer, host, domain, subnet)
        """
        return pulumi.get(self, "target_type")


