# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['PeerArgs', 'Peer']

@pulumi.input_type
class PeerArgs:
    def __init__(__self__, *,
                 peer_id: pulumi.Input[_builtins.str],
                 approval_required: Optional[pulumi.Input[_builtins.bool]] = None,
                 inactivity_expiration_enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 login_expiration_enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 ssh_enabled: Optional[pulumi.Input[_builtins.bool]] = None):
        """
        The set of arguments for constructing a Peer resource.

        :param pulumi.Input[_builtins.str] peer_id: Peer ID
        :param pulumi.Input[_builtins.bool] approval_required: Indicates whether peer needs approval
        :param pulumi.Input[_builtins.bool] inactivity_expiration_enabled: Enable inactivity expiration for peer
        :param pulumi.Input[_builtins.bool] login_expiration_enabled: Indicates whether login expiration is enabled for peer
        :param pulumi.Input[_builtins.str] name: Peer Name
        :param pulumi.Input[_builtins.bool] ssh_enabled: Enable SSH to Peer
        """
        pulumi.set(__self__, "peer_id", peer_id)
        if approval_required is not None:
            pulumi.set(__self__, "approval_required", approval_required)
        if inactivity_expiration_enabled is not None:
            pulumi.set(__self__, "inactivity_expiration_enabled", inactivity_expiration_enabled)
        if login_expiration_enabled is not None:
            pulumi.set(__self__, "login_expiration_enabled", login_expiration_enabled)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if ssh_enabled is not None:
            pulumi.set(__self__, "ssh_enabled", ssh_enabled)

    @_builtins.property
    @pulumi.getter(name="peerId")
    def peer_id(self) -> pulumi.Input[_builtins.str]:
        """
        Peer ID
        """
        return pulumi.get(self, "peer_id")

    @peer_id.setter
    def peer_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "peer_id", value)

    @_builtins.property
    @pulumi.getter(name="approvalRequired")
    def approval_required(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Indicates whether peer needs approval
        """
        return pulumi.get(self, "approval_required")

    @approval_required.setter
    def approval_required(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "approval_required", value)

    @_builtins.property
    @pulumi.getter(name="inactivityExpirationEnabled")
    def inactivity_expiration_enabled(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Enable inactivity expiration for peer
        """
        return pulumi.get(self, "inactivity_expiration_enabled")

    @inactivity_expiration_enabled.setter
    def inactivity_expiration_enabled(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "inactivity_expiration_enabled", value)

    @_builtins.property
    @pulumi.getter(name="loginExpirationEnabled")
    def login_expiration_enabled(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Indicates whether login expiration is enabled for peer
        """
        return pulumi.get(self, "login_expiration_enabled")

    @login_expiration_enabled.setter
    def login_expiration_enabled(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "login_expiration_enabled", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Peer Name
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="sshEnabled")
    def ssh_enabled(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Enable SSH to Peer
        """
        return pulumi.get(self, "ssh_enabled")

    @ssh_enabled.setter
    def ssh_enabled(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "ssh_enabled", value)


@pulumi.input_type
class _PeerState:
    def __init__(__self__, *,
                 approval_required: Optional[pulumi.Input[_builtins.bool]] = None,
                 city_name: Optional[pulumi.Input[_builtins.str]] = None,
                 connected: Optional[pulumi.Input[_builtins.bool]] = None,
                 connection_ip: Optional[pulumi.Input[_builtins.str]] = None,
                 country_code: Optional[pulumi.Input[_builtins.str]] = None,
                 dns_label: Optional[pulumi.Input[_builtins.str]] = None,
                 extra_dns_labels: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 geoname_id: Optional[pulumi.Input[_builtins.float]] = None,
                 groups: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 hostname: Optional[pulumi.Input[_builtins.str]] = None,
                 inactivity_expiration_enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 ip: Optional[pulumi.Input[_builtins.str]] = None,
                 kernel_version: Optional[pulumi.Input[_builtins.str]] = None,
                 last_login: Optional[pulumi.Input[_builtins.str]] = None,
                 last_seen: Optional[pulumi.Input[_builtins.str]] = None,
                 login_expiration_enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 login_expired: Optional[pulumi.Input[_builtins.bool]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 os: Optional[pulumi.Input[_builtins.str]] = None,
                 peer_id: Optional[pulumi.Input[_builtins.str]] = None,
                 serial_number: Optional[pulumi.Input[_builtins.str]] = None,
                 ssh_enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 ui_version: Optional[pulumi.Input[_builtins.str]] = None,
                 user_id: Optional[pulumi.Input[_builtins.str]] = None,
                 version: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering Peer resources.

        :param pulumi.Input[_builtins.bool] approval_required: Indicates whether peer needs approval
        :param pulumi.Input[_builtins.str] city_name: Peer city name
        :param pulumi.Input[_builtins.bool] connected: Peer Connection Status
        :param pulumi.Input[_builtins.str] connection_ip: Peer Public IP
        :param pulumi.Input[_builtins.str] country_code: Peer country code
        :param pulumi.Input[_builtins.str] dns_label: Peer DNS Label
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] extra_dns_labels: Peer extra DNS Labels
        :param pulumi.Input[_builtins.float] geoname_id: Peer Location ID
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] groups: Peer groups
        :param pulumi.Input[_builtins.str] hostname: Peer's HOSTNAME
        :param pulumi.Input[_builtins.bool] inactivity_expiration_enabled: Enable inactivity expiration for peer
        :param pulumi.Input[_builtins.str] ip: Peer  IP
        :param pulumi.Input[_builtins.str] kernel_version: Peer Kernel Version
        :param pulumi.Input[_builtins.str] last_login: Time of peer last login
        :param pulumi.Input[_builtins.str] last_seen: Peer Last Seen timedate
        :param pulumi.Input[_builtins.bool] login_expiration_enabled: Indicates whether login expiration is enabled for peer
        :param pulumi.Input[_builtins.bool] login_expired: Indicates whether peer login is expired
        :param pulumi.Input[_builtins.str] name: Peer Name
        :param pulumi.Input[_builtins.str] os: Peer OS
        :param pulumi.Input[_builtins.str] peer_id: Peer ID
        :param pulumi.Input[_builtins.str] serial_number: Peer device serial number
        :param pulumi.Input[_builtins.bool] ssh_enabled: Enable SSH to Peer
        :param pulumi.Input[_builtins.str] ui_version: Peer  UI Version
        :param pulumi.Input[_builtins.str] user_id: User ID of peer
        :param pulumi.Input[_builtins.str] version: Peer  Version
        """
        if approval_required is not None:
            pulumi.set(__self__, "approval_required", approval_required)
        if city_name is not None:
            pulumi.set(__self__, "city_name", city_name)
        if connected is not None:
            pulumi.set(__self__, "connected", connected)
        if connection_ip is not None:
            pulumi.set(__self__, "connection_ip", connection_ip)
        if country_code is not None:
            pulumi.set(__self__, "country_code", country_code)
        if dns_label is not None:
            pulumi.set(__self__, "dns_label", dns_label)
        if extra_dns_labels is not None:
            pulumi.set(__self__, "extra_dns_labels", extra_dns_labels)
        if geoname_id is not None:
            pulumi.set(__self__, "geoname_id", geoname_id)
        if groups is not None:
            pulumi.set(__self__, "groups", groups)
        if hostname is not None:
            pulumi.set(__self__, "hostname", hostname)
        if inactivity_expiration_enabled is not None:
            pulumi.set(__self__, "inactivity_expiration_enabled", inactivity_expiration_enabled)
        if ip is not None:
            pulumi.set(__self__, "ip", ip)
        if kernel_version is not None:
            pulumi.set(__self__, "kernel_version", kernel_version)
        if last_login is not None:
            pulumi.set(__self__, "last_login", last_login)
        if last_seen is not None:
            pulumi.set(__self__, "last_seen", last_seen)
        if login_expiration_enabled is not None:
            pulumi.set(__self__, "login_expiration_enabled", login_expiration_enabled)
        if login_expired is not None:
            pulumi.set(__self__, "login_expired", login_expired)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if os is not None:
            pulumi.set(__self__, "os", os)
        if peer_id is not None:
            pulumi.set(__self__, "peer_id", peer_id)
        if serial_number is not None:
            pulumi.set(__self__, "serial_number", serial_number)
        if ssh_enabled is not None:
            pulumi.set(__self__, "ssh_enabled", ssh_enabled)
        if ui_version is not None:
            pulumi.set(__self__, "ui_version", ui_version)
        if user_id is not None:
            pulumi.set(__self__, "user_id", user_id)
        if version is not None:
            pulumi.set(__self__, "version", version)

    @_builtins.property
    @pulumi.getter(name="approvalRequired")
    def approval_required(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Indicates whether peer needs approval
        """
        return pulumi.get(self, "approval_required")

    @approval_required.setter
    def approval_required(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "approval_required", value)

    @_builtins.property
    @pulumi.getter(name="cityName")
    def city_name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Peer city name
        """
        return pulumi.get(self, "city_name")

    @city_name.setter
    def city_name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "city_name", value)

    @_builtins.property
    @pulumi.getter
    def connected(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Peer Connection Status
        """
        return pulumi.get(self, "connected")

    @connected.setter
    def connected(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "connected", value)

    @_builtins.property
    @pulumi.getter(name="connectionIp")
    def connection_ip(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Peer Public IP
        """
        return pulumi.get(self, "connection_ip")

    @connection_ip.setter
    def connection_ip(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "connection_ip", value)

    @_builtins.property
    @pulumi.getter(name="countryCode")
    def country_code(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Peer country code
        """
        return pulumi.get(self, "country_code")

    @country_code.setter
    def country_code(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "country_code", value)

    @_builtins.property
    @pulumi.getter(name="dnsLabel")
    def dns_label(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Peer DNS Label
        """
        return pulumi.get(self, "dns_label")

    @dns_label.setter
    def dns_label(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "dns_label", value)

    @_builtins.property
    @pulumi.getter(name="extraDnsLabels")
    def extra_dns_labels(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Peer extra DNS Labels
        """
        return pulumi.get(self, "extra_dns_labels")

    @extra_dns_labels.setter
    def extra_dns_labels(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "extra_dns_labels", value)

    @_builtins.property
    @pulumi.getter(name="geonameId")
    def geoname_id(self) -> Optional[pulumi.Input[_builtins.float]]:
        """
        Peer Location ID
        """
        return pulumi.get(self, "geoname_id")

    @geoname_id.setter
    def geoname_id(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "geoname_id", value)

    @_builtins.property
    @pulumi.getter
    def groups(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Peer groups
        """
        return pulumi.get(self, "groups")

    @groups.setter
    def groups(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "groups", value)

    @_builtins.property
    @pulumi.getter
    def hostname(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Peer's HOSTNAME
        """
        return pulumi.get(self, "hostname")

    @hostname.setter
    def hostname(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "hostname", value)

    @_builtins.property
    @pulumi.getter(name="inactivityExpirationEnabled")
    def inactivity_expiration_enabled(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Enable inactivity expiration for peer
        """
        return pulumi.get(self, "inactivity_expiration_enabled")

    @inactivity_expiration_enabled.setter
    def inactivity_expiration_enabled(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "inactivity_expiration_enabled", value)

    @_builtins.property
    @pulumi.getter
    def ip(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Peer  IP
        """
        return pulumi.get(self, "ip")

    @ip.setter
    def ip(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "ip", value)

    @_builtins.property
    @pulumi.getter(name="kernelVersion")
    def kernel_version(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Peer Kernel Version
        """
        return pulumi.get(self, "kernel_version")

    @kernel_version.setter
    def kernel_version(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "kernel_version", value)

    @_builtins.property
    @pulumi.getter(name="lastLogin")
    def last_login(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Time of peer last login
        """
        return pulumi.get(self, "last_login")

    @last_login.setter
    def last_login(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "last_login", value)

    @_builtins.property
    @pulumi.getter(name="lastSeen")
    def last_seen(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Peer Last Seen timedate
        """
        return pulumi.get(self, "last_seen")

    @last_seen.setter
    def last_seen(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "last_seen", value)

    @_builtins.property
    @pulumi.getter(name="loginExpirationEnabled")
    def login_expiration_enabled(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Indicates whether login expiration is enabled for peer
        """
        return pulumi.get(self, "login_expiration_enabled")

    @login_expiration_enabled.setter
    def login_expiration_enabled(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "login_expiration_enabled", value)

    @_builtins.property
    @pulumi.getter(name="loginExpired")
    def login_expired(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Indicates whether peer login is expired
        """
        return pulumi.get(self, "login_expired")

    @login_expired.setter
    def login_expired(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "login_expired", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Peer Name
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def os(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Peer OS
        """
        return pulumi.get(self, "os")

    @os.setter
    def os(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "os", value)

    @_builtins.property
    @pulumi.getter(name="peerId")
    def peer_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Peer ID
        """
        return pulumi.get(self, "peer_id")

    @peer_id.setter
    def peer_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "peer_id", value)

    @_builtins.property
    @pulumi.getter(name="serialNumber")
    def serial_number(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Peer device serial number
        """
        return pulumi.get(self, "serial_number")

    @serial_number.setter
    def serial_number(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "serial_number", value)

    @_builtins.property
    @pulumi.getter(name="sshEnabled")
    def ssh_enabled(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Enable SSH to Peer
        """
        return pulumi.get(self, "ssh_enabled")

    @ssh_enabled.setter
    def ssh_enabled(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "ssh_enabled", value)

    @_builtins.property
    @pulumi.getter(name="uiVersion")
    def ui_version(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Peer  UI Version
        """
        return pulumi.get(self, "ui_version")

    @ui_version.setter
    def ui_version(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "ui_version", value)

    @_builtins.property
    @pulumi.getter(name="userId")
    def user_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        User ID of peer
        """
        return pulumi.get(self, "user_id")

    @user_id.setter
    def user_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "user_id", value)

    @_builtins.property
    @pulumi.getter
    def version(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Peer  Version
        """
        return pulumi.get(self, "version")

    @version.setter
    def version(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "version", value)


@pulumi.type_token("netbird:index/peer:Peer")
class Peer(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 approval_required: Optional[pulumi.Input[_builtins.bool]] = None,
                 inactivity_expiration_enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 login_expiration_enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 peer_id: Optional[pulumi.Input[_builtins.str]] = None,
                 ssh_enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 __props__=None):
        """
        Create a Peer resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] approval_required: Indicates whether peer needs approval
        :param pulumi.Input[_builtins.bool] inactivity_expiration_enabled: Enable inactivity expiration for peer
        :param pulumi.Input[_builtins.bool] login_expiration_enabled: Indicates whether login expiration is enabled for peer
        :param pulumi.Input[_builtins.str] name: Peer Name
        :param pulumi.Input[_builtins.str] peer_id: Peer ID
        :param pulumi.Input[_builtins.bool] ssh_enabled: Enable SSH to Peer
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: PeerArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a Peer resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param PeerArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(PeerArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 approval_required: Optional[pulumi.Input[_builtins.bool]] = None,
                 inactivity_expiration_enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 login_expiration_enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 peer_id: Optional[pulumi.Input[_builtins.str]] = None,
                 ssh_enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = PeerArgs.__new__(PeerArgs)

            __props__.__dict__["approval_required"] = approval_required
            __props__.__dict__["inactivity_expiration_enabled"] = inactivity_expiration_enabled
            __props__.__dict__["login_expiration_enabled"] = login_expiration_enabled
            __props__.__dict__["name"] = name
            if peer_id is None and not opts.urn:
                raise TypeError("Missing required property 'peer_id'")
            __props__.__dict__["peer_id"] = peer_id
            __props__.__dict__["ssh_enabled"] = ssh_enabled
            __props__.__dict__["city_name"] = None
            __props__.__dict__["connected"] = None
            __props__.__dict__["connection_ip"] = None
            __props__.__dict__["country_code"] = None
            __props__.__dict__["dns_label"] = None
            __props__.__dict__["extra_dns_labels"] = None
            __props__.__dict__["geoname_id"] = None
            __props__.__dict__["groups"] = None
            __props__.__dict__["hostname"] = None
            __props__.__dict__["ip"] = None
            __props__.__dict__["kernel_version"] = None
            __props__.__dict__["last_login"] = None
            __props__.__dict__["last_seen"] = None
            __props__.__dict__["login_expired"] = None
            __props__.__dict__["os"] = None
            __props__.__dict__["serial_number"] = None
            __props__.__dict__["ui_version"] = None
            __props__.__dict__["user_id"] = None
            __props__.__dict__["version"] = None
        super(Peer, __self__).__init__(
            'netbird:index/peer:Peer',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            approval_required: Optional[pulumi.Input[_builtins.bool]] = None,
            city_name: Optional[pulumi.Input[_builtins.str]] = None,
            connected: Optional[pulumi.Input[_builtins.bool]] = None,
            connection_ip: Optional[pulumi.Input[_builtins.str]] = None,
            country_code: Optional[pulumi.Input[_builtins.str]] = None,
            dns_label: Optional[pulumi.Input[_builtins.str]] = None,
            extra_dns_labels: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            geoname_id: Optional[pulumi.Input[_builtins.float]] = None,
            groups: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            hostname: Optional[pulumi.Input[_builtins.str]] = None,
            inactivity_expiration_enabled: Optional[pulumi.Input[_builtins.bool]] = None,
            ip: Optional[pulumi.Input[_builtins.str]] = None,
            kernel_version: Optional[pulumi.Input[_builtins.str]] = None,
            last_login: Optional[pulumi.Input[_builtins.str]] = None,
            last_seen: Optional[pulumi.Input[_builtins.str]] = None,
            login_expiration_enabled: Optional[pulumi.Input[_builtins.bool]] = None,
            login_expired: Optional[pulumi.Input[_builtins.bool]] = None,
            name: Optional[pulumi.Input[_builtins.str]] = None,
            os: Optional[pulumi.Input[_builtins.str]] = None,
            peer_id: Optional[pulumi.Input[_builtins.str]] = None,
            serial_number: Optional[pulumi.Input[_builtins.str]] = None,
            ssh_enabled: Optional[pulumi.Input[_builtins.bool]] = None,
            ui_version: Optional[pulumi.Input[_builtins.str]] = None,
            user_id: Optional[pulumi.Input[_builtins.str]] = None,
            version: Optional[pulumi.Input[_builtins.str]] = None) -> 'Peer':
        """
        Get an existing Peer resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] approval_required: Indicates whether peer needs approval
        :param pulumi.Input[_builtins.str] city_name: Peer city name
        :param pulumi.Input[_builtins.bool] connected: Peer Connection Status
        :param pulumi.Input[_builtins.str] connection_ip: Peer Public IP
        :param pulumi.Input[_builtins.str] country_code: Peer country code
        :param pulumi.Input[_builtins.str] dns_label: Peer DNS Label
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] extra_dns_labels: Peer extra DNS Labels
        :param pulumi.Input[_builtins.float] geoname_id: Peer Location ID
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] groups: Peer groups
        :param pulumi.Input[_builtins.str] hostname: Peer's HOSTNAME
        :param pulumi.Input[_builtins.bool] inactivity_expiration_enabled: Enable inactivity expiration for peer
        :param pulumi.Input[_builtins.str] ip: Peer  IP
        :param pulumi.Input[_builtins.str] kernel_version: Peer Kernel Version
        :param pulumi.Input[_builtins.str] last_login: Time of peer last login
        :param pulumi.Input[_builtins.str] last_seen: Peer Last Seen timedate
        :param pulumi.Input[_builtins.bool] login_expiration_enabled: Indicates whether login expiration is enabled for peer
        :param pulumi.Input[_builtins.bool] login_expired: Indicates whether peer login is expired
        :param pulumi.Input[_builtins.str] name: Peer Name
        :param pulumi.Input[_builtins.str] os: Peer OS
        :param pulumi.Input[_builtins.str] peer_id: Peer ID
        :param pulumi.Input[_builtins.str] serial_number: Peer device serial number
        :param pulumi.Input[_builtins.bool] ssh_enabled: Enable SSH to Peer
        :param pulumi.Input[_builtins.str] ui_version: Peer  UI Version
        :param pulumi.Input[_builtins.str] user_id: User ID of peer
        :param pulumi.Input[_builtins.str] version: Peer  Version
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _PeerState.__new__(_PeerState)

        __props__.__dict__["approval_required"] = approval_required
        __props__.__dict__["city_name"] = city_name
        __props__.__dict__["connected"] = connected
        __props__.__dict__["connection_ip"] = connection_ip
        __props__.__dict__["country_code"] = country_code
        __props__.__dict__["dns_label"] = dns_label
        __props__.__dict__["extra_dns_labels"] = extra_dns_labels
        __props__.__dict__["geoname_id"] = geoname_id
        __props__.__dict__["groups"] = groups
        __props__.__dict__["hostname"] = hostname
        __props__.__dict__["inactivity_expiration_enabled"] = inactivity_expiration_enabled
        __props__.__dict__["ip"] = ip
        __props__.__dict__["kernel_version"] = kernel_version
        __props__.__dict__["last_login"] = last_login
        __props__.__dict__["last_seen"] = last_seen
        __props__.__dict__["login_expiration_enabled"] = login_expiration_enabled
        __props__.__dict__["login_expired"] = login_expired
        __props__.__dict__["name"] = name
        __props__.__dict__["os"] = os
        __props__.__dict__["peer_id"] = peer_id
        __props__.__dict__["serial_number"] = serial_number
        __props__.__dict__["ssh_enabled"] = ssh_enabled
        __props__.__dict__["ui_version"] = ui_version
        __props__.__dict__["user_id"] = user_id
        __props__.__dict__["version"] = version
        return Peer(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="approvalRequired")
    def approval_required(self) -> pulumi.Output[_builtins.bool]:
        """
        Indicates whether peer needs approval
        """
        return pulumi.get(self, "approval_required")

    @_builtins.property
    @pulumi.getter(name="cityName")
    def city_name(self) -> pulumi.Output[_builtins.str]:
        """
        Peer city name
        """
        return pulumi.get(self, "city_name")

    @_builtins.property
    @pulumi.getter
    def connected(self) -> pulumi.Output[_builtins.bool]:
        """
        Peer Connection Status
        """
        return pulumi.get(self, "connected")

    @_builtins.property
    @pulumi.getter(name="connectionIp")
    def connection_ip(self) -> pulumi.Output[_builtins.str]:
        """
        Peer Public IP
        """
        return pulumi.get(self, "connection_ip")

    @_builtins.property
    @pulumi.getter(name="countryCode")
    def country_code(self) -> pulumi.Output[_builtins.str]:
        """
        Peer country code
        """
        return pulumi.get(self, "country_code")

    @_builtins.property
    @pulumi.getter(name="dnsLabel")
    def dns_label(self) -> pulumi.Output[_builtins.str]:
        """
        Peer DNS Label
        """
        return pulumi.get(self, "dns_label")

    @_builtins.property
    @pulumi.getter(name="extraDnsLabels")
    def extra_dns_labels(self) -> pulumi.Output[Sequence[_builtins.str]]:
        """
        Peer extra DNS Labels
        """
        return pulumi.get(self, "extra_dns_labels")

    @_builtins.property
    @pulumi.getter(name="geonameId")
    def geoname_id(self) -> pulumi.Output[_builtins.float]:
        """
        Peer Location ID
        """
        return pulumi.get(self, "geoname_id")

    @_builtins.property
    @pulumi.getter
    def groups(self) -> pulumi.Output[Sequence[_builtins.str]]:
        """
        Peer groups
        """
        return pulumi.get(self, "groups")

    @_builtins.property
    @pulumi.getter
    def hostname(self) -> pulumi.Output[_builtins.str]:
        """
        Peer's HOSTNAME
        """
        return pulumi.get(self, "hostname")

    @_builtins.property
    @pulumi.getter(name="inactivityExpirationEnabled")
    def inactivity_expiration_enabled(self) -> pulumi.Output[_builtins.bool]:
        """
        Enable inactivity expiration for peer
        """
        return pulumi.get(self, "inactivity_expiration_enabled")

    @_builtins.property
    @pulumi.getter
    def ip(self) -> pulumi.Output[_builtins.str]:
        """
        Peer  IP
        """
        return pulumi.get(self, "ip")

    @_builtins.property
    @pulumi.getter(name="kernelVersion")
    def kernel_version(self) -> pulumi.Output[_builtins.str]:
        """
        Peer Kernel Version
        """
        return pulumi.get(self, "kernel_version")

    @_builtins.property
    @pulumi.getter(name="lastLogin")
    def last_login(self) -> pulumi.Output[_builtins.str]:
        """
        Time of peer last login
        """
        return pulumi.get(self, "last_login")

    @_builtins.property
    @pulumi.getter(name="lastSeen")
    def last_seen(self) -> pulumi.Output[_builtins.str]:
        """
        Peer Last Seen timedate
        """
        return pulumi.get(self, "last_seen")

    @_builtins.property
    @pulumi.getter(name="loginExpirationEnabled")
    def login_expiration_enabled(self) -> pulumi.Output[_builtins.bool]:
        """
        Indicates whether login expiration is enabled for peer
        """
        return pulumi.get(self, "login_expiration_enabled")

    @_builtins.property
    @pulumi.getter(name="loginExpired")
    def login_expired(self) -> pulumi.Output[_builtins.bool]:
        """
        Indicates whether peer login is expired
        """
        return pulumi.get(self, "login_expired")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Peer Name
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def os(self) -> pulumi.Output[_builtins.str]:
        """
        Peer OS
        """
        return pulumi.get(self, "os")

    @_builtins.property
    @pulumi.getter(name="peerId")
    def peer_id(self) -> pulumi.Output[_builtins.str]:
        """
        Peer ID
        """
        return pulumi.get(self, "peer_id")

    @_builtins.property
    @pulumi.getter(name="serialNumber")
    def serial_number(self) -> pulumi.Output[_builtins.str]:
        """
        Peer device serial number
        """
        return pulumi.get(self, "serial_number")

    @_builtins.property
    @pulumi.getter(name="sshEnabled")
    def ssh_enabled(self) -> pulumi.Output[_builtins.bool]:
        """
        Enable SSH to Peer
        """
        return pulumi.get(self, "ssh_enabled")

    @_builtins.property
    @pulumi.getter(name="uiVersion")
    def ui_version(self) -> pulumi.Output[_builtins.str]:
        """
        Peer  UI Version
        """
        return pulumi.get(self, "ui_version")

    @_builtins.property
    @pulumi.getter(name="userId")
    def user_id(self) -> pulumi.Output[_builtins.str]:
        """
        User ID of peer
        """
        return pulumi.get(self, "user_id")

    @_builtins.property
    @pulumi.getter
    def version(self) -> pulumi.Output[_builtins.str]:
        """
        Peer  Version
        """
        return pulumi.get(self, "version")

