# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['PostureCheckArgs', 'PostureCheck']

@pulumi.input_type
class PostureCheckArgs:
    def __init__(__self__, *,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 geo_location_check: Optional[pulumi.Input['PostureCheckGeoLocationCheckArgs']] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 netbird_version_check: Optional[pulumi.Input['PostureCheckNetbirdVersionCheckArgs']] = None,
                 os_version_check: Optional[pulumi.Input['PostureCheckOsVersionCheckArgs']] = None,
                 peer_network_range_check: Optional[pulumi.Input['PostureCheckPeerNetworkRangeCheckArgs']] = None,
                 process_checks: Optional[pulumi.Input[Sequence[pulumi.Input['PostureCheckProcessCheckArgs']]]] = None):
        """
        The set of arguments for constructing a PostureCheck resource.

        :param pulumi.Input[_builtins.str] description: PostureCheck description
        :param pulumi.Input[_builtins.str] name: PostureCheck Name
        """
        if description is not None:
            pulumi.set(__self__, "description", description)
        if geo_location_check is not None:
            pulumi.set(__self__, "geo_location_check", geo_location_check)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if netbird_version_check is not None:
            pulumi.set(__self__, "netbird_version_check", netbird_version_check)
        if os_version_check is not None:
            pulumi.set(__self__, "os_version_check", os_version_check)
        if peer_network_range_check is not None:
            pulumi.set(__self__, "peer_network_range_check", peer_network_range_check)
        if process_checks is not None:
            pulumi.set(__self__, "process_checks", process_checks)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        PostureCheck description
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="geoLocationCheck")
    def geo_location_check(self) -> Optional[pulumi.Input['PostureCheckGeoLocationCheckArgs']]:
        return pulumi.get(self, "geo_location_check")

    @geo_location_check.setter
    def geo_location_check(self, value: Optional[pulumi.Input['PostureCheckGeoLocationCheckArgs']]):
        pulumi.set(self, "geo_location_check", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        PostureCheck Name
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="netbirdVersionCheck")
    def netbird_version_check(self) -> Optional[pulumi.Input['PostureCheckNetbirdVersionCheckArgs']]:
        return pulumi.get(self, "netbird_version_check")

    @netbird_version_check.setter
    def netbird_version_check(self, value: Optional[pulumi.Input['PostureCheckNetbirdVersionCheckArgs']]):
        pulumi.set(self, "netbird_version_check", value)

    @_builtins.property
    @pulumi.getter(name="osVersionCheck")
    def os_version_check(self) -> Optional[pulumi.Input['PostureCheckOsVersionCheckArgs']]:
        return pulumi.get(self, "os_version_check")

    @os_version_check.setter
    def os_version_check(self, value: Optional[pulumi.Input['PostureCheckOsVersionCheckArgs']]):
        pulumi.set(self, "os_version_check", value)

    @_builtins.property
    @pulumi.getter(name="peerNetworkRangeCheck")
    def peer_network_range_check(self) -> Optional[pulumi.Input['PostureCheckPeerNetworkRangeCheckArgs']]:
        return pulumi.get(self, "peer_network_range_check")

    @peer_network_range_check.setter
    def peer_network_range_check(self, value: Optional[pulumi.Input['PostureCheckPeerNetworkRangeCheckArgs']]):
        pulumi.set(self, "peer_network_range_check", value)

    @_builtins.property
    @pulumi.getter(name="processChecks")
    def process_checks(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['PostureCheckProcessCheckArgs']]]]:
        return pulumi.get(self, "process_checks")

    @process_checks.setter
    def process_checks(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['PostureCheckProcessCheckArgs']]]]):
        pulumi.set(self, "process_checks", value)


@pulumi.input_type
class _PostureCheckState:
    def __init__(__self__, *,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 geo_location_check: Optional[pulumi.Input['PostureCheckGeoLocationCheckArgs']] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 netbird_version_check: Optional[pulumi.Input['PostureCheckNetbirdVersionCheckArgs']] = None,
                 os_version_check: Optional[pulumi.Input['PostureCheckOsVersionCheckArgs']] = None,
                 peer_network_range_check: Optional[pulumi.Input['PostureCheckPeerNetworkRangeCheckArgs']] = None,
                 process_checks: Optional[pulumi.Input[Sequence[pulumi.Input['PostureCheckProcessCheckArgs']]]] = None):
        """
        Input properties used for looking up and filtering PostureCheck resources.

        :param pulumi.Input[_builtins.str] description: PostureCheck description
        :param pulumi.Input[_builtins.str] name: PostureCheck Name
        """
        if description is not None:
            pulumi.set(__self__, "description", description)
        if geo_location_check is not None:
            pulumi.set(__self__, "geo_location_check", geo_location_check)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if netbird_version_check is not None:
            pulumi.set(__self__, "netbird_version_check", netbird_version_check)
        if os_version_check is not None:
            pulumi.set(__self__, "os_version_check", os_version_check)
        if peer_network_range_check is not None:
            pulumi.set(__self__, "peer_network_range_check", peer_network_range_check)
        if process_checks is not None:
            pulumi.set(__self__, "process_checks", process_checks)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        PostureCheck description
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="geoLocationCheck")
    def geo_location_check(self) -> Optional[pulumi.Input['PostureCheckGeoLocationCheckArgs']]:
        return pulumi.get(self, "geo_location_check")

    @geo_location_check.setter
    def geo_location_check(self, value: Optional[pulumi.Input['PostureCheckGeoLocationCheckArgs']]):
        pulumi.set(self, "geo_location_check", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        PostureCheck Name
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="netbirdVersionCheck")
    def netbird_version_check(self) -> Optional[pulumi.Input['PostureCheckNetbirdVersionCheckArgs']]:
        return pulumi.get(self, "netbird_version_check")

    @netbird_version_check.setter
    def netbird_version_check(self, value: Optional[pulumi.Input['PostureCheckNetbirdVersionCheckArgs']]):
        pulumi.set(self, "netbird_version_check", value)

    @_builtins.property
    @pulumi.getter(name="osVersionCheck")
    def os_version_check(self) -> Optional[pulumi.Input['PostureCheckOsVersionCheckArgs']]:
        return pulumi.get(self, "os_version_check")

    @os_version_check.setter
    def os_version_check(self, value: Optional[pulumi.Input['PostureCheckOsVersionCheckArgs']]):
        pulumi.set(self, "os_version_check", value)

    @_builtins.property
    @pulumi.getter(name="peerNetworkRangeCheck")
    def peer_network_range_check(self) -> Optional[pulumi.Input['PostureCheckPeerNetworkRangeCheckArgs']]:
        return pulumi.get(self, "peer_network_range_check")

    @peer_network_range_check.setter
    def peer_network_range_check(self, value: Optional[pulumi.Input['PostureCheckPeerNetworkRangeCheckArgs']]):
        pulumi.set(self, "peer_network_range_check", value)

    @_builtins.property
    @pulumi.getter(name="processChecks")
    def process_checks(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['PostureCheckProcessCheckArgs']]]]:
        return pulumi.get(self, "process_checks")

    @process_checks.setter
    def process_checks(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['PostureCheckProcessCheckArgs']]]]):
        pulumi.set(self, "process_checks", value)


@pulumi.type_token("netbird:index/postureCheck:PostureCheck")
class PostureCheck(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 geo_location_check: Optional[pulumi.Input[Union['PostureCheckGeoLocationCheckArgs', 'PostureCheckGeoLocationCheckArgsDict']]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 netbird_version_check: Optional[pulumi.Input[Union['PostureCheckNetbirdVersionCheckArgs', 'PostureCheckNetbirdVersionCheckArgsDict']]] = None,
                 os_version_check: Optional[pulumi.Input[Union['PostureCheckOsVersionCheckArgs', 'PostureCheckOsVersionCheckArgsDict']]] = None,
                 peer_network_range_check: Optional[pulumi.Input[Union['PostureCheckPeerNetworkRangeCheckArgs', 'PostureCheckPeerNetworkRangeCheckArgsDict']]] = None,
                 process_checks: Optional[pulumi.Input[Sequence[pulumi.Input[Union['PostureCheckProcessCheckArgs', 'PostureCheckProcessCheckArgsDict']]]]] = None,
                 __props__=None):
        """
        Create a PostureCheck resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] description: PostureCheck description
        :param pulumi.Input[_builtins.str] name: PostureCheck Name
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[PostureCheckArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a PostureCheck resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param PostureCheckArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(PostureCheckArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 geo_location_check: Optional[pulumi.Input[Union['PostureCheckGeoLocationCheckArgs', 'PostureCheckGeoLocationCheckArgsDict']]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 netbird_version_check: Optional[pulumi.Input[Union['PostureCheckNetbirdVersionCheckArgs', 'PostureCheckNetbirdVersionCheckArgsDict']]] = None,
                 os_version_check: Optional[pulumi.Input[Union['PostureCheckOsVersionCheckArgs', 'PostureCheckOsVersionCheckArgsDict']]] = None,
                 peer_network_range_check: Optional[pulumi.Input[Union['PostureCheckPeerNetworkRangeCheckArgs', 'PostureCheckPeerNetworkRangeCheckArgsDict']]] = None,
                 process_checks: Optional[pulumi.Input[Sequence[pulumi.Input[Union['PostureCheckProcessCheckArgs', 'PostureCheckProcessCheckArgsDict']]]]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = PostureCheckArgs.__new__(PostureCheckArgs)

            __props__.__dict__["description"] = description
            __props__.__dict__["geo_location_check"] = geo_location_check
            __props__.__dict__["name"] = name
            __props__.__dict__["netbird_version_check"] = netbird_version_check
            __props__.__dict__["os_version_check"] = os_version_check
            __props__.__dict__["peer_network_range_check"] = peer_network_range_check
            __props__.__dict__["process_checks"] = process_checks
        super(PostureCheck, __self__).__init__(
            'netbird:index/postureCheck:PostureCheck',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            description: Optional[pulumi.Input[_builtins.str]] = None,
            geo_location_check: Optional[pulumi.Input[Union['PostureCheckGeoLocationCheckArgs', 'PostureCheckGeoLocationCheckArgsDict']]] = None,
            name: Optional[pulumi.Input[_builtins.str]] = None,
            netbird_version_check: Optional[pulumi.Input[Union['PostureCheckNetbirdVersionCheckArgs', 'PostureCheckNetbirdVersionCheckArgsDict']]] = None,
            os_version_check: Optional[pulumi.Input[Union['PostureCheckOsVersionCheckArgs', 'PostureCheckOsVersionCheckArgsDict']]] = None,
            peer_network_range_check: Optional[pulumi.Input[Union['PostureCheckPeerNetworkRangeCheckArgs', 'PostureCheckPeerNetworkRangeCheckArgsDict']]] = None,
            process_checks: Optional[pulumi.Input[Sequence[pulumi.Input[Union['PostureCheckProcessCheckArgs', 'PostureCheckProcessCheckArgsDict']]]]] = None) -> 'PostureCheck':
        """
        Get an existing PostureCheck resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] description: PostureCheck description
        :param pulumi.Input[_builtins.str] name: PostureCheck Name
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _PostureCheckState.__new__(_PostureCheckState)

        __props__.__dict__["description"] = description
        __props__.__dict__["geo_location_check"] = geo_location_check
        __props__.__dict__["name"] = name
        __props__.__dict__["netbird_version_check"] = netbird_version_check
        __props__.__dict__["os_version_check"] = os_version_check
        __props__.__dict__["peer_network_range_check"] = peer_network_range_check
        __props__.__dict__["process_checks"] = process_checks
        return PostureCheck(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        PostureCheck description
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter(name="geoLocationCheck")
    def geo_location_check(self) -> pulumi.Output[Optional['outputs.PostureCheckGeoLocationCheck']]:
        return pulumi.get(self, "geo_location_check")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        PostureCheck Name
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="netbirdVersionCheck")
    def netbird_version_check(self) -> pulumi.Output[Optional['outputs.PostureCheckNetbirdVersionCheck']]:
        return pulumi.get(self, "netbird_version_check")

    @_builtins.property
    @pulumi.getter(name="osVersionCheck")
    def os_version_check(self) -> pulumi.Output[Optional['outputs.PostureCheckOsVersionCheck']]:
        return pulumi.get(self, "os_version_check")

    @_builtins.property
    @pulumi.getter(name="peerNetworkRangeCheck")
    def peer_network_range_check(self) -> pulumi.Output[Optional['outputs.PostureCheckPeerNetworkRangeCheck']]:
        return pulumi.get(self, "peer_network_range_check")

    @_builtins.property
    @pulumi.getter(name="processChecks")
    def process_checks(self) -> pulumi.Output[Optional[Sequence['outputs.PostureCheckProcessCheck']]]:
        return pulumi.get(self, "process_checks")

