# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['ScimArgs', 'Scim']

@pulumi.input_type
class ScimArgs:
    def __init__(__self__, *,
                 provider_name: pulumi.Input[_builtins.str],
                 enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 group_prefixes: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 prefix: Optional[pulumi.Input[_builtins.str]] = None,
                 user_group_prefixes: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None):
        """
        The set of arguments for constructing a Scim resource.

        :param pulumi.Input[_builtins.str] provider_name: Name of the SCIM identity provider
        :param pulumi.Input[_builtins.bool] enabled: Indicates whether the integration is enabled
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] group_prefixes: List of<span pulumi-lang-nodejs=" startWith " pulumi-lang-dotnet=" StartWith " pulumi-lang-go=" startWith " pulumi-lang-python=" start_with " pulumi-lang-yaml=" startWith " pulumi-lang-java=" startWith "> start_with </span>string patterns for groups to sync
        :param pulumi.Input[_builtins.str] prefix: The connection prefix used for the SCIM provider.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] user_group_prefixes: List of<span pulumi-lang-nodejs=" startWith " pulumi-lang-dotnet=" StartWith " pulumi-lang-go=" startWith " pulumi-lang-python=" start_with " pulumi-lang-yaml=" startWith " pulumi-lang-java=" startWith "> start_with </span>string patterns for groups which users to sync
        """
        pulumi.set(__self__, "provider_name", provider_name)
        if enabled is not None:
            pulumi.set(__self__, "enabled", enabled)
        if group_prefixes is not None:
            pulumi.set(__self__, "group_prefixes", group_prefixes)
        if prefix is not None:
            pulumi.set(__self__, "prefix", prefix)
        if user_group_prefixes is not None:
            pulumi.set(__self__, "user_group_prefixes", user_group_prefixes)

    @_builtins.property
    @pulumi.getter(name="providerName")
    def provider_name(self) -> pulumi.Input[_builtins.str]:
        """
        Name of the SCIM identity provider
        """
        return pulumi.get(self, "provider_name")

    @provider_name.setter
    def provider_name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "provider_name", value)

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Indicates whether the integration is enabled
        """
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "enabled", value)

    @_builtins.property
    @pulumi.getter(name="groupPrefixes")
    def group_prefixes(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        List of<span pulumi-lang-nodejs=" startWith " pulumi-lang-dotnet=" StartWith " pulumi-lang-go=" startWith " pulumi-lang-python=" start_with " pulumi-lang-yaml=" startWith " pulumi-lang-java=" startWith "> start_with </span>string patterns for groups to sync
        """
        return pulumi.get(self, "group_prefixes")

    @group_prefixes.setter
    def group_prefixes(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "group_prefixes", value)

    @_builtins.property
    @pulumi.getter
    def prefix(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The connection prefix used for the SCIM provider.
        """
        return pulumi.get(self, "prefix")

    @prefix.setter
    def prefix(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "prefix", value)

    @_builtins.property
    @pulumi.getter(name="userGroupPrefixes")
    def user_group_prefixes(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        List of<span pulumi-lang-nodejs=" startWith " pulumi-lang-dotnet=" StartWith " pulumi-lang-go=" startWith " pulumi-lang-python=" start_with " pulumi-lang-yaml=" startWith " pulumi-lang-java=" startWith "> start_with </span>string patterns for groups which users to sync
        """
        return pulumi.get(self, "user_group_prefixes")

    @user_group_prefixes.setter
    def user_group_prefixes(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "user_group_prefixes", value)


@pulumi.input_type
class _ScimState:
    def __init__(__self__, *,
                 auth_token: Optional[pulumi.Input[_builtins.str]] = None,
                 enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 group_prefixes: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 last_synced_at: Optional[pulumi.Input[_builtins.str]] = None,
                 prefix: Optional[pulumi.Input[_builtins.str]] = None,
                 provider_name: Optional[pulumi.Input[_builtins.str]] = None,
                 user_group_prefixes: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None):
        """
        Input properties used for looking up and filtering Scim resources.

        :param pulumi.Input[_builtins.str] auth_token: SCIM API token (only available in full after creation)
        :param pulumi.Input[_builtins.bool] enabled: Indicates whether the integration is enabled
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] group_prefixes: List of<span pulumi-lang-nodejs=" startWith " pulumi-lang-dotnet=" StartWith " pulumi-lang-go=" startWith " pulumi-lang-python=" start_with " pulumi-lang-yaml=" startWith " pulumi-lang-java=" startWith "> start_with </span>string patterns for groups to sync
        :param pulumi.Input[_builtins.str] last_synced_at: Timestamp of when the integration was last synced
        :param pulumi.Input[_builtins.str] prefix: The connection prefix used for the SCIM provider.
        :param pulumi.Input[_builtins.str] provider_name: Name of the SCIM identity provider
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] user_group_prefixes: List of<span pulumi-lang-nodejs=" startWith " pulumi-lang-dotnet=" StartWith " pulumi-lang-go=" startWith " pulumi-lang-python=" start_with " pulumi-lang-yaml=" startWith " pulumi-lang-java=" startWith "> start_with </span>string patterns for groups which users to sync
        """
        if auth_token is not None:
            pulumi.set(__self__, "auth_token", auth_token)
        if enabled is not None:
            pulumi.set(__self__, "enabled", enabled)
        if group_prefixes is not None:
            pulumi.set(__self__, "group_prefixes", group_prefixes)
        if last_synced_at is not None:
            pulumi.set(__self__, "last_synced_at", last_synced_at)
        if prefix is not None:
            pulumi.set(__self__, "prefix", prefix)
        if provider_name is not None:
            pulumi.set(__self__, "provider_name", provider_name)
        if user_group_prefixes is not None:
            pulumi.set(__self__, "user_group_prefixes", user_group_prefixes)

    @_builtins.property
    @pulumi.getter(name="authToken")
    def auth_token(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        SCIM API token (only available in full after creation)
        """
        return pulumi.get(self, "auth_token")

    @auth_token.setter
    def auth_token(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "auth_token", value)

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Indicates whether the integration is enabled
        """
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "enabled", value)

    @_builtins.property
    @pulumi.getter(name="groupPrefixes")
    def group_prefixes(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        List of<span pulumi-lang-nodejs=" startWith " pulumi-lang-dotnet=" StartWith " pulumi-lang-go=" startWith " pulumi-lang-python=" start_with " pulumi-lang-yaml=" startWith " pulumi-lang-java=" startWith "> start_with </span>string patterns for groups to sync
        """
        return pulumi.get(self, "group_prefixes")

    @group_prefixes.setter
    def group_prefixes(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "group_prefixes", value)

    @_builtins.property
    @pulumi.getter(name="lastSyncedAt")
    def last_synced_at(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Timestamp of when the integration was last synced
        """
        return pulumi.get(self, "last_synced_at")

    @last_synced_at.setter
    def last_synced_at(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "last_synced_at", value)

    @_builtins.property
    @pulumi.getter
    def prefix(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The connection prefix used for the SCIM provider.
        """
        return pulumi.get(self, "prefix")

    @prefix.setter
    def prefix(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "prefix", value)

    @_builtins.property
    @pulumi.getter(name="providerName")
    def provider_name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Name of the SCIM identity provider
        """
        return pulumi.get(self, "provider_name")

    @provider_name.setter
    def provider_name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "provider_name", value)

    @_builtins.property
    @pulumi.getter(name="userGroupPrefixes")
    def user_group_prefixes(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        List of<span pulumi-lang-nodejs=" startWith " pulumi-lang-dotnet=" StartWith " pulumi-lang-go=" startWith " pulumi-lang-python=" start_with " pulumi-lang-yaml=" startWith " pulumi-lang-java=" startWith "> start_with </span>string patterns for groups which users to sync
        """
        return pulumi.get(self, "user_group_prefixes")

    @user_group_prefixes.setter
    def user_group_prefixes(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "user_group_prefixes", value)


@pulumi.type_token("netbird:index/scim:Scim")
class Scim(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 group_prefixes: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 prefix: Optional[pulumi.Input[_builtins.str]] = None,
                 provider_name: Optional[pulumi.Input[_builtins.str]] = None,
                 user_group_prefixes: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 __props__=None):
        """
        Create a Scim resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] enabled: Indicates whether the integration is enabled
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] group_prefixes: List of<span pulumi-lang-nodejs=" startWith " pulumi-lang-dotnet=" StartWith " pulumi-lang-go=" startWith " pulumi-lang-python=" start_with " pulumi-lang-yaml=" startWith " pulumi-lang-java=" startWith "> start_with </span>string patterns for groups to sync
        :param pulumi.Input[_builtins.str] prefix: The connection prefix used for the SCIM provider.
        :param pulumi.Input[_builtins.str] provider_name: Name of the SCIM identity provider
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] user_group_prefixes: List of<span pulumi-lang-nodejs=" startWith " pulumi-lang-dotnet=" StartWith " pulumi-lang-go=" startWith " pulumi-lang-python=" start_with " pulumi-lang-yaml=" startWith " pulumi-lang-java=" startWith "> start_with </span>string patterns for groups which users to sync
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ScimArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a Scim resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param ScimArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ScimArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 group_prefixes: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 prefix: Optional[pulumi.Input[_builtins.str]] = None,
                 provider_name: Optional[pulumi.Input[_builtins.str]] = None,
                 user_group_prefixes: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ScimArgs.__new__(ScimArgs)

            __props__.__dict__["enabled"] = enabled
            __props__.__dict__["group_prefixes"] = group_prefixes
            __props__.__dict__["prefix"] = prefix
            if provider_name is None and not opts.urn:
                raise TypeError("Missing required property 'provider_name'")
            __props__.__dict__["provider_name"] = provider_name
            __props__.__dict__["user_group_prefixes"] = user_group_prefixes
            __props__.__dict__["auth_token"] = None
            __props__.__dict__["last_synced_at"] = None
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["authToken"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(Scim, __self__).__init__(
            'netbird:index/scim:Scim',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            auth_token: Optional[pulumi.Input[_builtins.str]] = None,
            enabled: Optional[pulumi.Input[_builtins.bool]] = None,
            group_prefixes: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            last_synced_at: Optional[pulumi.Input[_builtins.str]] = None,
            prefix: Optional[pulumi.Input[_builtins.str]] = None,
            provider_name: Optional[pulumi.Input[_builtins.str]] = None,
            user_group_prefixes: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None) -> 'Scim':
        """
        Get an existing Scim resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] auth_token: SCIM API token (only available in full after creation)
        :param pulumi.Input[_builtins.bool] enabled: Indicates whether the integration is enabled
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] group_prefixes: List of<span pulumi-lang-nodejs=" startWith " pulumi-lang-dotnet=" StartWith " pulumi-lang-go=" startWith " pulumi-lang-python=" start_with " pulumi-lang-yaml=" startWith " pulumi-lang-java=" startWith "> start_with </span>string patterns for groups to sync
        :param pulumi.Input[_builtins.str] last_synced_at: Timestamp of when the integration was last synced
        :param pulumi.Input[_builtins.str] prefix: The connection prefix used for the SCIM provider.
        :param pulumi.Input[_builtins.str] provider_name: Name of the SCIM identity provider
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] user_group_prefixes: List of<span pulumi-lang-nodejs=" startWith " pulumi-lang-dotnet=" StartWith " pulumi-lang-go=" startWith " pulumi-lang-python=" start_with " pulumi-lang-yaml=" startWith " pulumi-lang-java=" startWith "> start_with </span>string patterns for groups which users to sync
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _ScimState.__new__(_ScimState)

        __props__.__dict__["auth_token"] = auth_token
        __props__.__dict__["enabled"] = enabled
        __props__.__dict__["group_prefixes"] = group_prefixes
        __props__.__dict__["last_synced_at"] = last_synced_at
        __props__.__dict__["prefix"] = prefix
        __props__.__dict__["provider_name"] = provider_name
        __props__.__dict__["user_group_prefixes"] = user_group_prefixes
        return Scim(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="authToken")
    def auth_token(self) -> pulumi.Output[_builtins.str]:
        """
        SCIM API token (only available in full after creation)
        """
        return pulumi.get(self, "auth_token")

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> pulumi.Output[_builtins.bool]:
        """
        Indicates whether the integration is enabled
        """
        return pulumi.get(self, "enabled")

    @_builtins.property
    @pulumi.getter(name="groupPrefixes")
    def group_prefixes(self) -> pulumi.Output[Sequence[_builtins.str]]:
        """
        List of<span pulumi-lang-nodejs=" startWith " pulumi-lang-dotnet=" StartWith " pulumi-lang-go=" startWith " pulumi-lang-python=" start_with " pulumi-lang-yaml=" startWith " pulumi-lang-java=" startWith "> start_with </span>string patterns for groups to sync
        """
        return pulumi.get(self, "group_prefixes")

    @_builtins.property
    @pulumi.getter(name="lastSyncedAt")
    def last_synced_at(self) -> pulumi.Output[_builtins.str]:
        """
        Timestamp of when the integration was last synced
        """
        return pulumi.get(self, "last_synced_at")

    @_builtins.property
    @pulumi.getter
    def prefix(self) -> pulumi.Output[_builtins.str]:
        """
        The connection prefix used for the SCIM provider.
        """
        return pulumi.get(self, "prefix")

    @_builtins.property
    @pulumi.getter(name="providerName")
    def provider_name(self) -> pulumi.Output[_builtins.str]:
        """
        Name of the SCIM identity provider
        """
        return pulumi.get(self, "provider_name")

    @_builtins.property
    @pulumi.getter(name="userGroupPrefixes")
    def user_group_prefixes(self) -> pulumi.Output[Sequence[_builtins.str]]:
        """
        List of<span pulumi-lang-nodejs=" startWith " pulumi-lang-dotnet=" StartWith " pulumi-lang-go=" startWith " pulumi-lang-python=" start_with " pulumi-lang-yaml=" startWith " pulumi-lang-java=" startWith "> start_with </span>string patterns for groups which users to sync
        """
        return pulumi.get(self, "user_group_prefixes")

