# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['SetupKeyArgs', 'SetupKey']

@pulumi.input_type
class SetupKeyArgs:
    def __init__(__self__, *,
                 allow_extra_dns_labels: Optional[pulumi.Input[_builtins.bool]] = None,
                 auto_groups: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 ephemeral: Optional[pulumi.Input[_builtins.bool]] = None,
                 expiry_seconds: Optional[pulumi.Input[_builtins.float]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 revoked: Optional[pulumi.Input[_builtins.bool]] = None,
                 type: Optional[pulumi.Input[_builtins.str]] = None,
                 usage_limit: Optional[pulumi.Input[_builtins.float]] = None):
        """
        The set of arguments for constructing a SetupKey resource.

        :param pulumi.Input[_builtins.bool] allow_extra_dns_labels: Allow extra DNS labels to be added to the peer
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] auto_groups: List of groups to automatically assign to peers created through this setup key
        :param pulumi.Input[_builtins.bool] ephemeral: Indicate that the peer will be ephemeral or not, ephemeral peers are deleted after 10 minutes of inactivity
        :param pulumi.Input[_builtins.float] expiry_seconds: Expiry time in seconds (0 is unlimited)
        :param pulumi.Input[_builtins.str] name: SetupKey Name
        :param pulumi.Input[_builtins.bool] revoked: Set to true to revoke setup key
        :param pulumi.Input[_builtins.str] type: Setup Key type (one-off or reusable)
        :param pulumi.Input[_builtins.float] usage_limit: Maximum number of times SetupKey can be used (0 for unlimited)
        """
        if allow_extra_dns_labels is not None:
            pulumi.set(__self__, "allow_extra_dns_labels", allow_extra_dns_labels)
        if auto_groups is not None:
            pulumi.set(__self__, "auto_groups", auto_groups)
        if ephemeral is not None:
            pulumi.set(__self__, "ephemeral", ephemeral)
        if expiry_seconds is not None:
            pulumi.set(__self__, "expiry_seconds", expiry_seconds)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if revoked is not None:
            pulumi.set(__self__, "revoked", revoked)
        if type is not None:
            pulumi.set(__self__, "type", type)
        if usage_limit is not None:
            pulumi.set(__self__, "usage_limit", usage_limit)

    @_builtins.property
    @pulumi.getter(name="allowExtraDnsLabels")
    def allow_extra_dns_labels(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Allow extra DNS labels to be added to the peer
        """
        return pulumi.get(self, "allow_extra_dns_labels")

    @allow_extra_dns_labels.setter
    def allow_extra_dns_labels(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "allow_extra_dns_labels", value)

    @_builtins.property
    @pulumi.getter(name="autoGroups")
    def auto_groups(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        List of groups to automatically assign to peers created through this setup key
        """
        return pulumi.get(self, "auto_groups")

    @auto_groups.setter
    def auto_groups(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "auto_groups", value)

    @_builtins.property
    @pulumi.getter
    def ephemeral(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Indicate that the peer will be ephemeral or not, ephemeral peers are deleted after 10 minutes of inactivity
        """
        return pulumi.get(self, "ephemeral")

    @ephemeral.setter
    def ephemeral(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "ephemeral", value)

    @_builtins.property
    @pulumi.getter(name="expirySeconds")
    def expiry_seconds(self) -> Optional[pulumi.Input[_builtins.float]]:
        """
        Expiry time in seconds (0 is unlimited)
        """
        return pulumi.get(self, "expiry_seconds")

    @expiry_seconds.setter
    def expiry_seconds(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "expiry_seconds", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        SetupKey Name
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def revoked(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Set to true to revoke setup key
        """
        return pulumi.get(self, "revoked")

    @revoked.setter
    def revoked(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "revoked", value)

    @_builtins.property
    @pulumi.getter
    def type(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Setup Key type (one-off or reusable)
        """
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "type", value)

    @_builtins.property
    @pulumi.getter(name="usageLimit")
    def usage_limit(self) -> Optional[pulumi.Input[_builtins.float]]:
        """
        Maximum number of times SetupKey can be used (0 for unlimited)
        """
        return pulumi.get(self, "usage_limit")

    @usage_limit.setter
    def usage_limit(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "usage_limit", value)


@pulumi.input_type
class _SetupKeyState:
    def __init__(__self__, *,
                 allow_extra_dns_labels: Optional[pulumi.Input[_builtins.bool]] = None,
                 auto_groups: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 ephemeral: Optional[pulumi.Input[_builtins.bool]] = None,
                 expires: Optional[pulumi.Input[_builtins.str]] = None,
                 expiry_seconds: Optional[pulumi.Input[_builtins.float]] = None,
                 key: Optional[pulumi.Input[_builtins.str]] = None,
                 last_used: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 revoked: Optional[pulumi.Input[_builtins.bool]] = None,
                 state: Optional[pulumi.Input[_builtins.str]] = None,
                 type: Optional[pulumi.Input[_builtins.str]] = None,
                 updated_at: Optional[pulumi.Input[_builtins.str]] = None,
                 usage_limit: Optional[pulumi.Input[_builtins.float]] = None,
                 used_times: Optional[pulumi.Input[_builtins.float]] = None,
                 valid: Optional[pulumi.Input[_builtins.bool]] = None):
        """
        Input properties used for looking up and filtering SetupKey resources.

        :param pulumi.Input[_builtins.bool] allow_extra_dns_labels: Allow extra DNS labels to be added to the peer
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] auto_groups: List of groups to automatically assign to peers created through this setup key
        :param pulumi.Input[_builtins.bool] ephemeral: Indicate that the peer will be ephemeral or not, ephemeral peers are deleted after 10 minutes of inactivity
        :param pulumi.Input[_builtins.str] expires: SetupKey Expiration Date
        :param pulumi.Input[_builtins.float] expiry_seconds: Expiry time in seconds (0 is unlimited)
        :param pulumi.Input[_builtins.str] key: Plaintext setup key
        :param pulumi.Input[_builtins.str] last_used: Last usage time
        :param pulumi.Input[_builtins.str] name: SetupKey Name
        :param pulumi.Input[_builtins.bool] revoked: Set to true to revoke setup key
        :param pulumi.Input[_builtins.str] state: Setup key state (valid or expired)
        :param pulumi.Input[_builtins.str] type: Setup Key type (one-off or reusable)
        :param pulumi.Input[_builtins.str] updated_at: Creation timestamp
        :param pulumi.Input[_builtins.float] usage_limit: Maximum number of times SetupKey can be used (0 for unlimited)
        :param pulumi.Input[_builtins.float] used_times: Number of times Setup Key was used
        :param pulumi.Input[_builtins.bool] valid: True if setup key can be used to create more Peers
        """
        if allow_extra_dns_labels is not None:
            pulumi.set(__self__, "allow_extra_dns_labels", allow_extra_dns_labels)
        if auto_groups is not None:
            pulumi.set(__self__, "auto_groups", auto_groups)
        if ephemeral is not None:
            pulumi.set(__self__, "ephemeral", ephemeral)
        if expires is not None:
            pulumi.set(__self__, "expires", expires)
        if expiry_seconds is not None:
            pulumi.set(__self__, "expiry_seconds", expiry_seconds)
        if key is not None:
            pulumi.set(__self__, "key", key)
        if last_used is not None:
            pulumi.set(__self__, "last_used", last_used)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if revoked is not None:
            pulumi.set(__self__, "revoked", revoked)
        if state is not None:
            pulumi.set(__self__, "state", state)
        if type is not None:
            pulumi.set(__self__, "type", type)
        if updated_at is not None:
            pulumi.set(__self__, "updated_at", updated_at)
        if usage_limit is not None:
            pulumi.set(__self__, "usage_limit", usage_limit)
        if used_times is not None:
            pulumi.set(__self__, "used_times", used_times)
        if valid is not None:
            pulumi.set(__self__, "valid", valid)

    @_builtins.property
    @pulumi.getter(name="allowExtraDnsLabels")
    def allow_extra_dns_labels(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Allow extra DNS labels to be added to the peer
        """
        return pulumi.get(self, "allow_extra_dns_labels")

    @allow_extra_dns_labels.setter
    def allow_extra_dns_labels(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "allow_extra_dns_labels", value)

    @_builtins.property
    @pulumi.getter(name="autoGroups")
    def auto_groups(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        List of groups to automatically assign to peers created through this setup key
        """
        return pulumi.get(self, "auto_groups")

    @auto_groups.setter
    def auto_groups(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "auto_groups", value)

    @_builtins.property
    @pulumi.getter
    def ephemeral(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Indicate that the peer will be ephemeral or not, ephemeral peers are deleted after 10 minutes of inactivity
        """
        return pulumi.get(self, "ephemeral")

    @ephemeral.setter
    def ephemeral(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "ephemeral", value)

    @_builtins.property
    @pulumi.getter
    def expires(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        SetupKey Expiration Date
        """
        return pulumi.get(self, "expires")

    @expires.setter
    def expires(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "expires", value)

    @_builtins.property
    @pulumi.getter(name="expirySeconds")
    def expiry_seconds(self) -> Optional[pulumi.Input[_builtins.float]]:
        """
        Expiry time in seconds (0 is unlimited)
        """
        return pulumi.get(self, "expiry_seconds")

    @expiry_seconds.setter
    def expiry_seconds(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "expiry_seconds", value)

    @_builtins.property
    @pulumi.getter
    def key(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Plaintext setup key
        """
        return pulumi.get(self, "key")

    @key.setter
    def key(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "key", value)

    @_builtins.property
    @pulumi.getter(name="lastUsed")
    def last_used(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Last usage time
        """
        return pulumi.get(self, "last_used")

    @last_used.setter
    def last_used(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "last_used", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        SetupKey Name
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def revoked(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Set to true to revoke setup key
        """
        return pulumi.get(self, "revoked")

    @revoked.setter
    def revoked(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "revoked", value)

    @_builtins.property
    @pulumi.getter
    def state(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Setup key state (valid or expired)
        """
        return pulumi.get(self, "state")

    @state.setter
    def state(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "state", value)

    @_builtins.property
    @pulumi.getter
    def type(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Setup Key type (one-off or reusable)
        """
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "type", value)

    @_builtins.property
    @pulumi.getter(name="updatedAt")
    def updated_at(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Creation timestamp
        """
        return pulumi.get(self, "updated_at")

    @updated_at.setter
    def updated_at(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "updated_at", value)

    @_builtins.property
    @pulumi.getter(name="usageLimit")
    def usage_limit(self) -> Optional[pulumi.Input[_builtins.float]]:
        """
        Maximum number of times SetupKey can be used (0 for unlimited)
        """
        return pulumi.get(self, "usage_limit")

    @usage_limit.setter
    def usage_limit(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "usage_limit", value)

    @_builtins.property
    @pulumi.getter(name="usedTimes")
    def used_times(self) -> Optional[pulumi.Input[_builtins.float]]:
        """
        Number of times Setup Key was used
        """
        return pulumi.get(self, "used_times")

    @used_times.setter
    def used_times(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "used_times", value)

    @_builtins.property
    @pulumi.getter
    def valid(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        True if setup key can be used to create more Peers
        """
        return pulumi.get(self, "valid")

    @valid.setter
    def valid(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "valid", value)


@pulumi.type_token("netbird:index/setupKey:SetupKey")
class SetupKey(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 allow_extra_dns_labels: Optional[pulumi.Input[_builtins.bool]] = None,
                 auto_groups: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 ephemeral: Optional[pulumi.Input[_builtins.bool]] = None,
                 expiry_seconds: Optional[pulumi.Input[_builtins.float]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 revoked: Optional[pulumi.Input[_builtins.bool]] = None,
                 type: Optional[pulumi.Input[_builtins.str]] = None,
                 usage_limit: Optional[pulumi.Input[_builtins.float]] = None,
                 __props__=None):
        """
        Create a SetupKey resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] allow_extra_dns_labels: Allow extra DNS labels to be added to the peer
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] auto_groups: List of groups to automatically assign to peers created through this setup key
        :param pulumi.Input[_builtins.bool] ephemeral: Indicate that the peer will be ephemeral or not, ephemeral peers are deleted after 10 minutes of inactivity
        :param pulumi.Input[_builtins.float] expiry_seconds: Expiry time in seconds (0 is unlimited)
        :param pulumi.Input[_builtins.str] name: SetupKey Name
        :param pulumi.Input[_builtins.bool] revoked: Set to true to revoke setup key
        :param pulumi.Input[_builtins.str] type: Setup Key type (one-off or reusable)
        :param pulumi.Input[_builtins.float] usage_limit: Maximum number of times SetupKey can be used (0 for unlimited)
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[SetupKeyArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a SetupKey resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param SetupKeyArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(SetupKeyArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 allow_extra_dns_labels: Optional[pulumi.Input[_builtins.bool]] = None,
                 auto_groups: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 ephemeral: Optional[pulumi.Input[_builtins.bool]] = None,
                 expiry_seconds: Optional[pulumi.Input[_builtins.float]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 revoked: Optional[pulumi.Input[_builtins.bool]] = None,
                 type: Optional[pulumi.Input[_builtins.str]] = None,
                 usage_limit: Optional[pulumi.Input[_builtins.float]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = SetupKeyArgs.__new__(SetupKeyArgs)

            __props__.__dict__["allow_extra_dns_labels"] = allow_extra_dns_labels
            __props__.__dict__["auto_groups"] = auto_groups
            __props__.__dict__["ephemeral"] = ephemeral
            __props__.__dict__["expiry_seconds"] = expiry_seconds
            __props__.__dict__["name"] = name
            __props__.__dict__["revoked"] = revoked
            __props__.__dict__["type"] = type
            __props__.__dict__["usage_limit"] = usage_limit
            __props__.__dict__["expires"] = None
            __props__.__dict__["key"] = None
            __props__.__dict__["last_used"] = None
            __props__.__dict__["state"] = None
            __props__.__dict__["updated_at"] = None
            __props__.__dict__["used_times"] = None
            __props__.__dict__["valid"] = None
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["key"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(SetupKey, __self__).__init__(
            'netbird:index/setupKey:SetupKey',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            allow_extra_dns_labels: Optional[pulumi.Input[_builtins.bool]] = None,
            auto_groups: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            ephemeral: Optional[pulumi.Input[_builtins.bool]] = None,
            expires: Optional[pulumi.Input[_builtins.str]] = None,
            expiry_seconds: Optional[pulumi.Input[_builtins.float]] = None,
            key: Optional[pulumi.Input[_builtins.str]] = None,
            last_used: Optional[pulumi.Input[_builtins.str]] = None,
            name: Optional[pulumi.Input[_builtins.str]] = None,
            revoked: Optional[pulumi.Input[_builtins.bool]] = None,
            state: Optional[pulumi.Input[_builtins.str]] = None,
            type: Optional[pulumi.Input[_builtins.str]] = None,
            updated_at: Optional[pulumi.Input[_builtins.str]] = None,
            usage_limit: Optional[pulumi.Input[_builtins.float]] = None,
            used_times: Optional[pulumi.Input[_builtins.float]] = None,
            valid: Optional[pulumi.Input[_builtins.bool]] = None) -> 'SetupKey':
        """
        Get an existing SetupKey resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] allow_extra_dns_labels: Allow extra DNS labels to be added to the peer
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] auto_groups: List of groups to automatically assign to peers created through this setup key
        :param pulumi.Input[_builtins.bool] ephemeral: Indicate that the peer will be ephemeral or not, ephemeral peers are deleted after 10 minutes of inactivity
        :param pulumi.Input[_builtins.str] expires: SetupKey Expiration Date
        :param pulumi.Input[_builtins.float] expiry_seconds: Expiry time in seconds (0 is unlimited)
        :param pulumi.Input[_builtins.str] key: Plaintext setup key
        :param pulumi.Input[_builtins.str] last_used: Last usage time
        :param pulumi.Input[_builtins.str] name: SetupKey Name
        :param pulumi.Input[_builtins.bool] revoked: Set to true to revoke setup key
        :param pulumi.Input[_builtins.str] state: Setup key state (valid or expired)
        :param pulumi.Input[_builtins.str] type: Setup Key type (one-off or reusable)
        :param pulumi.Input[_builtins.str] updated_at: Creation timestamp
        :param pulumi.Input[_builtins.float] usage_limit: Maximum number of times SetupKey can be used (0 for unlimited)
        :param pulumi.Input[_builtins.float] used_times: Number of times Setup Key was used
        :param pulumi.Input[_builtins.bool] valid: True if setup key can be used to create more Peers
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _SetupKeyState.__new__(_SetupKeyState)

        __props__.__dict__["allow_extra_dns_labels"] = allow_extra_dns_labels
        __props__.__dict__["auto_groups"] = auto_groups
        __props__.__dict__["ephemeral"] = ephemeral
        __props__.__dict__["expires"] = expires
        __props__.__dict__["expiry_seconds"] = expiry_seconds
        __props__.__dict__["key"] = key
        __props__.__dict__["last_used"] = last_used
        __props__.__dict__["name"] = name
        __props__.__dict__["revoked"] = revoked
        __props__.__dict__["state"] = state
        __props__.__dict__["type"] = type
        __props__.__dict__["updated_at"] = updated_at
        __props__.__dict__["usage_limit"] = usage_limit
        __props__.__dict__["used_times"] = used_times
        __props__.__dict__["valid"] = valid
        return SetupKey(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="allowExtraDnsLabels")
    def allow_extra_dns_labels(self) -> pulumi.Output[_builtins.bool]:
        """
        Allow extra DNS labels to be added to the peer
        """
        return pulumi.get(self, "allow_extra_dns_labels")

    @_builtins.property
    @pulumi.getter(name="autoGroups")
    def auto_groups(self) -> pulumi.Output[Sequence[_builtins.str]]:
        """
        List of groups to automatically assign to peers created through this setup key
        """
        return pulumi.get(self, "auto_groups")

    @_builtins.property
    @pulumi.getter
    def ephemeral(self) -> pulumi.Output[_builtins.bool]:
        """
        Indicate that the peer will be ephemeral or not, ephemeral peers are deleted after 10 minutes of inactivity
        """
        return pulumi.get(self, "ephemeral")

    @_builtins.property
    @pulumi.getter
    def expires(self) -> pulumi.Output[_builtins.str]:
        """
        SetupKey Expiration Date
        """
        return pulumi.get(self, "expires")

    @_builtins.property
    @pulumi.getter(name="expirySeconds")
    def expiry_seconds(self) -> pulumi.Output[_builtins.float]:
        """
        Expiry time in seconds (0 is unlimited)
        """
        return pulumi.get(self, "expiry_seconds")

    @_builtins.property
    @pulumi.getter
    def key(self) -> pulumi.Output[_builtins.str]:
        """
        Plaintext setup key
        """
        return pulumi.get(self, "key")

    @_builtins.property
    @pulumi.getter(name="lastUsed")
    def last_used(self) -> pulumi.Output[_builtins.str]:
        """
        Last usage time
        """
        return pulumi.get(self, "last_used")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        SetupKey Name
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def revoked(self) -> pulumi.Output[_builtins.bool]:
        """
        Set to true to revoke setup key
        """
        return pulumi.get(self, "revoked")

    @_builtins.property
    @pulumi.getter
    def state(self) -> pulumi.Output[_builtins.str]:
        """
        Setup key state (valid or expired)
        """
        return pulumi.get(self, "state")

    @_builtins.property
    @pulumi.getter
    def type(self) -> pulumi.Output[_builtins.str]:
        """
        Setup Key type (one-off or reusable)
        """
        return pulumi.get(self, "type")

    @_builtins.property
    @pulumi.getter(name="updatedAt")
    def updated_at(self) -> pulumi.Output[_builtins.str]:
        """
        Creation timestamp
        """
        return pulumi.get(self, "updated_at")

    @_builtins.property
    @pulumi.getter(name="usageLimit")
    def usage_limit(self) -> pulumi.Output[_builtins.float]:
        """
        Maximum number of times SetupKey can be used (0 for unlimited)
        """
        return pulumi.get(self, "usage_limit")

    @_builtins.property
    @pulumi.getter(name="usedTimes")
    def used_times(self) -> pulumi.Output[_builtins.float]:
        """
        Number of times Setup Key was used
        """
        return pulumi.get(self, "used_times")

    @_builtins.property
    @pulumi.getter
    def valid(self) -> pulumi.Output[_builtins.bool]:
        """
        True if setup key can be used to create more Peers
        """
        return pulumi.get(self, "valid")

