docker:
  images:
    remote:
      docker-cli:
        repo: docker
        tag: "29.4.1-cli"
  volumes:
    local:
      docker-proxy-mtls:
        backup: false
services:
  traefik:
    depends-on: ["docker"]
    container:
      volumes:
        docker-proxy-mtls:
          path: /etc/traefik/cert/docker-proxy-mtls
          read-only: true
  docker:
    variables:
      CA_PATH:
        extract:
          svolume: docker-proxy-mtls
        transform:
          path: ca.crt
      CERT_PATH:
        extract:
          svolume: docker-proxy-mtls
        transform:
          path: server.crt
      KEY_PATH:
        extract:
          svolume: docker-proxy-mtls
        transform:
          path: server.pem
    config:
      dagu:
        docker:
          executor:
            run:
              model: cli
          dags:
            start:
              dag:
                params:
                  main:
                    CONTAINERS: ""
              command:
                - "docker"
                - "start"
                - param: CONTAINERS
            stop:
              dag:
                params:
                  main:
                    CONTAINERS: ""
              command:
                - "docker"
                - "stop"
                - param: CONTAINERS
    files:
      ca:
        path:
          svariable: CA_PATH
        content:
          mtls: proxy-mtls
          info: ca_cert
      cert:
        path:
          svariable: CERT_PATH
        content:
          mtls: proxy-mtls
          info: server_cert
      key:
        path:
          svariable: KEY_PATH
        content:
          mtls: proxy-mtls
          info: server_key
    secrets:
      proxy-mtls:
        algorithm: ED25519
        hostname:
          hostname: docker-proxy
    containers:
      cli:
        active: false
        image: docker-cli
        docker-socket:
          write: false
        user: docker
