services:
  grafana:
    files:
      openobserve:
        path:
          extract:
            volume: grafana-provision
          transform:
            path: datasources/openobserve.yaml
        content:
          format: yaml
          data:
            apiVersion: 1
            prune: true
            datasources:
              - name: Huginn
                uid:
                  secret: openobserve-datasource-uid
                type: grafana-openobserve-datasource
                access: proxy
                editable: false
                url:
                  hvariable: OPENOBSERVE_URI
                user: $OPENOBSERVE_USERNAME
                jsonData:
                  database: default
                secureJsonData:
                  password: $OPENOBSERVE_PASSWORD
              - name: Huginn Metrics
                uid:
                  secret: openobserve-prometheus-datasource-uid
                type: prometheus
                access: proxy
                editable: false
                url:
                  extract:
                    hvariable: OPENOBSERVE_URI
                  transform:
                    string:
                      template: "{value}/api/default/prometheus"
                basicAuth: true
                basicAuthUser: $OPENOBSERVE_USERNAME
                jsonData:
                  httpMethod: POST
                  manageAlerts: false
                  prometheusType: Prometheus
                  timeInterval: 15s
                  disableRecordingRules: true
                secureJsonData:
                  basicAuthPassword: $OPENOBSERVE_PASSWORD
    network:
      bridge:
        egress:
          https:
            github.com: null
            release-assets.githubusercontent.com: null
    secrets:
      openobserve-datasource-uid:
        id:
      openobserve-prometheus-datasource-uid:
        id:
    container:
      envs:
        GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: grafana-openobserve-datasource
        GF_PLUGINS_PREINSTALL_SYNC:
          extract:
            kv:
              openobserve:
                extract: "1.3.0"
                transform:
                  string:
                    template: grafana-openobserve-datasource@{value}@https://github.com/LinPr/grafana-openobserve-datasource/releases/download/v{value}/grafana-openobserve-datasource-{value}.zip
        OPENOBSERVE_USERNAME:
          hvariable: OPENOBSERVE_USERNAME
        OPENOBSERVE_PASSWORD:
          hvariable: OPENOBSERVE_PASSWORD
  openobserve:
    container:
      network:
        bridge:
          grafana: {}
