docker:
  images:
    remote:
      grafana:
        repo: grafana/grafana
        tag: "13.0.1"
  volumes:
    local:
      grafana-data:
        backup:
          sqlite:
            dbs:
              - grafana.db
      grafana-plugins:
        backup: false
      grafana-provision:
        backup: false
services:
  grafana:
    variables:
      PORT: 3000
      URL:
        hostname: grafana
        scheme: https
      AUTH:
        extract:
          kv:
            username:
              keepass:
              info: username
            password:
              keepass:
              info: password
        transform:
          string:
            template: "{username}:{password}"
    config:
      traefik:
        dynamic:
          traefik:
            service:
              port:
                env: GF_SERVER_HTTP_PORT
    keepasses:
      keepass:
        hostname:
          hostname: grafana
    secrets:
      key: {}
    container:
      image: grafana
      volumes:
        grafana-data: /var/lib/grafana/data
        grafana-plugins:
          path: /var/lib/grafana/plugins
          read-only: true
        grafana-provision:
          path: /etc/grafana/provision
          read-only: true
          bind-file: false
      wud:
        template: https://github.com/grafana/grafana/releases/tag/v${original}
      envs:
        GF_PATHS_PROVISIONING:
          volume: grafana-provision
        GF_SERVER_HTTP_PORT:
          svariable: PORT
        GF_SERVER_ROOT_URL:
          svariable: URL
        GF_SERVER_ENABLE_GZIP: true
        GF_DATABASE_WAL: true
        GF_PATHS_DATA:
          volume: grafana-data
        GF_PATHS_PLUGINS:
          volume: grafana-plugins
        GF_ANALYTICS_ENABLED: false
        GF_SECURITY_ADMIN_USER:
          keepass:
          info: username
        GF_SECURITY_ADMIN_PASSWORD:
          keepass:
          info: password
        GF_SECURITY_SECRET_KEY:
          secret: key
        GF_SECURITY_DISABLE_GRAVATAR: true
        GF_PLUGINS_ENABLE_ALPHA: true
    containers:
      reload-datasources:
        oneshot: true
        image: curl
        command:
          - --json
          - "{}"
          - -u
          - svariable: AUTH
          - extract:
              svariable: PORT
            transform:
              string:
                template: "http://grafana:{value}/api/admin/provisioning/datasources/reload"
        volumes:
          grafana-provision:
            path: /etc/grafana/provision
            read-only: true
