docker:
  images:
    remote:
      grafana:
        repo: grafana/grafana
        tag: "13.0.1"
  volumes:
    local:
      grafana-data:
        backup:
          sqlite:
            dbs:
              - grafana.db
      grafana-plugins:
        backup: false
      grafana-provision:
        backup: false
services:
  grafana:
    variables:
      PORT: 3000
      URL:
        hostname: grafana
        scheme: https
      AUTH:
        extract:
          kv:
            username:
              keepass:
              info: username
            password:
              keepass:
              info: password
        transform:
          string:
            template: "{username}:{password}"
      DEFAULT_CONTACT_POINT: me
      PUSHOVER_USER_KEY:
      PUSHOVER_API_TOKEN:
    config:
      traefik:
        dynamic:
          traefik:
            service:
              port:
                env: GF_SERVER_HTTP_PORT
    files:
      alerting-default-contact-point:
        path:
          extract:
            volume: grafana-provision
          transform:
            path: alerting/default-contact-point.yaml
        content:
          format: yaml
          data:
            apiVersion: 1
            contactPoints:
              - name:
                  svariable: DEFAULT_CONTACT_POINT
                receivers:
                  - uid: pushover-me
                    type: pushover
                    settings:
                      apiToken:
                        svariable: PUSHOVER_API_TOKEN
                      userKey:
                        svariable: PUSHOVER_USER_KEY
    keepasses:
      keepass:
        hostname:
          hostname: grafana
    network:
      bridge:
        egress:
          https:
            api.pushover.net: null
    secrets:
      key: {}
    container:
      image: grafana
      tmpfs:
        - /tmp
      volumes:
        grafana-provision:
          path: /etc/grafana/provision
          read-only: true
          bind-file: false
        grafana-data: /var/lib/grafana/data
        grafana-plugins: /var/lib/grafana/plugins
      wud:
        template: https://github.com/grafana/grafana/releases/tag/v${original}
      envs:
        GF_PATHS_PROVISIONING:
          volume: grafana-provision
        GF_SERVER_HTTP_PORT:
          svariable: PORT
        GF_SERVER_ROOT_URL:
          svariable: URL
        GF_SERVER_ENABLE_GZIP: true
        GF_DATABASE_WAL: true
        GF_PATHS_DATA:
          volume: grafana-data
        GF_PATHS_PLUGINS:
          volume: grafana-plugins
        GF_ANALYTICS_ENABLED: false
        GF_SECURITY_ADMIN_USER:
          keepass:
          info: username
        GF_SECURITY_ADMIN_PASSWORD:
          keepass:
          info: password
        GF_SECURITY_SECRET_KEY:
          secret: key
        GF_SECURITY_DISABLE_GRAVATAR: true
        GF_PLUGINS_ENABLE_ALPHA: true
        GF_PLUGINS_PREINSTALL_SYNC:
          transform:
            string:
              template:
                join: ","
    containers:
      reload-datasources:
        oneshot: true
        image: curl
        command:
          - --json
          - "{}"
          - -u
          - svariable: AUTH
          - extract:
              svariable: PORT
            transform:
              string:
                template: "http://grafana:{value}/api/admin/provisioning/datasources/reload"
        volumes:
          grafana-provision:
            path: /etc/grafana/provision
            read-only: true
      reload-alerting:
        oneshot: true
        image: curl
        command:
          - --json
          - "{}"
          - -u
          - svariable: AUTH
          - extract:
              svariable: PORT
            transform:
              string:
                template: "http://grafana:{value}/api/admin/provisioning/alerting/reload"
        volumes:
          grafana-provision:
            path: /etc/grafana/provision
            read-only: true
