services:
  grafana:
    files:
      openobserve:
        path:
          extract:
            volume: grafana-provision
          transform:
            path: datasources/openobserve.yaml
        content:
          format: yaml
          data:
            apiVersion: 1
            prune: true
            datasources:
              - name: Huginn
                uid:
                  secret: openobserve-datasource-uid
                type: openobserve
                access: proxy
                editable: false
                url:
                  hvariable: OPENOBSERVE_URI
                basicAuth: true
                basicAuthUser: $OPENOBSERVE_USERNAME
                secureJsonData:
                  basicAuthPassword: $OPENOBSERVE_PASSWORD
              - name: Huginn Metrics
                uid:
                  secret: openobserve-prometheus-datasource-uid
                type: prometheus
                access: proxy
                editable: false
                url:
                  extract:
                    hvariable: OPENOBSERVE_URI
                  transform:
                    string:
                      template: "{value}/api/default/prometheus"
                basicAuth: true
                basicAuthUser: $OPENOBSERVE_USERNAME
                jsonData:
                  httpMethod: POST
                  manageAlerts: false
                  prometheusType: Prometheus
                  timeInterval: 15s
                  disableRecordingRules: true
                secureJsonData:
                  basicAuthPassword: $OPENOBSERVE_PASSWORD
    secrets:
      openobserve-datasource-uid:
        id:
      openobserve-prometheus-datasource-uid:
        id:
    container:
      envs:
        GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: openobserve
        OPENOBSERVE_USERNAME:
          hvariable: OPENOBSERVE_USERNAME
        OPENOBSERVE_PASSWORD:
          hvariable: OPENOBSERVE_PASSWORD
  openobserve:
    container:
      network:
        bridge:
          grafana: {}
