docker:
  images:
    build:
      hatchet-worker:
        context:
          location: image/hatchet/worker
          base: python-alpine
          python-builder:
            image: python-builder
          homelab-pydantic:
            path: tool/homelab-pydantic
        version: "0.0.1"
  volumes:
    local:
      hatchet-engine-mtls:
        backup: false
      hatchet-worker-config:
        backup: false
services:
  hatchet:
    variables:
      CA_PATH:
        extract:
          svolume: hatchet-engine-mtls
        transform:
          path: ca.crt
      CLIENT_CERT_PATH:
        extract:
          svolume: hatchet-engine-mtls
        transform:
          path: client.crt
      CLIENT_KEY_PATH:
        extract:
          svolume: hatchet-engine-mtls
        transform:
          path: client.pem
      WORKER_WORKFLOW_DIR:
        extract:
          volume: hatchet-worker-config
        transform:
          path: workflow
      WORKER_DOCKER_DIR:
        extract:
          volume: hatchet-worker-config
        transform:
          path: docker
      WORKER_SCHEDULE_DIR:
        extract:
          volume: hatchet-worker-config
        transform:
          path: schedule
      WORKER_CONFIG_DIR:
        extract:
          volume: hatchet-worker-config
        transform:
          path: config
      WORKER_SCHEDULER_DIR:
        extract:
          volume: hatchet-worker-config
        transform:
          path: scheduler
    config:
      worker: worker
      workflow-dir:
        svariable: WORKER_WORKFLOW_DIR
      docker-dir:
        svariable: WORKER_DOCKER_DIR
      schedule-dir:
        svariable: WORKER_SCHEDULE_DIR
      config-dir:
        svariable: WORKER_CONFIG_DIR
      scheduler-dir:
        svariable: WORKER_SCHEDULER_DIR
    files:
      ca:
        path:
          svariable: CA_PATH
        content:
          host: sun
          extract:
            service: hatchet
            extract:
              mtls: engine-mtls
              info: ca_cert
      client-cert:
        path:
          svariable: CLIENT_CERT_PATH
        content:
          host: sun
          extract:
            service: hatchet
            extract:
              mtls: engine-mtls
              info: client_cert
      client-key:
        path:
          svariable: CLIENT_KEY_PATH
        content:
          host: sun
          extract:
            service: hatchet
            extract:
              mtls: engine-mtls
              info: client_key
    containers:
      worker:
        image:
          build: hatchet-worker
        docker-socket:
          write: false
        hosts:
          - record: sun
            hostname: hatchet
          - record: sun
            hostname: hatchet-engine
        log:
          driver: json-file
          opts:
            max-size: "20m"
        volumes:
          hatchet-engine-mtls: /etc/hatchet/mtls/engine
          hatchet-worker-config:
            path: /etc/hatchet/worker
            read-only: true
        envs:
          HATCHET_CLIENT_TOKEN:
            host: sun
            extract:
              service: hatchet
              extract:
                svariable: WORKER_CLIENT_TOKEN
          HATCHET_CLIENT_HOST_PORT:
            host: sun
            extract:
              service: hatchet
              extract:
                svariable: GRPC_ADDRESS
          HATCHET_CLIENT_SERVER_URL:
            host: sun
            extract:
              service: hatchet
              extract:
                svariable: URL
          HATCHET_CLIENT_TLS_STRATEGY: mtls
          HATCHET_CLIENT_TLS_CERT_FILE:
            svariable: CLIENT_CERT_PATH
          HATCHET_CLIENT_TLS_KEY_FILE:
            svariable: CLIENT_KEY_PATH
          HATCHET_CLIENT_TLS_ROOT_CA_FILE:
            svariable: CA_PATH
          HATCHET_CLIENT_TLS_SERVER_NAME:
            record: sun
            hostname: hatchet-engine
          HATCHET_WORKER_HOST:
            hinfo: name
          HATCHET_WORKER_LOG_LEVEL: INFO
          HATCHET_WORKER_WORKFLOW_DIR:
            svariable: WORKER_WORKFLOW_DIR
          HATCHET_WORKER_DOCKER_DIR:
            svariable: WORKER_DOCKER_DIR
          HATCHET_WORKER_SCHEDULE_DIR:
            svariable: WORKER_SCHEDULE_DIR
          HATCHET_WORKER_CONFIG_DIR:
            svariable: WORKER_CONFIG_DIR
          HATCHET_WORKER_SCHEDULER_DIR:
            svariable: WORKER_SCHEDULER_DIR
