docker:
  images:
    remote:
      hatchet:
        repo: ghcr.io/hatchet-dev/hatchet/hatchet-lite
        tag: "v0.86.22"
  volumes:
    local:
      hatchet-config: {}
      hatchet-engine-mtls:
        backup: false
services:
  hatchet:
    variables:
      PORT: 8080
      FRONTEND_PORT: 8081
      RUNTIME_PORT: 8082
      GRPC_PORT: 7070
      HEALTHCHECK_PORT: 8733
      URL:
        record: sun
        hostname: hatchet
        scheme: https
      GRPC_ADDRESS:
        extract:
          kv:
            hostname:
              record: sun
              hostname: hatchet-engine
            port:
              service: traefik
              extract:
                svariable: HTTPS_PORT
        transform:
          string:
            template: "{hostname}:{port}"
      CA_PATH:
        extract:
          svolume: hatchet-engine-mtls
        transform:
          path: ca.crt
      SERVER_CERT_PATH:
        extract:
          svolume: hatchet-engine-mtls
        transform:
          path: server.crt
      SERVER_KEY_PATH:
        extract:
          svolume: hatchet-engine-mtls
        transform:
          path: server.pem
      WORKER_CLIENT_TOKEN:
    config:
      traefik:
        dynamic:
          traefik:
            record: sun
            service:
              port:
                svariable: RUNTIME_PORT
          engine:
            name: engine
            hostsni: hatchet-engine
            service:
              port:
                svariable: GRPC_PORT
    databases:
      postgres:
        postgres:
          envs:
            TZ: UTC
    keepasses:
      keepass:
        username:
          pcontext: email-me
        hostname:
          hostname: hatchet
          record: sun
    files:
      ca:
        path:
          svariable: CA_PATH
        content:
          host: sun
          extract:
            service: hatchet
            extract:
              mtls: engine-mtls
              info: ca_cert
      server-cert:
        path:
          svariable: SERVER_CERT_PATH
        content:
          host: sun
          extract:
            service: hatchet
            extract:
              mtls: engine-mtls
              info: server_cert
      server-key:
        path:
          svariable: SERVER_KEY_PATH
        content:
          host: sun
          extract:
            service: hatchet
            extract:
              mtls: engine-mtls
              info: server_key
    secrets:
      tenant-id:
        uuid:
      engine-mtls:
        algorithm: RSA
        hostname:
          hostname: hatchet-engine
    container:
      image: hatchet
      databases:
        - postgres:
          envs:
            env: DATABASE_URL
      hosts:
        - record: sun
          hostname: hatchet
        - record: sun
          hostname: hatchet-engine
      volumes:
        hatchet-config: /config
        hatchet-engine-mtls: /etc/hatchet/mtls/engine
      envs:
        SERVER_PORT:
          svariable: PORT
        LITE_FRONTEND_PORT:
          svariable: FRONTEND_PORT
        LITE_RUNTIME_PORT:
          svariable: RUNTIME_PORT
        SERVER_URL:
          svariable: URL
        SERVER_GRPC_PORT:
          svariable: GRPC_PORT
        SERVER_GRPC_BIND_ADDRESS: "0.0.0.0"
        SERVER_GRPC_BROADCAST_ADDRESS:
          svariable: GRPC_ADDRESS
        SERVER_GRPC_INSECURE: false
        SERVER_ALLOW_SIGNUP: false
        SERVER_ALLOW_INVITES: false
        SERVER_ALLOW_CREATE_TENANT: false
        SERVER_ALLOW_CHANGE_PASSWORD: false
        SERVER_HEALTHCHECK: true
        SERVER_HEALTHCHECK_PORT:
          svariable: HEALTHCHECK_PORT
        SERVER_ENABLE_DATA_RETENTION: true
        SERVER_ENABLE_WORKER_RETENTION: false
        ADMIN_EMAIL:
          keepass:
          info: username
        ADMIN_PASSWORD:
          keepass:
          info: password
        ADMIN_NAME: Me
        DEFAULT_TENANT_ID:
          secret: tenant-id
        SERVER_SECURITY_CHECK_ENABLED: false
        SERVER_AUTH_COOKIE_DOMAIN:
          record: sun
          hostname: hatchet
        SERVER_TLS_STRATEGY: mtls
        SERVER_TLS_CERT_FILE:
          svariable: SERVER_CERT_PATH
        SERVER_TLS_KEY_FILE:
          svariable: SERVER_KEY_PATH
        SERVER_TLS_ROOT_CA_FILE:
          svariable: CA_PATH
        SERVER_TLS_SERVER_NAME:
          record: sun
          hostname: hatchet-engine
        SERVER_INTERNAL_CLIENT_BASE_INHERIT_BASE: false
        SERVER_INTERNAL_CLIENT_BASE_STRATEGY: mtls
        SERVER_INTERNAL_CLIENT_TLS_BASE_CERT_FILE:
          svariable: CLIENT_CERT_PATH
        SERVER_INTERNAL_CLIENT_TLS_BASE_KEY_FILE:
          svariable: CLIENT_KEY_PATH
        SERVER_INTERNAL_CLIENT_TLS_BASE_ROOT_CA_FILE:
          svariable: CA_PATH
        SERVER_INTERNAL_CLIENT_TLS_SERVER_NAME:
          env: SERVER_TLS_SERVER_NAME
        SERVER_INTERNAL_CLIENT_INTERNAL_GRPC_BROADCAST_ADDRESS:
          env: SERVER_GRPC_BROADCAST_ADDRESS
        SERVER_LOGGER_LEVEL: WARN
        SERVER_LOGGER_FORMAT: json
        SERVER_OBSERVABILITY_ENABLED: true
        SERVER_DEFAULT_ENGINE_VERSION: "V1"
