docker:
  images:
    remote:
      stalwart:
        repo: stalwartlabs/stalwart
        tag: "v0.16.1"
  volumes:
    local:
      mail-stalwart-config:
        backup: false
      mail-stalwart-data: {}
services:
  kanidm:
    config:
      state:
        systems:
          oauth2:
            mail:
              display-name: Mail
              origin-url:
                - hostname: mail
                  record: solar
                  scheme: https
              origin-landing:
                hostname: mail
                record: solar
                scheme: https
              prefer-short-username: true
  mail:
    variables:
      STALWART_CONFIG_PATH:
        extract:
          volume: mail-stalwart-config
        transform:
          path: config.json
      STALWART_HTTP_PORT: 12908
      MAIL_OAUTH_URL:
        extract:
          record: solar
          hostname: kanidm
          scheme: https
        transform:
          string:
            template: "{value}/oauth2/openid/mail"
    config:
      stalwart:
        recovery:
          enabled: true
          address:
            hinfo: address
          username:
            keepass: stalwart-admin
            info: username
          password:
            keepass: stalwart-admin
            info: password
        listener:
          http:
            port:
              svariable: STALWART_HTTP_PORT
            protocol: http
          smtp:
            port:
              gvariable: MAIL_SMTP_PORT
            protocol: smtp
          smtps:
            port:
              gvariable: MAIL_SMTPS_PORT
            protocol: smtp
            tls-implicit: true
      traefik:
        dynamic:
          smtps:
            name: smtps
            hostsni:
            entrypoint: smtps
            passthrough: false
            service:
              port:
                gvariable: MAIL_SMTP_PORT
    keepasses:
      stalwart-admin:
        username:
          force-lower: true
        hostname:
          record: solar
          hostname: mail
    files:
      stalwart-config:
        path:
          svariable: STALWART_CONFIG_PATH
        content:
          format: json
          data:
            "@type": "RocksDb"
            path:
              extract:
                volume: mail-stalwart-data
              transform:
                path: rocksdb
    container:
      delete-before-replace: true
      image: stalwart
      cap:
        add:
          - NET_BIND_SERVICE
      command:
        - "-c"
        - svariable: STALWART_CONFIG_PATH
      healthcheck: {}
      hosts:
        - record: solar
          hostname: kanidm
      tmpfs:
        - /tmp
      volumes:
        mail-stalwart-config:
          path: /etc/stalwart
          read-only: true
        mail-stalwart-data: /var/lib/stalwart
      envs:
        STALWART_RECOVERY_MODE_LOG_LEVEL: debug
        STALWART_HEALTHCHECK_URL:
          extract:
            svariable: STALWART_HTTP_PORT
          transform:
            string:
              template: "http://localhost:{value}/healthz/live"
