docker:
  images:
    remote:
      n8n:
        repo: ghcr.io/n8n-io/n8n
        tag: "2.12.0"
  volumes:
    local:
      n8n-data: {}
      n8n-hooks:
        backup: false
services:
  kanidm:
    config:
      state:
        systems:
          oauth2:
            n8n:
              display-name: N8N
              origin-url:
                - service: n8n
                  extract:
                    svariable: REDIRECT_URL
              origin-landing:
                hostname: n8n
                record: solar
                scheme: https
              prefer-short-username: true
              allow-insecure-client-disable-pkce: true
  n8n:
    variables:
      REDIRECT_URL:
        extract:
          hostname: n8n
          record: solar
          scheme: https
        transform:
          string:
            template: "{value}/auth/oidc/callback"
      OAUTH_URL:
        extract:
          hostname: kanidm
          record: solar
          scheme: https
        transform:
          string:
            template: "{value}/oauth2/openid/n8n"
      OIDC_HOOK_PATH:
        extract:
          volume: n8n-hooks
        transform:
          path: oidc.js
    config:
      traefik:
        dynamic:
          traefik:
            record: solar
            service:
              port:
                env: N8N_PORT
    databases:
      postgres:
        postgres: {}
    keepasses:
      keepass:
        hostname:
          hostname: n8n
          record: solar
    files:
      oidc-hook:
        path:
          svariable: OIDC_HOOK_PATH
        content:
          include: config/data/n8n/n8n-oidc/hooks.js
    secrets:
      key: {}
      jwt: {}
    container:
      image: n8n
      databases:
        - postgres:
          envs:
            username: DB_POSTGRESDB_USER
            password: DB_POSTGRESDB_PASSWORD
            database: DB_POSTGRESDB_DATABASE
            host: DB_POSTGRESDB_HOST
            port: DB_POSTGRESDB_PORT
      healthcheck:
        tests:
          - "CMD"
          - "wget"
          - "--spider"
          - "-q"
          - extract:
              env: N8N_PORT
            transform:
              string:
                template: "http://localhost:{value}/healthz"
      network:
        bridge:
          vpn: {}
      tmpfs:
        - /home/node/.cache/n8n/public
        - /tmp/n8nDataTableUploads
      volumes:
        n8n-data: /home/node/.n8n
        n8n-hooks:
          path: /hooks
          read-only: true
      wud:
        template: https://github.com/n8n-io/n8n/releases/tag/n8n@${original}
      envs:
        DB_TYPE: postgresdb
        N8N_ENCRYPTION_KEY:
          secret: key
        N8N_PORT: 5678
        N8N_DIAGNOSTICS_ENABLED: false
        N8N_VERSION_NOTIFICATIONS_ENABLED: false
        N8N_TEMPLATES_ENABLED: false
        N8N_DIAGNOSTICS_CONFIG_FRONTEND: ""
        N8N_DIAGNOSTICS_CONFIG_BACKEND: ""
        N8N_HIRING_BANNER_ENABLED: false
        N8N_PROXY_HOPS: 1
        N8N_USER_MANAGEMENT_JWT_SECRET:
          secret: jwt
        N8N_LICENSE_ACTIVATION_KEY:
        N8N_EDITOR_BASE_URL:
          hostname: n8n
          record: solar
          scheme: https
        WEBHOOK_URL:
          hostname: n8n
          record: solar
          scheme: https
        EXTERNAL_HOOK_FILES:
          svariable: OIDC_HOOK_PATH
        OIDC_ISSUER_URL:
          svariable: OAUTH_URL
        OIDC_CLIENT_ID: n8n
        OIDC_CLIENT_SECRET:
          service: kanidm
          extract:
            export: n8n
        OIDC_REDIRECT_URI:
          svariable: REDIRECT_URL
        N8N_ADDITIONAL_NON_UI_ROUTES: auth
        EXTERNAL_FRONTEND_HOOKS_URLS: /assets/oidc-frontend-hook.js
