services:
  traefik:
    config:
      log:
        access:
          config:
            fields:
              headers:
                names:
                  X-Geoblock-Remediation: keep
      record:
        external-middlewares:
          http:
            - geoblock
      plugins:
        geoblock:
          name: github.com/david-garcia-garcia/traefik-geoblock
          version: "v1.1.4"
          unsafe: true
      traefik:
        dynamic:
          geoblock:
            name: geoblock
            plugin: geoblock
            data:
              enabled: true
              defaultAllow: false
              databaseFilePath:
                extract:
                  volume: traefik-plugin
                transform:
                  path: sources
              allowedCountries:
              allowPrivate: true
              banIfError: true
              logLevel: "info"
              logFormat: "json"
              logBannedRequests: false
              databaseAutoUpdate: true
              databaseAutoUpdateDir:
                extract:
                  volume: traefik-data
                transform:
                  path: ip2database
              remediationHeadersCustomName: X-Geoblock-Remediation
