images:
  remote:
    alist:
      repo: xhofe/alist
      tag: "v3.42.0-aio"
volumes:
  local:
    alist-data: {}
services:
  alist:
    config:
      traefik:
        traefik:
          public: true
          service:
            port:
              env: HTTP_PORT
    secrets:
      jwt: {}
    container:
      image: alist
      envs:
        SITE_URL:
          hostname: alist
          public: true
        JWT_SECRET:
          secret: jwt
        HTTP_PORT: 5244
        DB_FILE:
          extract:
            volume: alist-data
          transform:
            path: data.db
      wud:
        template: https://github.com/AlistGo/alist/releases/tag/v${transformed}
        include-prefix: v
        include-suffix: -aio
        transform: true
      volumes:
        alist-data: /opt/alist/data
