images:
  remote:
    apprise:
      repo: ghcr.io/caronc/apprise
      tag: "1.2.0"
volumes:
  local:
    apprise-config:
      backup: false
    apprise-storage: {}
    apprise-attach: {}
services:
  apprise:
    config: {}
    container:
      image: apprise
      volumes:
        apprise-config:
          path: /config
          read-only: true
        apprise-storage: /storage
        apprise-attach: /attach
      tmpfs:
        - /tmp
        - /run/apprise
        - /var/lib/nginx/body
        - /var/lib/nginx/proxy
        - /var/lib/nginx/fastcgi
        - /var/lib/nginx/uwsgi
        - /var/lib/nginx/scgi
      envs:
        PUID: 0
        PGID: 0
        APPRISE_CONFIG_DIR:
          volume: apprise-config
        APPRISE_CONFIG_PATH:
          volume: apprise-config
        APPRISE_STORAGE_DIR:
          volume: apprise-storage
        APPRISE_STORAGE_PATH:
          volume: apprise-storage
        APPRISE_ATTACH_DIR:
          volume: apprise-attach
        APPRISE_ATTACH_PATH:
          volume: apprise-attach
        APPRISE_STATEFUL_MODE: simple
        APPRISE_CONFIG_LOCK: "yes"
        APPRISE_ADMIN: "yes"
        APPRISE_PLUGIN_PATHS: ""
        APPRISE_WORKER_COUNT: 1
