images:
  build:
    barman:
      context:
        location: image/barman
        base: alpine
      args:
        BARMAN_VERSION: &barman-version "3.13.0-r0"
      version: *barman-version
volumes:
  local:
    barman-home: {}
    barman-config:
      backup: false
services:
  barman:
    config:
      config-dir:
        volume: barman-config
      staging-dir:
        extract:
          volume: barman-home
        transform:
          path: staging
      minimum-redundancy: 5
      last-backup-maximum-age: 1 WEEKS
      retention-policy: RECOVERY WINDOW OF 1 WEEKS
      dagu:
        docker:
          executor:
            exec:
              container:
          dag:
            params:
              types:
                backup:
            tags: ["backup"]
          command:
            prefix: ["barman"]
            suffix:
              - param:
                  type: backup
          dags:
            check:
              dag:
                schedule: "0 2 * * *" # 2am every day
              command: ["check"]
            backup:
              # TODO: re-enable --wait option after https://github.com/EnterpriseDB/barman/issues/1041
              command: ["backup"]
            switch-wal:
              command: ["switch-wal", "--force", "--archive"]
    container:
      image:
        build: barman
      init: true
      tmpfs:
        - /tmp
        - /var/run
      volumes:
        barman-config:
          path: /etc/barman.d
          read-only: true
        barman-home: /var/lib/barman
