images:
  remote:
    beszel:
      repo: ghcr.io/henrygd/beszel/beszel
      tag: "0.11.1"
volumes:
  local:
    beszel-data: {}
services:
  beszel:
    variables:
      PORT: 8090
      PREFIX: /xana
    config:
      traefik:
        traefik:
          public: false
          hostname: system
          prefix:
            variable: PREFIX
          service:
            port:
              variable: PORT
          middlewares:
            - name: strip-prefix
              data:
                stripPrefix:
                  prefixes:
                    - variable: PREFIX
      files:
        file:
          private-key:
            path:
              extract:
                volume: beszel-data
              transform:
                path: id_ed25519
            content:
              extract:
                secret: ssh
              transform:
                string:
                  template: "{private_key_openssh}"
          public-key:
            path:
              extract:
                volume: beszel-data
              transform:
                path: id_ed25519.pub
            content:
              extract:
                secret: ssh
              transform:
                string:
                  template: "{public_key_openssh}"
    secrets:
      ssh:
        algorithm: ED25519
    keepasses:
      keepass:
        hostname:
          hostname: system
          public: false
    container:
      image: beszel
      network:
        default-bridge: true
      volumes:
        beszel-data: /beszel_data
        "/var/lib/beszel-agent": /var/lib/beszel-agent
      envs:
        APP_URL:
          extract:
            kv:
              base:
                hostname: system
                public: false
                scheme: https
              prefix:
                variable: PREFIX
          transform:
            string:
              template: "{base}{prefix}"
