images:
  remote:
    cadvisor:
      repo: ghcr.io/google/cadvisor
      tag: "v0.53.0"
services:
  cadvisor:
    variables:
      PORT: 8080
      PREFIX: /system
    config:
      traefik:
        traefik:
          public: false
          hostname: system
          prefix:
            variable: PREFIX
          service:
            port:
              variable: PORT
    container:
      image: cadvisor
      command:
        - extract:
            variable: PORT
          transform:
            string:
              template: "--port={value}"
        - extract:
            variable: PREFIX
          transform:
            string:
              template: "--url_base_prefix={value}"
        - --store_container_labels=false
        - --docker_only=false
      devices:
        - /dev/kmsg
      docker-socket:
        write: false
      healthcheck:
        tests:
          - "CMD"
          - "wget"
          - "--spider"
          - "-q"
          - extract:
              kv:
                port:
                  variable: PORT
                prefix:
                  variable: PREFIX
            transform:
              string:
                template: "http://localhost:{port}{prefix}/healthz"
        interval: 30s
        timeout: 5s
      privileged: true
      volumes:
        "/":
          path: /rootfs
          read-only: true
        "/var/run":
          path: /var/run
          read-only: true
        "/sys":
          path: /sys
          read-only: true
        "/var/lib/docker":
          path: /var/lib/docker
          read-only: true
        "/dev/disk":
          path: /dev/disk
          read-only: true
