images:
  remote:
    dagu:
      repo: ghcr.io/dagu-org/dagu
      tag: "1.17.2"
volumes:
  local:
    dagu-home: {}
    dagu-dags:
      backup: false
services:
  dagu:
    config:
      dags-dir:
        extract:
          env: DAGU_DAGS_DIR
      log-dir:
        extract:
          env: DAGU_LOG_DIR
      traefik:
        traefik:
          public: false
          service:
            port:
              env: DAGU_PORT
      dagu:
        dag:
          dag:
            name: dummy
            steps:
              - name: dummy
                run: ["true"]
    container:
      image: dagu
      command: ["start-all"]
      docker-socket:
        write: true
      entrypoint: ["dagu"]
      # TODO: Re-enable healthcheck
      # healthcheck:
      #   tests:
      #     - "CMD"
      #     - "wget"
      #     - "-q"
      #     - extract:
      #         env: DAGU_PORT
      #       transform:
      #         string:
      #           template: "http://localhost:{value}/api/v1/health"
      #     - "-O"
      #     - "/dev/null"
      #   interval: 30s
      #   timeout: 5s
      tmpfs:
        - /tmp
      volumes:
        dagu-home: /dagu
        dagu-dags:
          path: /dagu/dags
          read-only: true
      wud:
        template: https://github.com/dagu-org/dagu/releases/tag/v${original}
      envs:
        DAGU_PORT: 8080
        DAGU_TZ:
          docker: "{timezone}"
        DAGU_HOME:
          volume: dagu-home
        DAGU_DAGS_DIR:
          volume: dagu-dags
        DAGU_BASE_CONFIG:
          extract:
            volume: dagu-dags
          transform:
            path: base.yaml
        DAGU_DATA_DIR:
          extract:
            volume: dagu-home
          transform:
            path: data
        DAGU_SUSPEND_FLAGS_DIR:
          extract:
            volume: dagu-home
          transform:
            path: suspend
        DAGU_LOG_DIR:
          extract:
            volume: dagu-home
          transform:
            path: logs/dags
        DAGU_ADMIN_LOG_DIR:
          extract:
            volume: dagu-home
          transform:
            path: logs/admin
        DAGU_PERMISSIONS_WRITE_DAGS: "false"
        DAGU_LOG_FORMAT: json
