images:
  remote:
    ddns:
      repo: ghcr.io/qdm12/ddns-updater
      tag: "v2.9.0"
volumes:
  local:
    ddns-data: {}
services:
  ddns:
    variables:
      PORT: 8000
    config:
      traefik:
        traefik:
          record: private
          hostname: system
          prefix:
            env: ROOT_URL
          service:
            port:
              variable: PORT
    container:
      image: ddns
      healthcheck:
        tests: ["CMD", "/updater/ddns-updater", "healthcheck"]
        interval: 30s
        timeout: 30s
        retries: 5
        start-period: 10s
      network:
        default-bridge: true
      volumes:
        ddns-data: /updater/data
      wait_timeout: 300
      wud:
        template: https://github.com/qdm12/ddns-updater/releases/tag/${original}
        include-prefix: v
      envs:
        LISTENING_ADDRESS:
          extract:
            variable: PORT
          transform:
            string:
              template: ":{value}"
        ROOT_URL: /ip
        DATADIR:
          volume: ddns-data
        RESOLVER_ADDRESS: "1.1.1.1:53"
