images:
  remote:
    flaresolverr:
      repo: 21hsmw/flaresolverr
      tag: "nodriver"
services:
  flaresolverr:
    config: {}
    container:
      image: flaresolverr
      network:
        container:
          service: gluetun
          extract:
            id:
      read-only: false
      # wud:
      #   template: https://github.com/FlareSolverr/FlareSolverr/releases/tag/${original}
      #   include-prefix: v
      envs:
        PORT: 8191
