images:
  remote:
    flaresolverr:
      repo: ghcr.io/flaresolverr/flaresolverr
      tag: "v3.3.25"
services:
  flaresolverr:
    config: {}
    container:
      image: flaresolverr
      network:
        container:
          service: gluetun
          extract:
            id:
      read-only: false
      wud:
        template: https://github.com/FlareSolverr/FlareSolverr/releases/tag/${original}
        include-prefix: v
      envs:
        PORT: 8191
