images:
  remote:
    frp:
      repo: ghcr.io/fatedier/frpc
      tag: "v0.63.0"
volumes:
  local:
    frp-config:
      backup: false
services:
  frp:
    variables:
      CONFIG_PATH:
        extract:
          volume: frp-config
        transform:
          path: client.toml
    config:
      path:
        variable: CONFIG_PATH
      protocol: quic
      pool: 10
    container:
      image: frp
      command:
        - "-c"
        - variable: CONFIG_PATH
      network:
        default-bridge: true
        proxy-bridge: true
      volumes:
        frp-config:
          path: /etc/frp
          read-only: true
      wud:
        template: https://github.com/fatedier/frp/releases/tag/${original}
        include-prefix: v
