images:
  remote:
    immich-server:
      repo: ghcr.io/immich-app/immich-server
      tag: &immich-version "v1.135.3"
    immich-machine-learning:
      repo: ghcr.io/immich-app/immich-machine-learning
      tag: *immich-version
volumes:
  local:
    immich-data: {}
    immich-machine-learning-cache:
      backup: false
services:
  kanidm:
    config:
      state:
        systems:
          oauth2:
            immich:
              display-name: Immich
              origin-url:
                - extract:
                    hostname: immich
                    public: true
                    scheme: https
                  transform:
                    string:
                      template: "{value}/auth/login"
                - extract:
                    hostname: immich
                    public: true
                    scheme: https
                  transform:
                    string:
                      template: "{value}/user-settings"
                - app.immich:///oauth-callback
              origin-landing:
                hostname: immich
                public: true
                scheme: https
              prefer-short-username: true
  immich:
    config:
      traefik:
        traefik:
          public: true
          service:
            port:
              env: IMMICH_PORT
          middlewares:
            - name: limit
              data:
                buffering:
                  maxRequestBodyBytes: 20000000000
                  memRequestBodyBytes: 500000000
                  maxResponseBodyBytes: 20000000000
                  memResponseBodyBytes: 500000000
    databases:
      postgres:
        postgres:
          image: vectorchord
      valkey:
        valkey: {}
    keepasses:
      keepass:
        hostname:
          hostname: immich
          public: true
        apps:
          - app.alextran.immich
    container:
      image: immich-server
      databases:
        - postgres:
          envs:
            env: DB_URL
        - valkey:
          envs:
            username: REDIS_USERNAME
            password: REDIS_PASSWORD
            host: REDIS_HOSTNAME
            port: REDIS_PORT
      devices:
        - /dev/dri
      healthcheck:
        tests:
          - "CMD"
          - "immich-healthcheck"
        interval: 30s
        timeout: 5s
      envs:
        IMMICH_PORT: 2283
        IMMICH_MEDIA_LOCATION:
          volume: immich-data
      volumes:
        immich-data: /usr/src/app/data
      wait-timeout: 120
      wud:
        template: https://github.com/immich-app/immich/releases/tag/${original}
        include-prefix: v
    containers:
      machine-learning:
        image: immich-machine-learning
        healthcheck:
          tests:
            - "CMD"
            - "python3"
            - "healthcheck.py"
          interval: 30s
          timeout: 5s
        network:
          default-bridge: true
        volumes:
          immich-machine-learning-cache: /cache
        tmpfs:
          - /tmp
          - /root
        envs:
          MACHINE_LEARNING_MODEL_TTL: 300
          MACHINE_LEARNING_CACHE_FOLDER:
            volume: immich-machine-learning-cache
