images:
  remote:
    kanidm-server:
      repo: kanidm/server
      tag: &kanidm-version "1.6.4"
volumes:
  local:
    kanidm-config:
      backup: false
    kanidm-data:
      backup: false
    kanidm-backup:
      backup:
        source:
          variable: BACKUP
        file: true
services:
  kanidm:
    variables:
      PORT: &port 8443
      CONFIG:
        extract:
          volume: kanidm-config
        transform:
          path: server.toml
      BACKUP:
        extract:
          volume: kanidm-backup
        transform:
          path: kanidm.backup.json
    config:
      address:
        hinfo: address
      path:
        config:
          variable: CONFIG
        tls-key:
          extract:
            volume: kanidm-data
          transform:
            path: key.pem
        tls-chain:
          extract:
            volume: kanidm-data
          transform:
            path: chain.pem
        db:
          extract:
            volume: kanidm-data
          transform:
            path: kanidm.db
      port:
        variable: PORT
      domain:
        hostname: kanidm
        record: public
      origin:
        hostname: kanidm
        record: public
        scheme: https
      state:
        persons:
          me:
            admin: true
            present: true
            display-name: "Me"
      traefik:
        traefik:
          record: public
          service:
            scheme: https
            port:
              variable: PORT
      dagu:
        dag:
          pre-backup-volume:
            name: pre-backup-volume
            path: kanidm-pre-backup-volume
            tags: ["backup"]
            steps:
              - name: stop-container
                run:
                  service: dagu
                  dag: stop
                  params:
                    main:
                      CONTAINERS:
                        cinfo: name
              - name: create-backup
                executor:
                  model:
                run:
                  - "/sbin/kanidmd"
                  - "database"
                  - "backup"
                  - "-c"
                  - variable: CONFIG
                  - variable: BACKUP
              - name: start-container
                run:
                  service: dagu
                  dag: start
                  params:
                    main:
                      CONTAINERS:
                        cinfo: name
    keepasses:
      keepass:
        hostname:
          hostname: kanidm
          record: public
    container:
      image: kanidm-server
      command:
        - "/sbin/kanidmd"
        - "server"
        - "-c"
        - variable: CONFIG
      healthcheck:
        tests:
          - "CMD"
          - "/sbin/kanidmd"
          - "healthcheck"
          - "-c"
          - variable: CONFIG
        interval: 30s
        timeout: 5s
        retries: 5
        start-interval: 5s
        start-period: 10s
      network:
        default-bridge: true
      ports:
        https:
          internal: *port
          protocol: tcp
      volumes:
        kanidm-config: /config
        kanidm-data: /data
        kanidm-backup: /backup
      wud:
        template: https://github.com/kanidm/kanidm/releases/tag/v${original}
      envs:
        KANIDM_TRUST_X_FORWARD_FOR: true
