images:
  remote:
    maybe:
      repo: ghcr.io/maybe-finance/maybe
      tag: "0.5.0"
volumes:
  local:
    maybe-storage: {}
services:
  maybe:
    config:
      traefik:
        traefik:
          public: true
          service:
            port:
              env: PORT
    databases:
      postgres:
        postgres: {}
      valkey:
        valkey: {}
    keepasses:
      keepass:
        hostname:
          hostname: maybe
          public: true
    secrets:
      key: {}
    container:
      image: maybe
      databases:
        - postgres:
          envs:
            username: POSTGRES_USER
            password: POSTGRES_PASSWORD
            database: POSTGRES_DB
            host: DB_HOST
            port: DB_PORT
        - valkey:
          envs:
            env: REDIS_URL
      network:
        default-bridge: true
      tmpfs:
        - /tmp
        - /rails/tmp/sockets
      volumes:
        maybe-storage: /rails/storage
      wud:
        template: https://github.com/maybe-finance/maybe/releases/tag/v${original}
      envs:
        SELF_HOSTED: true
        RAILS_FORCE_SSL: false
        RAILS_ASSUME_SSL: true
        SECRET_KEY_BASE:
          secret: key
        PORT: 3000
        APP_DOMAIN:
          hostname: maybe
          public: true
    containers:
      worker:
        inherit:
        command: ["bundle", "exec", "sidekiq"]
        network:
          default-bridge: false
        wud:
