images:
  remote:
    neko-vlc:
      repo: ghcr.io/m1k1o/neko/vlc
      tag: &neko-tag "3.0.6"
services:
  neko:
    variables:
      PORT: 8080
      UDP_PORT_START: &udp-port-start 52000
      UDP_PORT_END: &udp-port-end 52010
    config:
      traefik:
        vlc:
          name: vlc
          hostname: neko
          public: true
          service:
            container: vlc
            port:
              variable: PORT
    keepasses:
      admin:
        hostname:
          hostname: neko
          public: true
      user:
        hostname:
          hostname: neko
          public: true
    containers:
      vlc:
        image: neko-vlc
        ports:
          neko-udp-v4:
            start: *udp-port-start
            end: *udp-port-end
            ip: "0.0.0.0"
            protocol: udp
            forward: {}
          neko-udp-v6:
            start: *udp-port-start
            end: *udp-port-end
            ip: "::"
            protocol: udp
        tmpfs:
          - /tmp
          - /var/run/
          - /var/log/neko
          - /tmp/.X11-unix
          - path: /home/neko
            uid: 1000
            gid: 1000
        volumes:
          jellyfin-starr:
            path: /starr/media
            read-only: true
          jellyfin-downloads:
            path: /downloads/media
            read-only: true
        envs:
          NEKO_DESKTOP_SCREEN: "1920x1080@30"
          NEKO_CAPTURE_VIDEO_CODEC: h264
          NEKO_MEMBER_MULTIUSER_ADMIN_PASSWORD:
            keepass: admin
            info: password
          NEKO_MEMBER_MULTIUSER_USER_PASSWORD:
            keepass: user
            info: password
          NEKO_SESSION_IMPLICIT_HOSTING: true
          NEKO_WEBRTC_ICELITE: true
          NEKO_WEBRTC_NAT1TO1:
          NEKO_WEBRTC_EPR:
            extract:
              kv:
                start:
                  variable: UDP_PORT_START
                end:
                  variable: UDP_PORT_END
            transform:
              string:
                template: "{start}-{end}"
          NEKO_SERVER_BIND:
            extract:
              variable: PORT
            transform:
              string:
                template: "0.0.0.0:{value}"
          NEKO_SERVER_PROXY: true
          NEKO_LOG_JSON: true
          NEKO_LOG_LEVEL: info
          NEKO_DEBUG: false
