images:
  remote:
    nghe:
      repo: ghcr.io/vnghia/nghe-musl
      tag: "0.10.6"
volumes:
  local:
    nghe-music: {}
    nghe-cache: {}
services:
  nghe:
    config:
      traefik:
        traefik:
          record: public
          service:
            port:
              env: NGHE_SERVER__PORT
    databases:
      postgres:
        postgres: {}
    secrets:
      key:
        length: 16
    container:
      image: nghe
      databases:
        - postgres:
          envs:
            env: NGHE_DATABASE__URL
      healthcheck:
        tests:
          - "CMD"
          - "wget"
          - "--spider"
          - "-q"
          - extract:
              env: NGHE_SERVER__PORT
            transform:
              string:
                template: "http://localhost:{value}/rest/health"
        interval: 30s
        timeout: 5s
      network:
        default-bridge: true
      volumes:
        nghe-music:
          path: /music
          read-only: true
        nghe-cache: /tmp/nghe
      envs:
        NGHE_SERVER__PORT: 3000
        NGHE_DATABASE__KEY:
          extract:
            secret: key
          transform:
            secret:
              encode: hex
        NGHE_LOG__TIME: false
        NGHE_LOG__FORMAT: json
        NGHE_S3__ENABLE: true
        NGHE_INTEGRATION__SPOTIFY__ID:
        NGHE_INTEGRATION__SPOTIFY__SECRET:
        NGHE_INTEGRATION__LASTFM__KEY:
