images:
  remote:
    opencloud:
      repo: opencloudeu/opencloud-rolling
      tag: "2.1.0"
volumes:
  local:
    opencloud-config:
      backup: false
    opencloud-data: {}
services:
  kanidm:
    config:
      state:
        systems:
          oauth2:
            opencloud:
              public: true
              display-name: OpenCloud
              origin-url:
                - hostname: opencloud
                  public: true
                  scheme: https
                - extract:
                    hostname: opencloud
                    public: true
                    scheme: https
                  transform:
                    string:
                      template: "{value}/oidc-callback.html"
                - extract:
                    hostname: opencloud
                    public: true
                    scheme: https
                  transform:
                    string:
                      template: "{value}/oidc-silent-redirect.html"
                - oc://android.opencloud.eu
                - oc://ios.opencloud.eu
              origin-landing:
                hostname: opencloud
                public: true
                scheme: https
              prefer-short-username: true
              claim-maps:
                role:
                  values-by-group:
                    role_admin: [opencloudAdmin]
                    role_user: [opencloudUser]
  opencloud:
    variables:
      PORT: 9200
    config:
      traefik:
        traefik:
          public: true
          service:
            port:
              variable: PORT
      files:
        file:
          csp:
            path:
              env: PROXY_CSP_CONFIG_FILE_LOCATION
            content:
              yaml:
                directives:
                  child-src:
                    - "'self'"
                  connect-src:
                    - "'self'"
                    - "blob:"
                    - hostname: kanidm
                      public: true
                      scheme: https
                  default-src:
                    - "'none'"
                  font-src:
                    - "'self'"
                  frame-ancestors:
                    - "'self'"
                  frame-src:
                    - "'self'"
                    - "blob:"
                    - "https://embed.diagrams.net/"
                  img-src:
                    - "'self'"
                    - "data:"
                    - "blob:"
                  manifest-src:
                    - "'self'"
                  media-src:
                    - "'self'"
                  object-src:
                    - "'self'"
                    - "blob:"
                  script-src:
                    - "'self'"
                    - "'unsafe-inline'"
                  style-src:
                    - "'self'"
                    - "'unsafe-inline'"
    secrets:
      jwt-secret: {}
      transfer-secret: {}
      machine-auth-api-key: {}
      system-user-id:
        uuid: true
      system-user-api-key: {}
      storage-users-mount-id:
        uuid: true
      service-account-id:
        uuid: true
      service-account-secret: {}
      graph-application-id:
        uuid: true
      idm-service-user-password: {}
      reva-service-user-password: {}
      idp-service-user-password: {}
      ldap-bind-password: {}
    container:
      image: opencloud
      tmpfs:
        - /tmp
      volumes:
        opencloud-config:
          path: /etc/opencloud
          read-only: true
        opencloud-data: /var/lib/opencloud
      wud:
        template: https://github.com/opencloud-eu/opencloud/releases/tag/v${original}
      envs:
        PROXY_HTTP_ADDR:
          extract:
            variable: PORT
          transform:
            string:
              template: "0.0.0.0:{value}"
        PROXY_TLS: false
        OC_LOG_LEVEL: info
        OC_URL:
          hostname: opencloud
          public: true
          scheme: https
        GATEWAY_GRPC_ADDR: 0.0.0.0:9142
        OC_GATEWAY_GRPC_ADDR:
          env: GATEWAY_GRPC_ADDR
        OC_ASYNC_UPLOADS: true
        OC_INSECURE: false
        OC_JWT_SECRET:
          secret: jwt-secret
        OC_TRANSFER_SECRET:
          secret: transfer-secret
        OC_MACHINE_AUTH_API_KEY:
          secret: machine-auth-api-key
        OC_SYSTEM_USER_ID:
          secret: system-user-id
        OC_SYSTEM_USER_API_KEY:
          secret: system-user-api-key
        STORAGE_USERS_MOUNT_ID:
          secret: storage-users-mount-id
        GATEWAY_STORAGE_USERS_MOUNT_ID:
          secret: storage-users-mount-id
        OC_SERVICE_ACCOUNT_ID:
          secret: service-account-id
        OC_SERVICE_ACCOUNT_SECRET:
          secret: service-account-secret
        GRAPH_APPLICATION_ID:
          secret: graph-application-id
        OC_ADMIN_USER_ID: ""
        IDM_SVC_PASSWORD:
          secret: idm-service-user-password
        GRAPH_LDAP_BIND_PASSWORD:
          env: IDM_SVC_PASSWORD
        IDM_REVASVC_PASSWORD:
          secret: reva-service-user-password
        GROUPS_LDAP_BIND_PASSWORD:
          env: IDM_REVASVC_PASSWORD
        USERS_LDAP_BIND_PASSWORD:
          env: IDM_REVASVC_PASSWORD
        IDM_IDPSVC_PASSWORD:
          secret: idp-service-user-password
        IDP_LDAP_BIND_PASSWORD:
          env: IDM_IDPSVC_PASSWORD
        IDM_CREATE_DEMO_USERS: false
        OC_LDAP_BIND_PASSWORD:
          secret: ldap-bind-password
        OC_OIDC_ISSUER:
          extract:
            hostname: kanidm
            public: true
            scheme: https
          transform:
            string:
              template: "{value}/oauth2/openid/opencloud"
        OC_OIDC_CLIENT_ID: opencloud
        OC_EXCLUDE_RUN_SERVICES: idp
        PROXY_OIDC_REWRITE_WELLKNOWN: false
        PROXY_USER_OIDC_CLAIM: sub
        PROXY_USER_CS3_CLAIM: username
        PROXY_AUTOPROVISION_CLAIM_USERNAME: preferred_username
        PROXY_AUTOPROVISION_CLAIM_EMAIL: email
        PROXY_AUTOPROVISION_CLAIM_DISPLAYNAME: name
        PROXY_AUTOPROVISION_ACCOUNTS: true
        GRAPH_USERNAME_MATCH: none
        PROXY_ROLE_ASSIGNMENT_DRIVER: oidc
        GRAPH_ASSIGN_DEFAULT_USER_ROLE: false
        PROXY_ROLE_ASSIGNMENT_OIDC_CLAIM: role
        PROXY_CSP_CONFIG_FILE_LOCATION:
          extract:
            volume: opencloud-config
          transform:
            path: csp.yaml
        OC_SHARING_PUBLIC_SHARE_MUST_HAVE_PASSWORD: false
        STORAGE_USERS_DRIVER: posix
        STORAGE_USERS_ID_CACHE_STORE: nats-js-kv
        OC_BASE_DATA_PATH:
          volume: opencloud-data
