database:
  postgres:
    images:
      postgres:
        "17":
          repo: postgres
          tag: "17.4-bookworm"
      pgvector:
        "16":
          repo: ghcr.io/tensorchord/pgvecto-rs
          tag: "pg16-v0.3.0"
      postgis:
        "17":
          repo: postgis/postgis
          tag: "17-3.5"
    version: 17
    port: 5432
    data-dir: /var/lib/postgresql/data
    initdb-dir: /docker-entrypoint-initdb.d
    scripts:
      - path: replication.sh
        content: |
          #!/bin/bash
          set -eux
          echo 'host replication all all scram-sha-256' >> ${PGDATA}/pg_hba.conf
    env:
      username: POSTGRES_USER
      password: POSTGRES_PASSWORD
      database: POSTGRES_DB
      data-dir: PGDATA
    container:
      healthcheck:
        tests:
          - "CMD"
          - "pg_isready"
          - "-U"
          - env: POSTGRES_DB
        interval: 30s
        retries: 5
        timeout: 5s
      tmpfs:
        - /var/run/postgresql
