images:
  remote:
    qbittorrent:
      repo: lscr.io/linuxserver/qbittorrent
      tag: "5.0.4"
volumes:
  local:
    qbittorrent-config: {}
    qbittorrent-downloads:
      backup: false
services:
  qbittorrent:
    config:
      traefik:
        traefik:
          public: false
          service:
            port:
              env: WEBUI_PORT
    container:
      image: qbittorrent
      network:
        mode: vpn
      tmpfs:
        - path: /run
          exec: true
      volumes:
        qbittorrent-config: /config
        qbittorrent-downloads: /downloads
      envs:
        S6_READ_ONLY_ROOT: 1
        WEBUI_PORT: 8080
        TORRENTING_PORT:
          port: qbittorrent
      wud: {}
