images:
  remote:
    rxresume:
      repo: ghcr.io/amruthpillai/reactive-resume
      tag: "v4.4.5"
services:
  kanidm:
    config:
      state:
        systems:
          oauth2:
            rxresume:
              display-name: Reactive Resume
              origin-url:
                - extract:
                    hostname: rxresume
                    public: true
                    scheme: https
                  transform:
                    string:
                      template: "{value}/api/auth/openid/callback"
              origin-landing:
                hostname: rxresume
                public: true
                scheme: https
              prefer-short-username: true
              allow-insecure-client-disable-pkce: true
  rxresume:
    variables:
      OAUTH_URL:
        extract:
          hostname: kanidm
          public: true
          scheme: https
        transform:
          string:
            template: "{value}/oauth2/openid/rxresume"
    config:
      traefik:
        traefik:
          public: true
          service:
            port:
              env: PORT
    databases:
      postgres:
        postgres: {}
      redis:
        redis: {}
    secrets:
      access: {}
      refresh: {}
    container:
      image: rxresume
      databases:
        - postgres:
          envs:
            env: DATABASE_URL
            scheme: postgresql
        - redis:
          envs:
            env: REDIS_URL
      network:
        default-bridge: true
      envs:
        PORT: 3000
        NODE_ENV: production
        PUBLIC_URL:
          hostname: rxresume
          public: true
          scheme: https
        CHROME_TOKEN:
          service: chromium
          extract:
            secret: token
        CHROME_URL:
          hostname: chromium
          public: true
          scheme: wss
        ACCESS_TOKEN_SECRET:
          secret: access
        REFRESH_TOKEN_SECRET:
          secret: refresh
        # TODO: Enable this after https://github.com/AmruthPillai/Reactive-Resume/issues/2153
        DISABLE_SIGNUPS: true
        DISABLE_EMAIL_AUTH: false
        VITE_OPENID_NAME: Kanidm
        OPENID_AUTHORIZATION_URL:
          extract:
            hostname: kanidm
            public: true
            scheme: https
          transform:
            string:
              template: "{value}/ui/oauth2"
        OPENID_CALLBACK_URL:
          extract:
            hostname: rxresume
            public: true
            scheme: https
          transform:
            string:
              template: "{value}/api/auth/openid/callback"
        OPENID_CLIENT_ID: rxresume
        OPENID_CLIENT_SECRET:
          service: kanidm
          extract:
            export: rxresume
        OPENID_ISSUER: kanidm
        OPENID_SCOPE: openid profile email
        OPENID_TOKEN_URL:
          extract:
            hostname: kanidm
            public: true
            scheme: https
          transform:
            string:
              template: "{value}/oauth2/token"
        OPENID_USER_INFO_URL:
          extract:
            variable: OAUTH_URL
          transform:
            string:
              template: "{value}/userinfo"
