images:
  remote:
    seafile:
      repo: seafileltd/seafile-md-server
      tag: "13.0.1-testing"
services:
  seafile:
    config: {}
    databases:
      mysql:
        mysql:
          scripts:
            - path: setup-seafile-mysql.sql
              content: |
                CREATE DATABASE IF NOT EXISTS `ccnet` CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci';
                CREATE DATABASE IF NOT EXISTS `seahub` CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci';

                GRANT ALL PRIVILEGES ON `ccnet`.* TO 'seafile'@'%';
                GRANT ALL PRIVILEGES ON `seahub`.* TO 'seafile'@'%';

                FLUSH PRIVILEGES;
      redis:
        redis: {}
    container:
      image: seafile
