images:
  remote:
    seafile:
      repo: seafileltd/seafile-md-server
      tag: "13.0.1-testing"
services:
  seafile:
    config: {}
    secrets:
      jwt: {}
    databases:
      mysql:
        mysql:
          scripts:
            - path: setup-seafile-mysql.sql
              content: |
                CREATE DATABASE IF NOT EXISTS `ccnet` CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci';
                CREATE DATABASE IF NOT EXISTS `seahub` CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci';

                GRANT ALL PRIVILEGES ON `ccnet`.* TO 'seafile'@'%';
                GRANT ALL PRIVILEGES ON `seahub`.* TO 'seafile'@'%';

                FLUSH PRIVILEGES;
      redis:
        redis: {}
    container:
      image: seafile
      databases:
        - mysql:
          envs:
            username: SEAFILE_MYSQL_DB_USER
            password: SEAFILE_MYSQL_DB_PASSWORD
            database: SEAFILE_MYSQL_DB_SEAFILE_DB_NAME
            host: SEAFILE_MYSQL_DB_HOST
            port: SEAFILE_MYSQL_DB_PORT
        - redis:
          envs:
            password: REDIS_PASSWORD
            host: REDIS_HOST
            port: REDIS_PORT
      envs:
        SEAFILE_MYSQL_DB_CCNET_DB_NAME: ccnet
        SEAFILE_MYSQL_DB_SEAHUB_DB_NAME: seahub
        TIME_ZONE:
          docker: "{timezone}"
        JWT_PRIVATE_KEY:
          secret: jwt
        SEAFILE_LOG_TO_STDOUT: true
