images:
  remote:
    seafile:
      repo: seafileltd/seafile-md-server
      tag: "13.0.1-testing"
services:
  seafile:
    config: {}
    databases:
      mysql:
        mysql: {}
      redis:
        redis: {}
    container:
      image: seafile
