images:
  build:
    sqlite-backup:
      context:
        location: image/sqlite-backup
        base: python-alpine
        python-builder:
          image: python-builder
      version: "0.1.7"
volumes:
  local:
    sqlite-backup-data: {}
services:
  sqlite-backup:
    config:
      source-dir:
        env: HOMELAB_SOURCE_DIR
      dagu:
        docker:
          executor:
            run:
              model:
          dag:
            params:
              types:
                backup:
            tags: ["backup"]
          dags:
            backup:
              command:
                - homelab-sqlite-backup
                - param:
                    type: backup
    container:
      active: false
      image:
        build: sqlite-backup
      tmpfs:
        - /tmp
      volumes:
        sqlite-backup-data: /data
      envs:
        HOMELAB_SOURCE_DIR: /mnt
        HOMELAB_DESTINATION_DIR:
          volume: sqlite-backup-data
