images:
  remote:
    radarr:
      repo: ghcr.io/linuxserver/radarr
      tag: "5.22.4"
    sonarr:
      repo: ghcr.io/linuxserver/sonarr
      tag: "4.0.14"
volumes:
  local:
    starr-data:
      backup: false
    radarr-config: {}
    sonarr-config: {}
services:
  starr:
    config:
      traefik:
        radarr:
          name: radarr
          public: false
          service:
            container: radarr
            port:
              variable: RADARR_PORT
        sonarr:
          name: sonarr
          public: false
          service:
            container: sonarr
            port:
              variable: SONARR_PORT
    keepasses:
      radarr:
        hostname:
          hostname: starr-radarr
          public: false
      sonarr:
        hostname:
          hostname: starr-sonarr
          public: false
    variables:
      RADARR_PORT: 7878
      SONARR_PORT: 8989
    containers:
      radarr:
        image: radarr
        network:
          default-bridge: true
        tmpfs:
          - path: /run
            exec: true
        volumes:
          starr-data: /starr
          radarr-config: /config
        envs:
          S6_READ_ONLY_ROOT: 1
      sonarr:
        image: sonarr
        network:
          default-bridge: true
        tmpfs:
          - path: /run
            exec: true
        volumes:
          starr-data: /starr
          sonarr-config: /config
        envs:
          S6_READ_ONLY_ROOT: 1
