images:
  remote:
    tailscale:
      repo: ghcr.io/tailscale/tailscale
      tag: "v1.84.2"
volumes:
  local:
    tailscale-data: {}
services:
  tailscale:
    container:
      image: tailscale
      capabilities:
        - NET_ADMIN
      healthcheck:
        tests:
          - "CMD"
          - "wget"
          - "--spider"
          - "-q"
          - "http://localhost:9002/healthz"
        interval: 30s
        timeout: 5s
      network:
        default-bridge: true
        proxy-bridge: true
      ports:
        http:
          internal: 80
          external: 80
          ip: "0.0.0.0"
        https:
          internal: 443
          external: 443
          ip: "0.0.0.0"
          protocol: tcp
        h3:
          internal: 444
          external: 443
          ip: "0.0.0.0"
          protocol: udp
      tmpfs:
        - /tmp
        - /run
      volumes:
        tailscale-data: /var/lib/tailscale
      wud:
        template: https://tailscale.com/changelog
        include-prefix: v
      envs:
        TS_STATE_DIR:
          volume: tailscale-data
        TS_USERSPACE: false
        TS_AUTH_ONCE: true
        TS_ENABLE_HEALTH_CHECK: true
