images:
  remote:
    traefik:
      repo: traefik
      tag: "v3.4.3"
volumes:
  local:
    traefik-config:
      backup: false
    traefik-cert: {}
    traefik-plugin:
      backup: false
    traefik-data: {}
    traefik-tmp:
      backup: false
services:
  kanidm:
    config:
      state:
        systems:
          oauth2:
            kanidm:
              display-name: Kanidm
              origin-landing:
                hostname: kanidm
                public: true
                scheme: https
              prefer-short-username: true
  traefik:
    variables:
      CERT_PATH:
        extract:
          volume: traefik-cert
        transform:
          path: acme.json
      CONFIG_PATH:
        volume: traefik-config
      STATIC_PATH:
        extract:
          variable: CONFIG_PATH
        transform:
          path: static.toml
      API_PATH: /proxy
    config:
      path:
        static:
          variable: STATIC_PATH
        dynamic:
          extract:
            variable: CONFIG_PATH
          transform:
            path: dynamic
        api:
          variable: API_PATH
      acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        storage:
          variable: CERT_PATH
        disable-checks: false
        require-all-rns: false
        disable-ans-checks: true
        delay-before-checks: 60s
      entrypoint:
        public-http: "public-http"
        private-http: "private-http"
        public-https: "public-https"
        private-https: "private-https"
      timeout:
        read: 12h
        write: 12h
        idle: 12h
      plugins:
        crowdsec:
          name: github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
          version: "v1.4.2"
        geoblock:
          name: github.com/david-garcia-garcia/traefik-geoblock
          version: "v1.0.1"
        oidc:
          name: github.com/sevensolutions/traefik-oidc-auth
          version: "v0.12.0"
      traefik:
        geoblock:
          name: geoblock
          plugin: geoblock
          data:
            enabled: true
            defaultAllow: false
            databaseFilePath:
              extract:
                volume: traefik-plugin
              transform:
                path: sources
            allowedCountries:
            allowPrivate: true
            banIfError: true
            logLevel: "info"
            logFormat: "json"
            logBannedRequests: true
            databaseAutoUpdate: true
            databaseAutoUpdateDir:
              extract:
                volume: traefik-data
              transform:
                path: ip2database
        crowdsec:
          name: crowdsec
          plugin: crowdsec
          data:
            enabled: true
            crowdsecMode: stream
            crowdseclapikey:
              service: crowdsec
              extract:
                secret: traefik
            crowdsecLapiHost:
              service: crowdsec
              extract:
                name:
              transform:
                string:
                  template: "{value}:8080"
        oidc:
          name: oidc
          plugin: oidc
          data:
            Secret:
              secret: oidc
            Provider:
              Url:
                extract:
                  hostname: kanidm
                  public: true
                  scheme: https
                transform:
                  string:
                    template: "{value}/oauth2/openid/kanidm"
              ClientId: kanidm
              ClientSecret:
                service: kanidm
                extract:
                  export: kanidm
              TokenValidation: IdToken
              UsePkce: true
            Scopes: ["openid", "profile", "email"]
            Headers:
              - Name: X-Remote-User
                Value: "{{`{{ .claims.preferred_username }}`}}"
              - Name: X-Remote-Name
                Value: "{{`{{ .claims.name }}`}}"
              - Name: X-Remote-Email
                Value: "{{`{{ .claims.email }}`}}"
        dashboard:
          name: dashboard
          public: false
          hostname: system
          prefix:
            variable: API_PATH
          service: "api@internal"
    secrets:
      oidc:
        length: 32
    container:
      image: traefik
      command:
        - "traefik"
        - "--configFile"
        - variable: STATIC_PATH
      healthcheck:
        tests: ["CMD", "traefik", "healthcheck", "--ping"]
        interval: 30s
        timeout: 5s
        retries: 5
      labels:
        crowdsec.enable: true
        crowdsec.labels.type: traefik
      network:
        container:
          service: tailscale
          extract:
            id:
      wud:
        template: https://github.com/traefik/traefik/releases/tag/${original}
        include-prefix: v
      volumes:
        traefik-config:
          path: /etc/traefik/config
          read-only: true
        traefik-cert: /etc/traefik/cert
        traefik-plugin: /plugins-storage
        traefik-data: /data
        traefik-tmp: /tmp
