images:
  remote:
    xseed:
      repo: ghcr.io/cross-seed/cross-seed
      tag: "6.13.0"
volumes:
  local:
    xseed-config:
      backup:
        sqlites:
          - extract:
              volume: xseed-config
            transform:
              path: cross-seed.db
services:
  xseed:
    config:
      depends-on: [qbittorrent]
    container:
      image: xseed
      command: [daemon]
      user: "911:1001"
      wud:
        template: https://github.com/cross-seed/cross-seed/releases/tag/v${original}
      volumes:
        xseed-config: /config
        qbittorrent-downloads:
          service: qbittorrent
          extract:
            container:
            extract:
              volume: qbittorrent-downloads
        qbittorrent-starr:
          service: qbittorrent
          extract:
            container:
            extract:
              volume: qbittorrent-starr
