# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .application_key import *
from .bucket import *
from .bucket_file_version import *
from .bucket_notification_rules import *
from .get_account_info import *
from .get_application_key import *
from .get_bucket import *
from .get_bucket_file import *
from .get_bucket_file_signed_url import *
from .get_bucket_files import *
from .get_bucket_notification_rules import *
from .provider import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_b2.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_b2.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "b2",
  "mod": "index/applicationKey",
  "fqn": "pulumi_b2",
  "classes": {
   "b2:index/applicationKey:ApplicationKey": "ApplicationKey"
  }
 },
 {
  "pkg": "b2",
  "mod": "index/bucket",
  "fqn": "pulumi_b2",
  "classes": {
   "b2:index/bucket:Bucket": "Bucket"
  }
 },
 {
  "pkg": "b2",
  "mod": "index/bucketFileVersion",
  "fqn": "pulumi_b2",
  "classes": {
   "b2:index/bucketFileVersion:BucketFileVersion": "BucketFileVersion"
  }
 },
 {
  "pkg": "b2",
  "mod": "index/bucketNotificationRules",
  "fqn": "pulumi_b2",
  "classes": {
   "b2:index/bucketNotificationRules:BucketNotificationRules": "BucketNotificationRules"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "b2",
  "token": "pulumi:providers:b2",
  "fqn": "pulumi_b2",
  "class": "Provider"
 }
]
"""
)
