# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['ApplicationKeyArgs', 'ApplicationKey']

@pulumi.input_type
class ApplicationKeyArgs:
    def __init__(__self__, *,
                 capabilities: pulumi.Input[Sequence[pulumi.Input[_builtins.str]]],
                 key_name: pulumi.Input[_builtins.str],
                 b2_application_key_id: Optional[pulumi.Input[_builtins.str]] = None,
                 bucket_id: Optional[pulumi.Input[_builtins.str]] = None,
                 bucket_ids: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 name_prefix: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a ApplicationKey resource.

        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] capabilities: A set of strings, each one naming a capability the key has. **Modifying this attribute will force creation of a new resource.**
        :param pulumi.Input[_builtins.str] key_name: The name of the key. **Modifying this attribute will force creation of a new resource.**
        :param pulumi.Input[_builtins.str] bucket_id: When present, restricts access to one bucket. Conflicts with <span pulumi-lang-nodejs="`bucketIds`" pulumi-lang-dotnet="`BucketIds`" pulumi-lang-go="`bucketIds`" pulumi-lang-python="`bucket_ids`" pulumi-lang-yaml="`bucketIds`" pulumi-lang-java="`bucketIds`">`bucket_ids`</span>. **Modifying this attribute will force creation of a new resource.**
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] bucket_ids: When provided, the new key can only access the specified buckets. **Modifying this attribute will force creation of a new resource.**
        :param pulumi.Input[_builtins.str] name_prefix: When present, restricts access to files whose names start with the prefix. **Modifying this attribute will force creation of a new resource.**
        """
        pulumi.set(__self__, "capabilities", capabilities)
        pulumi.set(__self__, "key_name", key_name)
        if b2_application_key_id is not None:
            pulumi.set(__self__, "b2_application_key_id", b2_application_key_id)
        if bucket_id is not None:
            warnings.warn("""Deprecated""", DeprecationWarning)
            pulumi.log.warn("""bucket_id is deprecated: Deprecated""")
        if bucket_id is not None:
            pulumi.set(__self__, "bucket_id", bucket_id)
        if bucket_ids is not None:
            pulumi.set(__self__, "bucket_ids", bucket_ids)
        if name_prefix is not None:
            pulumi.set(__self__, "name_prefix", name_prefix)

    @_builtins.property
    @pulumi.getter
    def capabilities(self) -> pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]:
        """
        A set of strings, each one naming a capability the key has. **Modifying this attribute will force creation of a new resource.**
        """
        return pulumi.get(self, "capabilities")

    @capabilities.setter
    def capabilities(self, value: pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]):
        pulumi.set(self, "capabilities", value)

    @_builtins.property
    @pulumi.getter(name="keyName")
    def key_name(self) -> pulumi.Input[_builtins.str]:
        """
        The name of the key. **Modifying this attribute will force creation of a new resource.**
        """
        return pulumi.get(self, "key_name")

    @key_name.setter
    def key_name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "key_name", value)

    @_builtins.property
    @pulumi.getter(name="b2ApplicationKeyId")
    def b2_application_key_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "b2_application_key_id")

    @b2_application_key_id.setter
    def b2_application_key_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "b2_application_key_id", value)

    @_builtins.property
    @pulumi.getter(name="bucketId")
    @_utilities.deprecated("""Deprecated""")
    def bucket_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        When present, restricts access to one bucket. Conflicts with <span pulumi-lang-nodejs="`bucketIds`" pulumi-lang-dotnet="`BucketIds`" pulumi-lang-go="`bucketIds`" pulumi-lang-python="`bucket_ids`" pulumi-lang-yaml="`bucketIds`" pulumi-lang-java="`bucketIds`">`bucket_ids`</span>. **Modifying this attribute will force creation of a new resource.**
        """
        return pulumi.get(self, "bucket_id")

    @bucket_id.setter
    def bucket_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "bucket_id", value)

    @_builtins.property
    @pulumi.getter(name="bucketIds")
    def bucket_ids(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        When provided, the new key can only access the specified buckets. **Modifying this attribute will force creation of a new resource.**
        """
        return pulumi.get(self, "bucket_ids")

    @bucket_ids.setter
    def bucket_ids(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "bucket_ids", value)

    @_builtins.property
    @pulumi.getter(name="namePrefix")
    def name_prefix(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        When present, restricts access to files whose names start with the prefix. **Modifying this attribute will force creation of a new resource.**
        """
        return pulumi.get(self, "name_prefix")

    @name_prefix.setter
    def name_prefix(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name_prefix", value)


@pulumi.input_type
class _ApplicationKeyState:
    def __init__(__self__, *,
                 application_key: Optional[pulumi.Input[_builtins.str]] = None,
                 application_key_id: Optional[pulumi.Input[_builtins.str]] = None,
                 b2_application_key_id: Optional[pulumi.Input[_builtins.str]] = None,
                 bucket_id: Optional[pulumi.Input[_builtins.str]] = None,
                 bucket_ids: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 capabilities: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 key_name: Optional[pulumi.Input[_builtins.str]] = None,
                 name_prefix: Optional[pulumi.Input[_builtins.str]] = None,
                 options: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None):
        """
        Input properties used for looking up and filtering ApplicationKey resources.

        :param pulumi.Input[_builtins.str] application_key: The key.
        :param pulumi.Input[_builtins.str] application_key_id: The ID of the newly created key.
        :param pulumi.Input[_builtins.str] bucket_id: When present, restricts access to one bucket. Conflicts with <span pulumi-lang-nodejs="`bucketIds`" pulumi-lang-dotnet="`BucketIds`" pulumi-lang-go="`bucketIds`" pulumi-lang-python="`bucket_ids`" pulumi-lang-yaml="`bucketIds`" pulumi-lang-java="`bucketIds`">`bucket_ids`</span>. **Modifying this attribute will force creation of a new resource.**
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] bucket_ids: When provided, the new key can only access the specified buckets. **Modifying this attribute will force creation of a new resource.**
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] capabilities: A set of strings, each one naming a capability the key has. **Modifying this attribute will force creation of a new resource.**
        :param pulumi.Input[_builtins.str] key_name: The name of the key. **Modifying this attribute will force creation of a new resource.**
        :param pulumi.Input[_builtins.str] name_prefix: When present, restricts access to files whose names start with the prefix. **Modifying this attribute will force creation of a new resource.**
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] options: List of application key options.
        """
        if application_key is not None:
            pulumi.set(__self__, "application_key", application_key)
        if application_key_id is not None:
            pulumi.set(__self__, "application_key_id", application_key_id)
        if b2_application_key_id is not None:
            pulumi.set(__self__, "b2_application_key_id", b2_application_key_id)
        if bucket_id is not None:
            warnings.warn("""Deprecated""", DeprecationWarning)
            pulumi.log.warn("""bucket_id is deprecated: Deprecated""")
        if bucket_id is not None:
            pulumi.set(__self__, "bucket_id", bucket_id)
        if bucket_ids is not None:
            pulumi.set(__self__, "bucket_ids", bucket_ids)
        if capabilities is not None:
            pulumi.set(__self__, "capabilities", capabilities)
        if key_name is not None:
            pulumi.set(__self__, "key_name", key_name)
        if name_prefix is not None:
            pulumi.set(__self__, "name_prefix", name_prefix)
        if options is not None:
            pulumi.set(__self__, "options", options)

    @_builtins.property
    @pulumi.getter(name="applicationKey")
    def application_key(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The key.
        """
        return pulumi.get(self, "application_key")

    @application_key.setter
    def application_key(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "application_key", value)

    @_builtins.property
    @pulumi.getter(name="applicationKeyId")
    def application_key_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The ID of the newly created key.
        """
        return pulumi.get(self, "application_key_id")

    @application_key_id.setter
    def application_key_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "application_key_id", value)

    @_builtins.property
    @pulumi.getter(name="b2ApplicationKeyId")
    def b2_application_key_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "b2_application_key_id")

    @b2_application_key_id.setter
    def b2_application_key_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "b2_application_key_id", value)

    @_builtins.property
    @pulumi.getter(name="bucketId")
    @_utilities.deprecated("""Deprecated""")
    def bucket_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        When present, restricts access to one bucket. Conflicts with <span pulumi-lang-nodejs="`bucketIds`" pulumi-lang-dotnet="`BucketIds`" pulumi-lang-go="`bucketIds`" pulumi-lang-python="`bucket_ids`" pulumi-lang-yaml="`bucketIds`" pulumi-lang-java="`bucketIds`">`bucket_ids`</span>. **Modifying this attribute will force creation of a new resource.**
        """
        return pulumi.get(self, "bucket_id")

    @bucket_id.setter
    def bucket_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "bucket_id", value)

    @_builtins.property
    @pulumi.getter(name="bucketIds")
    def bucket_ids(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        When provided, the new key can only access the specified buckets. **Modifying this attribute will force creation of a new resource.**
        """
        return pulumi.get(self, "bucket_ids")

    @bucket_ids.setter
    def bucket_ids(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "bucket_ids", value)

    @_builtins.property
    @pulumi.getter
    def capabilities(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        A set of strings, each one naming a capability the key has. **Modifying this attribute will force creation of a new resource.**
        """
        return pulumi.get(self, "capabilities")

    @capabilities.setter
    def capabilities(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "capabilities", value)

    @_builtins.property
    @pulumi.getter(name="keyName")
    def key_name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The name of the key. **Modifying this attribute will force creation of a new resource.**
        """
        return pulumi.get(self, "key_name")

    @key_name.setter
    def key_name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "key_name", value)

    @_builtins.property
    @pulumi.getter(name="namePrefix")
    def name_prefix(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        When present, restricts access to files whose names start with the prefix. **Modifying this attribute will force creation of a new resource.**
        """
        return pulumi.get(self, "name_prefix")

    @name_prefix.setter
    def name_prefix(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name_prefix", value)

    @_builtins.property
    @pulumi.getter
    def options(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        List of application key options.
        """
        return pulumi.get(self, "options")

    @options.setter
    def options(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "options", value)


@pulumi.type_token("b2:index/applicationKey:ApplicationKey")
class ApplicationKey(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 b2_application_key_id: Optional[pulumi.Input[_builtins.str]] = None,
                 bucket_id: Optional[pulumi.Input[_builtins.str]] = None,
                 bucket_ids: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 capabilities: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 key_name: Optional[pulumi.Input[_builtins.str]] = None,
                 name_prefix: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Create a ApplicationKey resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] bucket_id: When present, restricts access to one bucket. Conflicts with <span pulumi-lang-nodejs="`bucketIds`" pulumi-lang-dotnet="`BucketIds`" pulumi-lang-go="`bucketIds`" pulumi-lang-python="`bucket_ids`" pulumi-lang-yaml="`bucketIds`" pulumi-lang-java="`bucketIds`">`bucket_ids`</span>. **Modifying this attribute will force creation of a new resource.**
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] bucket_ids: When provided, the new key can only access the specified buckets. **Modifying this attribute will force creation of a new resource.**
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] capabilities: A set of strings, each one naming a capability the key has. **Modifying this attribute will force creation of a new resource.**
        :param pulumi.Input[_builtins.str] key_name: The name of the key. **Modifying this attribute will force creation of a new resource.**
        :param pulumi.Input[_builtins.str] name_prefix: When present, restricts access to files whose names start with the prefix. **Modifying this attribute will force creation of a new resource.**
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ApplicationKeyArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a ApplicationKey resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param ApplicationKeyArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ApplicationKeyArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 b2_application_key_id: Optional[pulumi.Input[_builtins.str]] = None,
                 bucket_id: Optional[pulumi.Input[_builtins.str]] = None,
                 bucket_ids: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 capabilities: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 key_name: Optional[pulumi.Input[_builtins.str]] = None,
                 name_prefix: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ApplicationKeyArgs.__new__(ApplicationKeyArgs)

            __props__.__dict__["b2_application_key_id"] = b2_application_key_id
            __props__.__dict__["bucket_id"] = bucket_id
            __props__.__dict__["bucket_ids"] = bucket_ids
            if capabilities is None and not opts.urn:
                raise TypeError("Missing required property 'capabilities'")
            __props__.__dict__["capabilities"] = capabilities
            if key_name is None and not opts.urn:
                raise TypeError("Missing required property 'key_name'")
            __props__.__dict__["key_name"] = key_name
            __props__.__dict__["name_prefix"] = name_prefix
            __props__.__dict__["application_key"] = None
            __props__.__dict__["application_key_id"] = None
            __props__.__dict__["options"] = None
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["applicationKey"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(ApplicationKey, __self__).__init__(
            'b2:index/applicationKey:ApplicationKey',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            application_key: Optional[pulumi.Input[_builtins.str]] = None,
            application_key_id: Optional[pulumi.Input[_builtins.str]] = None,
            b2_application_key_id: Optional[pulumi.Input[_builtins.str]] = None,
            bucket_id: Optional[pulumi.Input[_builtins.str]] = None,
            bucket_ids: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            capabilities: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            key_name: Optional[pulumi.Input[_builtins.str]] = None,
            name_prefix: Optional[pulumi.Input[_builtins.str]] = None,
            options: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None) -> 'ApplicationKey':
        """
        Get an existing ApplicationKey resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] application_key: The key.
        :param pulumi.Input[_builtins.str] application_key_id: The ID of the newly created key.
        :param pulumi.Input[_builtins.str] bucket_id: When present, restricts access to one bucket. Conflicts with <span pulumi-lang-nodejs="`bucketIds`" pulumi-lang-dotnet="`BucketIds`" pulumi-lang-go="`bucketIds`" pulumi-lang-python="`bucket_ids`" pulumi-lang-yaml="`bucketIds`" pulumi-lang-java="`bucketIds`">`bucket_ids`</span>. **Modifying this attribute will force creation of a new resource.**
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] bucket_ids: When provided, the new key can only access the specified buckets. **Modifying this attribute will force creation of a new resource.**
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] capabilities: A set of strings, each one naming a capability the key has. **Modifying this attribute will force creation of a new resource.**
        :param pulumi.Input[_builtins.str] key_name: The name of the key. **Modifying this attribute will force creation of a new resource.**
        :param pulumi.Input[_builtins.str] name_prefix: When present, restricts access to files whose names start with the prefix. **Modifying this attribute will force creation of a new resource.**
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] options: List of application key options.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _ApplicationKeyState.__new__(_ApplicationKeyState)

        __props__.__dict__["application_key"] = application_key
        __props__.__dict__["application_key_id"] = application_key_id
        __props__.__dict__["b2_application_key_id"] = b2_application_key_id
        __props__.__dict__["bucket_id"] = bucket_id
        __props__.__dict__["bucket_ids"] = bucket_ids
        __props__.__dict__["capabilities"] = capabilities
        __props__.__dict__["key_name"] = key_name
        __props__.__dict__["name_prefix"] = name_prefix
        __props__.__dict__["options"] = options
        return ApplicationKey(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="applicationKey")
    def application_key(self) -> pulumi.Output[_builtins.str]:
        """
        The key.
        """
        return pulumi.get(self, "application_key")

    @_builtins.property
    @pulumi.getter(name="applicationKeyId")
    def application_key_id(self) -> pulumi.Output[_builtins.str]:
        """
        The ID of the newly created key.
        """
        return pulumi.get(self, "application_key_id")

    @_builtins.property
    @pulumi.getter(name="b2ApplicationKeyId")
    def b2_application_key_id(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "b2_application_key_id")

    @_builtins.property
    @pulumi.getter(name="bucketId")
    @_utilities.deprecated("""Deprecated""")
    def bucket_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        When present, restricts access to one bucket. Conflicts with <span pulumi-lang-nodejs="`bucketIds`" pulumi-lang-dotnet="`BucketIds`" pulumi-lang-go="`bucketIds`" pulumi-lang-python="`bucket_ids`" pulumi-lang-yaml="`bucketIds`" pulumi-lang-java="`bucketIds`">`bucket_ids`</span>. **Modifying this attribute will force creation of a new resource.**
        """
        return pulumi.get(self, "bucket_id")

    @_builtins.property
    @pulumi.getter(name="bucketIds")
    def bucket_ids(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        When provided, the new key can only access the specified buckets. **Modifying this attribute will force creation of a new resource.**
        """
        return pulumi.get(self, "bucket_ids")

    @_builtins.property
    @pulumi.getter
    def capabilities(self) -> pulumi.Output[Sequence[_builtins.str]]:
        """
        A set of strings, each one naming a capability the key has. **Modifying this attribute will force creation of a new resource.**
        """
        return pulumi.get(self, "capabilities")

    @_builtins.property
    @pulumi.getter(name="keyName")
    def key_name(self) -> pulumi.Output[_builtins.str]:
        """
        The name of the key. **Modifying this attribute will force creation of a new resource.**
        """
        return pulumi.get(self, "key_name")

    @_builtins.property
    @pulumi.getter(name="namePrefix")
    def name_prefix(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        When present, restricts access to files whose names start with the prefix. **Modifying this attribute will force creation of a new resource.**
        """
        return pulumi.get(self, "name_prefix")

    @_builtins.property
    @pulumi.getter
    def options(self) -> pulumi.Output[Sequence[_builtins.str]]:
        """
        List of application key options.
        """
        return pulumi.get(self, "options")

