# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetBucketFileResult',
    'AwaitableGetBucketFileResult',
    'get_bucket_file',
    'get_bucket_file_output',
]

@pulumi.output_type
class GetBucketFileResult:
    """
    A collection of values returned by getBucketFile.
    """
    def __init__(__self__, bucket_id=None, file_name=None, file_versions=None, id=None, show_versions=None):
        if bucket_id and not isinstance(bucket_id, str):
            raise TypeError("Expected argument 'bucket_id' to be a str")
        pulumi.set(__self__, "bucket_id", bucket_id)
        if file_name and not isinstance(file_name, str):
            raise TypeError("Expected argument 'file_name' to be a str")
        pulumi.set(__self__, "file_name", file_name)
        if file_versions and not isinstance(file_versions, list):
            raise TypeError("Expected argument 'file_versions' to be a list")
        pulumi.set(__self__, "file_versions", file_versions)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if show_versions and not isinstance(show_versions, bool):
            raise TypeError("Expected argument 'show_versions' to be a bool")
        pulumi.set(__self__, "show_versions", show_versions)

    @_builtins.property
    @pulumi.getter(name="bucketId")
    def bucket_id(self) -> _builtins.str:
        return pulumi.get(self, "bucket_id")

    @_builtins.property
    @pulumi.getter(name="fileName")
    def file_name(self) -> _builtins.str:
        return pulumi.get(self, "file_name")

    @_builtins.property
    @pulumi.getter(name="fileVersions")
    def file_versions(self) -> Sequence['outputs.GetBucketFileFileVersionResult']:
        return pulumi.get(self, "file_versions")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="showVersions")
    def show_versions(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "show_versions")


class AwaitableGetBucketFileResult(GetBucketFileResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetBucketFileResult(
            bucket_id=self.bucket_id,
            file_name=self.file_name,
            file_versions=self.file_versions,
            id=self.id,
            show_versions=self.show_versions)


def get_bucket_file(bucket_id: Optional[_builtins.str] = None,
                    file_name: Optional[_builtins.str] = None,
                    id: Optional[_builtins.str] = None,
                    show_versions: Optional[_builtins.bool] = None,
                    opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetBucketFileResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['bucketId'] = bucket_id
    __args__['fileName'] = file_name
    __args__['id'] = id
    __args__['showVersions'] = show_versions
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('b2:index/getBucketFile:getBucketFile', __args__, opts=opts, typ=GetBucketFileResult, package_ref=_utilities.get_package()).value

    return AwaitableGetBucketFileResult(
        bucket_id=pulumi.get(__ret__, 'bucket_id'),
        file_name=pulumi.get(__ret__, 'file_name'),
        file_versions=pulumi.get(__ret__, 'file_versions'),
        id=pulumi.get(__ret__, 'id'),
        show_versions=pulumi.get(__ret__, 'show_versions'))
def get_bucket_file_output(bucket_id: Optional[pulumi.Input[_builtins.str]] = None,
                           file_name: Optional[pulumi.Input[_builtins.str]] = None,
                           id: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                           show_versions: Optional[pulumi.Input[Optional[_builtins.bool]]] = None,
                           opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetBucketFileResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['bucketId'] = bucket_id
    __args__['fileName'] = file_name
    __args__['id'] = id
    __args__['showVersions'] = show_versions
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('b2:index/getBucketFile:getBucketFile', __args__, opts=opts, typ=GetBucketFileResult, package_ref=_utilities.get_package())
    return __ret__.apply(lambda __response__: GetBucketFileResult(
        bucket_id=pulumi.get(__response__, 'bucket_id'),
        file_name=pulumi.get(__response__, 'file_name'),
        file_versions=pulumi.get(__response__, 'file_versions'),
        id=pulumi.get(__response__, 'id'),
        show_versions=pulumi.get(__response__, 'show_versions')))
