# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetBucketFilesResult',
    'AwaitableGetBucketFilesResult',
    'get_bucket_files',
    'get_bucket_files_output',
]

@pulumi.output_type
class GetBucketFilesResult:
    """
    A collection of values returned by getBucketFiles.
    """
    def __init__(__self__, bucket_id=None, file_versions=None, folder_name=None, id=None, recursive=None, show_versions=None):
        if bucket_id and not isinstance(bucket_id, str):
            raise TypeError("Expected argument 'bucket_id' to be a str")
        pulumi.set(__self__, "bucket_id", bucket_id)
        if file_versions and not isinstance(file_versions, list):
            raise TypeError("Expected argument 'file_versions' to be a list")
        pulumi.set(__self__, "file_versions", file_versions)
        if folder_name and not isinstance(folder_name, str):
            raise TypeError("Expected argument 'folder_name' to be a str")
        pulumi.set(__self__, "folder_name", folder_name)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if recursive and not isinstance(recursive, bool):
            raise TypeError("Expected argument 'recursive' to be a bool")
        pulumi.set(__self__, "recursive", recursive)
        if show_versions and not isinstance(show_versions, bool):
            raise TypeError("Expected argument 'show_versions' to be a bool")
        pulumi.set(__self__, "show_versions", show_versions)

    @_builtins.property
    @pulumi.getter(name="bucketId")
    def bucket_id(self) -> _builtins.str:
        return pulumi.get(self, "bucket_id")

    @_builtins.property
    @pulumi.getter(name="fileVersions")
    def file_versions(self) -> Sequence['outputs.GetBucketFilesFileVersionResult']:
        return pulumi.get(self, "file_versions")

    @_builtins.property
    @pulumi.getter(name="folderName")
    def folder_name(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "folder_name")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def recursive(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "recursive")

    @_builtins.property
    @pulumi.getter(name="showVersions")
    def show_versions(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "show_versions")


class AwaitableGetBucketFilesResult(GetBucketFilesResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetBucketFilesResult(
            bucket_id=self.bucket_id,
            file_versions=self.file_versions,
            folder_name=self.folder_name,
            id=self.id,
            recursive=self.recursive,
            show_versions=self.show_versions)


def get_bucket_files(bucket_id: Optional[_builtins.str] = None,
                     folder_name: Optional[_builtins.str] = None,
                     id: Optional[_builtins.str] = None,
                     recursive: Optional[_builtins.bool] = None,
                     show_versions: Optional[_builtins.bool] = None,
                     opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetBucketFilesResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['bucketId'] = bucket_id
    __args__['folderName'] = folder_name
    __args__['id'] = id
    __args__['recursive'] = recursive
    __args__['showVersions'] = show_versions
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('b2:index/getBucketFiles:getBucketFiles', __args__, opts=opts, typ=GetBucketFilesResult, package_ref=_utilities.get_package()).value

    return AwaitableGetBucketFilesResult(
        bucket_id=pulumi.get(__ret__, 'bucket_id'),
        file_versions=pulumi.get(__ret__, 'file_versions'),
        folder_name=pulumi.get(__ret__, 'folder_name'),
        id=pulumi.get(__ret__, 'id'),
        recursive=pulumi.get(__ret__, 'recursive'),
        show_versions=pulumi.get(__ret__, 'show_versions'))
def get_bucket_files_output(bucket_id: Optional[pulumi.Input[_builtins.str]] = None,
                            folder_name: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                            id: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                            recursive: Optional[pulumi.Input[Optional[_builtins.bool]]] = None,
                            show_versions: Optional[pulumi.Input[Optional[_builtins.bool]]] = None,
                            opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetBucketFilesResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['bucketId'] = bucket_id
    __args__['folderName'] = folder_name
    __args__['id'] = id
    __args__['recursive'] = recursive
    __args__['showVersions'] = show_versions
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('b2:index/getBucketFiles:getBucketFiles', __args__, opts=opts, typ=GetBucketFilesResult, package_ref=_utilities.get_package())
    return __ret__.apply(lambda __response__: GetBucketFilesResult(
        bucket_id=pulumi.get(__response__, 'bucket_id'),
        file_versions=pulumi.get(__response__, 'file_versions'),
        folder_name=pulumi.get(__response__, 'folder_name'),
        id=pulumi.get(__response__, 'id'),
        recursive=pulumi.get(__response__, 'recursive'),
        show_versions=pulumi.get(__response__, 'show_versions')))
