# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

import types

__config__ = pulumi.Config('netbird')


class _ExportableConfig(types.ModuleType):
    @_builtins.property
    def management_url(self) -> Optional[str]:
        return __config__.get('managementUrl')

    @_builtins.property
    def tenant_account(self) -> Optional[str]:
        return __config__.get('tenantAccount')

    @_builtins.property
    def token(self) -> Optional[str]:
        return __config__.get('token')

