{
 "title": "Traefik",
 "panels": [
  {
   "title": "Raw Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Access Logs",
     "type": "logs",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
     "targets": [
      { "displayMode": "logs", "organization": "default", "query": "select * from traefik", "stream": "traefik" }
     ]
    }
   ]
  },
  { "title": "Geography", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Geographic Distribution",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "displayMode": "auto",
     "organization": "default",
     "query": "select geoip_location_latitude as latitude, geoip_location_longitude as longitude, count(*) as request_count from traefik where geoip_location_latitude is not null and geoip_location_longitude is not null group by geoip_location_latitude, geoip_location_longitude",
     "stream": "traefik"
    }
   ]
  },
  {
   "title": "Top Countries",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "displayMode": "auto",
     "organization": "default",
     "query": "select coalesce(geoip_country_name, geoip_registered_country_name) as country_name, count(*) as request_count from traefik group by country_name having country_name is not null order by request_count desc",
     "stream": "traefik"
    }
   ]
  },
  {
   "title": "Top Geoblocked Countries",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "displayMode": "auto",
     "organization": "default",
     "query": "select coalesce(geoip_country_name, geoip_registered_country_name) as country_name, count(*) as request_count from traefik where downstream_x_geoblock_remediation is not null group by country_name order by request_count desc",
     "stream": "traefik"
    }
   ]
  }
 ]
}