records:
  solar:
    host: sun
    source-ip: ddns
  sun:
    host: sun
    source-ip: hmesh
    records:
      mail:
        routable: false
      xseed:
        routable: false
  earth:
    host: earth
    source-ip: hmesh
    records:
      docker-proxy:
        routable: false
      dozzle:
        routable: false
      dagu:
        routable: false
