[project]
name = "homelab-sqlite-backup"
version = "0.1.0"
requires-python = ">=3.13.1"
dependencies = [
    "loguru>=0.7.3",
    "sqlite-backup>=0.1.7",
    "typed-argument-parser>=1.10.1",
]

[project.scripts]
homelab-sqlite-backup = "main:main"
