database:
  postgres:
    images:
      vectorchord:
        "17":
          repo: ghcr.io/immich-app/postgres
          tag: "17-vectorchord0.4.3"
          container:
            healthcheck:
            tmpfs:
              - /etc/postgresql
      postgis:
        "17":
          repo: postgis/postgis
          tag: "17-3.5"
