[project]
name = "homelab-wintele"
version = "0.1.0"
requires-python = ">=3.13.1"
dependencies = [
    "docker[ssh]>=7.1.0",
    "pyotp>=2.9.0",
    "pyrate-limiter>=3.7.1",
    "python-json-logger>=3.3.0",
    "python-telegram-bot[webhooks]>=22.2",
]

[project.scripts]
homelab-wintele = "main:main"
